### ISSUE TITLE
Instance encounter states: Save to DB

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#1]
Saving the states to db.

**Comment by Zyres** [comment]
Function available and need to be implemented in every script....

**Comment by Zyres** [comment]
Encounter saving already done. To handle the savings see:
076368fcd92b1b84eb1014f3f050ac30daf4d465
a8bda706b8e249eb7cbd93b1f8491691bbe791a7
114cde7f925cec5d660a5ecd6a0bea92afe42235
f55874f96b90069a8714d0e0735cd724307c7e6f
8d18cfd2f6cd1a696a0085cb4e2f8ea6e4e5c8a9
