### ISSUE TITLE
👾 [Bug Report] Player equipped items are not sent to other clients (TBC)

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#1006]
**Description**: 
Player equipped items are not sent to other clients in TBC. If you have two clients logged in players are always naked to each other, and if you try to inspect their gear the equipped items are not there.

**Steps to reproduce the problem**: 
1. Login with 2 clients
2. See how the other client is naked
3. Try inspect their gear and see how they don't have any items equipped

**Expansion version**: 
TBC only

**AscEmu hash/commit**: 
https://github.com/AscEmu/AscEmu/commit/ed3f5c3416a1beeb9697cd7693769156cf0d0aa0

**Operating system**: 
Win 10

**Comment by schnek** [comment]
![image](https://user-images.githubusercontent.com/1216225/163454740-832abbce-9bf4-424a-90b2-6dd7e4d049c5.png)
wotlk
