### ISSUE TITLE
AddTimer is not working

### ISSUE THREAD

**Issue by Cronicman** [AscEmu/AscEmu#101]
The moonscript command AddTimer is not working, i'm on the latest commit.

**Comment by Zyres** [comment]
Shure?
Have you checked other scripts?

**Comment by Cronicman** [comment]
Yes I'm sure. Its my own custom script. Nothing happens when I use it like the timer isn't working when I get home I'll post my script I use
timer1 = AddTimer(40000); 
iN aiupdate I have istimerfinished but I have the timer start whenever the npc loads

**Comment by Cronicman** [comment]
I'm trying to fix violet hold it is almost done but it won't work without the timers

**Comment by Cronicman** [comment]
Invalid Issue - sorry for the report.

**Comment by Evairfairy** [comment]
@Cronicman Sorry for the late reply

This would be difficult to change as it would no doubt break legacy behaviour, so would require some planning before making any changes ;)

Perhaps in future
