### ISSUE TITLE
👾 [Bug Report] Quest Icons are wrong

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#1024]
**Description**: 
Quest Icons on Creatures are wrong, u can see the Pickup Icon for the Quests u already Have when its directly finishable.

**Steps to reproduce the problem**: 
1.  go to Trisfal Glades
2.  Take Quest A rogues Deal https://classic.wowhead.com/quest=590/a-rogues-deal
3.  Notice how u still able to select the npc and see the quest u already picked up

**Comment by schnek** [comment]
fix (https://github.com/AscEmu/AscEmu/pull/1023)

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/83e98c09ba063ae25976f6b86f65b935f0277a44
