### ISSUE TITLE
💡 [Feature Request] Automatic database updater and pull requests with SQL files

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#1028]
**Description**: 
There is a problem if there are multiple pull requests with SQL files merged at the same time.
Let's make an example; 3 pull requests from different users and all are merged at the same time.
User A adds a world db update with id 100
User B adds a world db update with id 101
User C adds a world db update with id 102

Each user then checkout develop and start the server. User A would receive updates from both User B and User C. However, User B will receive the update from User C but will not receive the update from User A. User C as he added an update with id 102 will not receive the updates from User A or User B since his update is already the latest.

So I think the id column should be dropped. On server startup the contents in sql/updates folder are compared to all rows in world_db_version, and if there is an update in sql folder that is not in the table then that update should be applied, regardless if its an older update. Of course the latest db version should still be checked.

So if we look at the example again. User C has not started server for a while and in addition to those two older updates from User A and B there are two new updates from Users D and E. User C pulls new changes and starts the server and the automatic updater notices there are two new updates but also notices that there are two older updates that are in sql folder but are not in world_db_version, and will apply them before applying the updates from Users D and E.

**Comment by Zyres** [comment]
Closing this feature request. Everything should be fine if we correctly merge the PRs

**Comment by Appled** [comment]
> Everything should be fine if we correctly merge the PRs

The problem was never at AE's end, it's at user's end.

- User A, B and C make each their own pull requests with world database fixes.
- A has the update with id 100, B with 101 and C with 102.
- All 3 are merged "correctly" to AE.
- All users now checkout develop and start the server.
- User A since he had id 100 would get updates from B and C normally.
- B would not get the update from A since his db already has update 101, but will get update from C.
- C would not get update from A nor from B since his database is considered to be up to date.

I'm still rooting for dropping the id row. There shouldn't be any problems afaik.
