### ISSUE TITLE
Console colours not correctly terminated

### ISSUE THREAD

**Issue by Evairfairy** [AscEmu/AscEmu#103]
Summary:
On Linux, when console text is set to a specific colour, it is not correctly terminated at the end of the string, resulting in the colour being incorrectly applied to other texts.

Desired outcome:
Text should revert to the default colour at the end of the coloured string.

Example of bug:
![image](https://cloud.githubusercontent.com/assets/1409096/6988382/be3d2b34-da48-11e4-8a4c-2225dbed1ff6.png)

To reproduce:
Launch an AscEmu server executable without a valid conf file available.

**Comment by armm77** [comment]
thanks for report, I will review the error.

**Comment by armm77** [comment]
Please check and comets me. @Evairfairy 
https://github.com/armm77/AscEmu/commit/ea5e8370dbdd791ae7d96ac67e58a3cf213cf6f7

**Comment by Evairfairy** [comment]
@armm77 Your changes are fine, please submit a pull request
