### ISSUE TITLE
👾 [Bug Report] problem with starting zone dk

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1030]
**Description**: 
problem with starting zone dk (no spawn npc)

**Steps to reproduce the problem**: 
1. create new dk

**Expansion version**: 

Patch 4.3.4 - Cataclysm

**add: now this problem is massive for all npc and go**

**Comment by schnek** [comment]
now this problem is massive for all npc and go, for all version

**Comment by Appled** [comment]
> now this problem is massive for all npc and go, for all version

https://github.com/AscEmu/AscEmu/commit/227c631fb8ccd8389e2a5b260e0ce2f33d16c2f9 fixes this 😉

**Comment by schnek** [comment]
😉

**Comment by schnek** [comment]
I hope it's not because https://github.com/AscEmu/AscEmu/pull/1027/files#diff-feca6782d1ba4aaa36350a268c51a560b8dbd5343be5ebf6375bc6600e5b1a69R43

**Comment by Appled** [comment]
> I hope it's not because https://github.com/AscEmu/AscEmu/pull/1027/files#diff-feca6782d1ba4aaa36350a268c51a560b8dbd5343be5ebf6375bc6600e5b1a69R43 (43-45)

No it's not. I can fix this later today or tomorrow.

**Comment by schnek** [comment]
![image](https://user-images.githubusercontent.com/1216225/173249802-1a7b1297-d523-46b4-a07a-856b4bb19ef2.png)

fix https://github.com/AscEmu/AscEmu/pull/1036
