### ISSUE TITLE
💡 [Feature Request] Refactoring of Hellfire Ramparts

### ISSUE THREAD

**Issue by Razfury** [AscEmu/AscEmu#1040]
**Description**: 
A total rescript and refactor of the burning crusade instance Hellfire Rampart as the current scripts are outdated or do not work.

- [ ] [Watchkeeper Gargolmar](https://tbc.wowhead.com/npc=17306/watchkeeper-gargolmar)
- [ ] [Omor the Unscarred](https://tbc.wowhead.com/npc=17308/omor-the-unscarred)
- [ ] [Nazan](https://tbc.wowhead.com/npc=17536/nazan) & [Vazruden](https://tbc.wowhead.com/npc=17537/vazruden)

Instances spawns need fixed as well but that is a separate issue for all TBC instances.

Patch Versions:
- Patch 2.4.3 (The Burning Crusade)
- Patch 3.3.5 (Wrath of Lich King)
- Patch 4.3.4 (Cataclysm)
- Patch 5.4.8 (Mists of Pandaria)

**Comment by Zyres** [comment]
Hey @Razfury would you mind to work on this, or is it just a wish?
