### ISSUE TITLE
💡 [Feature Request] Refactoring of Blood Furnace

### ISSUE THREAD

**Issue by Razfury** [AscEmu/AscEmu#1041]
**Description**: 
A total rescript and refactor of the burning crusade instance Blood Furnace as the current scripts are outdated or do not work.

- [ ] [The Maker](https://tbc.wowhead.com/npc=17381)
- [ ] [Broggok](https://tbc.wowhead.com/npc=17380)
- [ ] [Keli'dan the Breaker](https://tbc.wowhead.com/npc=17377)

Instances spawns need fixed as well but that is a separate issue for all TBC instances.

Patch Versions:
- Patch 2.4.3 (The Burning Crusade)
- Patch 3.3.5 (Wrath of Lich King)
- Patch 4.3.4 (Cataclysm)
- Patch 5.4.8 (Mists of Pandaria)

**Comment by Zyres** [comment]
Hey @Razfury would you mind to work on this, or is it just a wish?
