### ISSUE TITLE
💡 [Feature Request] Refactoring of Shattered Halls

### ISSUE THREAD

**Issue by Razfury** [AscEmu/AscEmu#1042]
**Description**: 
A total rescript and refactor of the burning crusade instance Shattered Halls as the current scripts are outdated or do not work.

- [ ] [Grand Warlock Nethekurse](https://tbc.wowhead.com/npc=16807)
- [ ] [Blood Guard Porung-HEROIC ONLY](https://tbc.wowhead.com/npc=20923)
- [ ] [Warbringer O'mrogg](https://tbc.wowhead.com/npc=16809)
- [ ] [Warchief Kargath Bladefist](https://tbc.wowhead.com/npc=16808)

Instances spawns need fixed as well but that is a separate issue for all TBC instances.

Patch Versions:
- Patch 2.4.3 (The Burning Crusade)
- Patch 3.3.5 (Wrath of Lich King)
- Patch 4.3.4 (Cataclysm)
- Patch 5.4.8 (Mists of Pandaria)

**Comment by Zyres** [comment]
Hey @Razfury would you mind to work on this, or is it just a wish?
