### ISSUE TITLE
👾 [Bug Report] lua.obj : build warning LNK4006 when assembling for all versions

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1052]
Windows: 
Build warning LNK4006 when assembling for all versions

Debian:
/usr/bin/ld: ../../../dep/lualib/src/liblualib.a(loslib.c.o): in function `os_tmpname':
loslib.c:(.text+0x3b1): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

**Comment by schnek** [comment]
for information

**Comment by Zyres** [comment]
This comes from a dep (external code). Since this is just a warning, we should be fine to ignore it.
