### ISSUE TITLE
👾 [Bug Report] start ./world error in linux 

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1053]
**Steps to reproduce the problem**: 
1.start world 
![image](https://user-images.githubusercontent.com/1216225/188326278-99714b98-d3cd-40be-b025-64edcfa7d021.png)
(report Ludow)

**Expansion version**: 

- Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 

latest dev

**Operating system**: 

- Platform: Linux (debian 11)

**Comment by Appled** [comment]
Confirmed on Ubuntu but when I restarted server there were no errors 🤔

**Comment by schnek** [comment]
the problem is due to the fact that the file has a lot of warning. the file is not uploaded completely (deb11)

**Comment by Zyres** [comment]
I checked the file world_base.sql it looks pretty complete to me.

**Comment by Appled** [comment]
I cannot reproduce this on Ubuntu anymore. Could be same as https://github.com/AscEmu/AscEmu/issues/1054
