### ISSUE TITLE
👾 [Bug Report]

### ISSUE THREAD

**Issue by glitchtime25** [AscEmu/AscEmu#1054]
**Description**: 

When I am trying to start WotlK World Server, I got the following ERROR:

`13:20:29 [INFO]: Loaded instances in 4 ms
13:20:29 [INFO]: MySQLDataLoads : Table item_pages has 3 columns
13:20:29 [INFO]: MySQLDataLoads : Loaded 1647 pages from item_pages table in 50 ms!
13:20:31 [INFO]: MySQLDataLoads : Table item_properties has 128 columns
13:20:32 [INFO]: MySQLDataLoads : Loaded 38616 item_properties in 2559 ms!
13:20:32 [INFO]: MySQLDataLoads : Table creature_properties_movement has 8 columns
13:20:32 [INFO]: MySQLDataLoads : Loaded 4345 creature movement data in 25 ms!
13:20:34 [INFO]: MySQLDataLoads : Table creature_properties has 76 columns
Segmentation fault (core dumped)`

**Steps to reproduce the problem**: 
1. cd /path/to/ascemu/
2. ./world
3. 
4.

**Expansion version**: 

    - Patch 3.3.5 - WoTLK

**AscEmu hash/commit**: 

4299a7ce78b3759fbc2a4f056c1048344f262fd3

**Operating system**: 

    - Platform: Linux

**Comment by Appled** [comment]
Hey, sorry for late reply. This should be fixed on our develop branch.
