### ISSUE TITLE
⚙ [Support Request] Vmaps extractor not working (TBC)

### ISSUE THREAD

**Issue by Kutsikas** [AscEmu/AscEmu#1065]
**Description**: 
I tried to compile TBC core and after compiling I found a bug. In C:\AscEmu\tools have something messed up because after
ae_tools.bat running I extract maps but when I try to extract vmaps then it does not support TBC version and says I Opening Data\enGB/lichking-locale-enGB.MPQ
Error opening archive 'Data\enGB/lichking-locale-enGB.MPQ': Does file really exist?https://pastebin.com/GyRSntF0
Look like the extractor is bugged and no extract TBC vmaps somehow. I show it in discord dudes to and it says I need to ask support to fix this issue

**Steps to reproduce**: 
1. no
2. ideas
3. fix
4. it

**Expansion version**: 

**AscEmu hash/commit**: 

**Operating system**:

**Comment by schnek** [comment]
![image](https://user-images.githubusercontent.com/1216225/203351767-7fb11457-8d33-4a24-9d75-65a6a9e67021.png)
yes solution extractor vmaps as wotlk and because of this problem
i disabled files wotlk and it started working as it should (from Buildings)
