### ISSUE TITLE
TBC frs server npcs no move and no attack back/box in hands

### ISSUE THREAD

**Issue by Kutsikas** [AscEmu/AscEmu#1067]
**Description**: 
compiling new TBC  repack and extracting all maps and stuff in. after when I go server I try to attack NPC and it is not attack me back or move when I attack npc. they are braindead. another problem is some NPCs have boxes in hand hope it can fix!

**Steps to reproduce**: 
1. 
2. 
3. 
4.

**Expansion version**: 

    Specify version - is required:
  
    - Patch 2.4.3 - TBC
   

 - Platform: Windows

**Comment by Kutsikas** [comment]
https://ibb.co/jhQ5RFM
https://ibb.co/LS0v08m
https://ibb.co/BjVG53v
https://ibb.co/y0C4yKD
https://ibb.co/7p9PhbJ

**Comment by schnek** [comment]
already had something like this..
