### ISSUE TITLE
⚙ [Support Request] Trainers are missing spells

### ISSUE THREAD

**Issue by Kutsikas** [AscEmu/AscEmu#1068]
**Description**: 
 cant learn skills Trainer NPCs.wen go to trainer click it then u no have any menu to learn any spells
https://ibb.co/NC6RTKM

**Expansion version**: 
    Specify version - is required:
    
    - Patch 2.4.3 - TBC
**AscEmu hash/commit**: 
7ae986735
**Operating system**: 
    - Platform: Windows

**Comment by schnek** [comment]
@Kutsikas need npc id and info it works on 3.3.5
