### ISSUE TITLE
Battlemasters no work TBC

### ISSUE THREAD

**Issue by Kutsikas** [AscEmu/AscEmu#1069]
Battlemasters no work  still no work when I try to speak  battlemaster and no give me any many to go join the bg queue

<a href="https://ibb.co/hXPHfV3"><img src="https://i.ibb.co/FsSJVzR/Wo-WScrn-Shot-112322-194047.jpg" alt="Wo-WScrn-Shot-112322-194047" border="0"></a>

**Steps to reproduce**: 
1. 
2. 
3. 
4.

**Expansion version**:

 - Patch 2.4.3 - TBC

**AscEmu hash/commit**: 

**Operating system**:

    - Platform: Windows

**Comment by Zyres** [comment]
so how did you solved it?

**Comment by Kutsikas** [comment]
looks like I fixed but after when I tried it its not still not work

**Comment by schnek** [comment]
@Kutsikas need npc id and info it works on 3.3.5

**Comment by schnek** [comment]
fix?
