### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Kutsikas** [AscEmu/AscEmu#1071]
**Description**: 
I tried npc make  follow my waypoints but when I add a waypoint server just crashed.-{[world server crashed}

**Steps to reproduce**: 
1. 
2. 
3. 
4.

**Expansion version**:
    - Patch 2.4.3 - TBC

**AscEmu hash/commit**: 

**Operating system**:

    - Platform: Windows

**Comment by aaron02** [comment]
can you post a sql with your custom waypoints to reproduce your issue ?

**Comment by Kutsikas** [comment]
I can't make add any weapons just when I try to add them server crashed. I just share the discord screen with MR.schnek when it happens.just click on npc and click addon to add waypoint and  all game blow off

**Comment by Kutsikas** [comment]
Look like after needing a fix NPC can move because after the server run up again I added some waypoints but NPC is not followed to waypoints only when making NPC beacon does it comes to me or moved.https://imgur.com/a/nDDY02X

**Comment by aaron02** [comment]
check if movementtype in creature_spawns table for your npc is set at 
![image](https://user-images.githubusercontent.com/1266630/203645096-e547c4b7-d898-4cc1-92eb-4e8e79702d16.png)

**Comment by aaron02** [comment]
this should be fixed
