### ISSUE TITLE
i try attribute my server

### ISSUE THREAD

**Issue by Kutsikas** [AscEmu/AscEmu#1072]
**Description**: 
I try to attribute my server up :
 UPDATE item_properties SET `stat_value1` = 10;
UPDATE item_properties SET `stat_value2` = 10;
UPDATE item_properties SET `stat_value3` = 10;
UPDATE item_properties SET `stat_value4` = 10;
UPDATE item_properties SET `stat_value5` = 10;
UPDATE item_properties SET `stat_value6` = 10;
UPDATE item_properties SET `stat_value7` = 10;
UPDATE item_properties SET `stat_value8` = 10;
UPDATE item_properties SET `stat_value9` = 10;
UPDATE item_properties SET `stat_value10` = 10;
(code tnx by schnek)

and its no affect my server weapons

**Steps to reproduce**: 
1. 
2. 
3. 
4.

**Expansion version**:

    - Patch 2.4.3 - TBC

**AscEmu hash/commit**: 

**Operating system**:

    - Platform: Windows
-->

**Comment by schnek** [comment]
i just changed item -> item_properties 😁😄

**Comment by aaron02** [comment]
when these are existing items then u have to clear wow cache
