### ISSUE TITLE
COMPILE ERROR (build with tools)

### ISSUE THREAD

**Issue by glitchtime25** [AscEmu/AscEmu#1078]
**Description**: 

I got the following ERROR if I compile with TOOLS (-DBUILD_TOOLS=1)

`
[ 61%] Building CXX object src/tools/mmaps_generator/CMakeFiles/mmaps_generator.dir/MapBuilder.cpp.o
In file included from /root/ae_wotlk/src/tools/mmaps_generator/MapBuilder.cpp:21:
/root/ae_wotlk/src/tools/mmaps_generator/MapBuilder.h:49:30: error: expected unqualified-id before ‘)’ token
   49 |     ProducerConsumerQueue<T>() : _shutdown(false) { }
      |                              ^
make[2]: *** [src/tools/mmaps_generator/CMakeFiles/mmaps_generator.dir/build.make:90: src/tools/mmaps_generator/CMakeFiles/mmaps_generator.dir/MapBuilder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1015: src/tools/mmaps_generator/CMakeFiles/mmaps_generator.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

**Steps to reproduce the problem**:
1. Use CMAKE with **-DBUILD_TOOLS=1**
2. Start compiling (make)

**Expansion version**:
    - (Patch 1.12.1 - Classic) (not tested)
    - Patch 2.4.3 - TBC
    - Patch 3.3.5 - WoTLK
    - Patch 4.3.4 - Cataclysm
    - Patch 5.4.8 - Mop

**AscEmu hash/commit**: 

commit c421c6748f44d3ac686e0e352d562573059be8bf (HEAD -> master, origin/master, origin/HEAD)

**Operating system**:

    - Platform: Linux

**Comment by schnek** [comment]
confirm 😟
