### ISSUE TITLE
GameEventMgr: Specific faction for event spawns

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#108]
Unfortunately this "Issue" was only reported in the forum.
http://www.board.ascemu.org/index.php/Thread/24-GameEvent-Proposal/?postID=56#post56

By spawning event_creature_spawns, the faction (set in event_creature_spawns. faction) is not set. Currently the faction from creature_proto is set, but thats not correct.

By checking some commits I saw this line: https://github.com/AscEmu/AscEmu/commit/5ca11b8352cd8d9392a2f00b6db915f21599c416#diff-751bf3e494c1bbd17eae64a57ad1e24cR96
Maybe this can be included in GameEventMgr...

@armm77 Is this correct explained?

**Comment by armm77** [comment]
Yes, this well explained.
You could also edit the display id, so that no alliances within the hordes areas and vice versa.
