### ISSUE TITLE
👾 [Bug Report] Server has crashed

### ISSUE THREAD

**Issue by Kutsikas** [AscEmu/AscEmu#1080]
**Description**: 
I compile fresh core and start the login server and then the world server to import data in. all go well all stuff goes in and when it ends server crashes .all the time when I start importing, again and again, its crashes all time. it looks like world_base.sql crashed my server because when I remove it all sqls go in and I can go into the server but there are no NPCs in the server. and when I use the world_base.sql server mess up no idea maybe I'm making something wrong
****************************************************************************************
world-normal.log

=================[2023-01-01 18:46:50]=================
18:46:50 [ERROR]: << AscEmu /Debug-Windows x64 (AMD64) :: World Server >>
18:46:50 [ERROR]: ========================================================
18:46:50 [INFO]: The key combination <Ctrl-C> will safely shut down the server.
18:46:50 [INFO]: Config : Loading Config Files...
18:46:50 [INFO]: Config : configs/world.conf loaded
18:46:50 [INFO]: MySQLDatabase : Connecting to `localhost`, database `ascemu_world`...
18:46:50 [INFO]: MySQLDatabase : Connecting to `localhost`, database `ascemu_char`...
18:46:50 [INFO]: Required dir C:\Develoment\AscEmu_server\configs found!
18:46:50 [INFO]: Required dir C:\Develoment\AscEmu_server\dbc found!
18:46:50 [INFO]: Required dir C:\Develoment\AscEmu_server\maps found!
18:46:50 [INFO]: Database character Version : 20220415-00_account_instance_times
18:46:50 [INFO]: Database world Version : 20211025-00_magtheridon_spawns
18:46:50 [ERROR][MAJOR]: Server has crashed. Creating crash dump file CrashDumps\dump-world.exe--2023-1-1-18-46-50-9324.dmp
18:46:50 [ERROR][MAJOR]: Crash Handler : Advanced crash handler initialized.
18:46:50 [INFO]: sql : Waiting for all database queries to finish...
18:46:50 [INFO]: sql : All pending database operations cleared.
18:46:50 [INFO]: Saving all players to database...
18:46:50 [INFO]: Saved 0 players.
18:46:50 [INFO]: sql : Data saved.
18:46:50 [INFO]: Server : Closing.
********************************************************************************************************************
world-error.log

=================[2023-01-01 18:46:50]=================
18:46:50 [ERROR]: << AscEmu /Debug-Windows x64 (AMD64) :: World Server >>
18:46:50 [ERROR]: ========================================================
18:46:50 [ERROR][MAJOR]: Server has crashed. Creating crash dump file CrashDumps\dump-world.exe--2023-1-1-18-46-50-9324.dmp
18:46:50 [ERROR][MAJOR]: Crash Handler : Advanced crash handler initialized.

CrashDumps : https://files.fm/u/vxrjqfrv8

**Steps to reproduce the problem**: 
1. server
2. crashed
3. 
4.

**Expansion version**:   Patch 2.4.3 - TBC

**AscEmu hash/commit**: 

**Operating system**:  Platform: Windows

**Comment by schnek** [comment]
your update

> 18:46:50 [INFO]: Database world Version : 20211025-00_magtheridon_spawns

develop latest update

![image](https://user-images.githubusercontent.com/1216225/210179227-a0ad1143-95f5-4a27-be9d-b18e1d20f5b2.png)

**Comment by Kutsikas** [comment]
why did my world.exe crash then? I no have still no ideas

**Comment by Appled** [comment]
> ok get fixed but now no NPC no items in-game. run in game little time word server.exe crashed

Have you followed [installation guide](https://ascemu.github.io/Wiki/docs/installation/windows/#database-setup) in our wiki and downloaded OneDB?
Because it sounds like you've installed the world base file which intentionally contains only table structures.

**Comment by Kutsikas** [comment]
have OneDB my developer folder and follow the tutorial! still, no NPCs and no items in the game + word server.exe crashed
![errrord](https://user-images.githubusercontent.com/118775171/210233963-2a2f980a-f38a-4023-832d-62b863a1e0aa.png)

**Comment by Zyres** [comment]
I guess you are not following the installation guid correctly. Delete all tables in your ascemu_world database and let ascemu set up the database for you.

**Comment by Kutsikas** [comment]
Still same no npc no items
![nahui](https://user-images.githubusercontent.com/118775171/210413318-9a3e2a24-423f-49a7-bf00-456095639554.png)

**Comment by Zyres** [comment]
Teamviewer?

**Comment by Zyres** [comment]
closed - my.ini changed to handle the large amount of data.
