### ISSUE TITLE
👾 [Bug Report] Cant learn talents on max level

### ISSUE THREAD

**Issue by Kutsikas** [AscEmu/AscEmu#1085]
**Description**: 
Cant learn talents at all when I make the account max level and try to learn talents then looks like talents are frozen and I no cant learn talents :(
wen go to battle master then all different battle masters are allowed to join only one battleground

**Steps to reproduce**: 
1. cant learn talents
2. battle masters need to fix
3. 
4.

**Expansion version**:  - Patch 2.4.3 - TBC
**AscEmu hash/commit**: 
**Operating system**:  - Platform: Windows

**Comment by Appled** [comment]
https://github.com/AscEmu/AscEmu/issues/1171
