### ISSUE TITLE
👾 [Bug Report] gm commands gocreature work incorrectly

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1096]
**Description**: 

gm commands gocreature work incorrectly

**Steps to reproduce the problem**: 
1.  use the command .gocreature 
2. make sure id is there
![image](https://user-images.githubusercontent.com/1216225/222987626-6edb743b-4252-46d8-8ef0-f0287bf83390.png)
3. .gocreature 34777
![image](https://user-images.githubusercontent.com/1216225/222987655-8e0c3624-90ac-4238-8a27-1939a440342f.png)

**Expansion version**: 

Specify version - is required:

- Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 

latest dev

**Comment by Appled** [comment]
That's because NPC with guid 34777 is not spawned in Cata
![Query](https://user-images.githubusercontent.com/346848/222993763-7bdb7f93-24be-42c5-85f3-77b6577d39b2.png)

Try NPC guid 34771, it should be spawned in Cata

**Comment by schnek** [comment]
then it is at least not clear. if you add that the minimum and maximum build is such and such, it would be clearer.

**Comment by Zyres** [comment]
But the min/max build is there to make it clear ;-)

**Comment by schnek** [comment]
😉

**Comment by schnek** [comment]
haha i decided to check it out
![image](https://user-images.githubusercontent.com/1216225/223206614-db612295-d5e7-4d6c-aa91-cf0dbc66414e.png)

.gocreature 54443 (cata)

![image](https://user-images.githubusercontent.com/1216225/223206710-269cba75-ba1f-4428-bd8a-ee4967a61ad9.png)

.gocreature 54472 (cata)

![image](https://user-images.githubusercontent.com/1216225/223207077-5254c7dd-0f8c-44b0-ae49-20332f4057ff.png)

here is something else 🤗😁😅
