### ISSUE TITLE
👾 [Bug Report] problems with transport - not teleport (сata version)

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1100]
**Description**: 

on the сata version again problems with transport)  most importantly does not teleport

**Steps to reproduce the problem**: 
![image](https://github.com/AscEmu/AscEmu/assets/1216225/99075a4f-396e-486b-b0c7-990be7a6aec9)
the test was conducted in the white sectors

**Expansion version**: 
    - Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 

latest develop

**Operating system**: 
    - Platform: Windows

**Comment by Zyres** [comment]
Closed since latest develop is merged to master
