### ISSUE TITLE
👾 [Bug Report] npc cannot deal damage to a character

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1104]
**Steps to reproduce the problem**: 
1. create character and attack npc
![image](https://github.com/AscEmu/AscEmu/assets/1216225/fedcde88-a3dd-45db-974e-81a3515b66ab)
as you can see, 2 NPCs do not hit the character.

**Expansion version**: 
    - Patch 4.3.4 - Cataclysm
    - Patch 5.4.8 - Mop

**AscEmu hash/commit**: 

**Operating system**: 
    - Platform: Windows

**Comment by Appled** [comment]
Check from database what's the NPC's mindamage and maxdamage. I remember there are some cata NPCs that don't have min and max damages set.

**Comment by schnek** [comment]
the player himself cannot inflict damage on himself. for example, if it falls from a great height.

**Comment by Appled** [comment]
> for example, if it falls from a great height.
That is not related to this issue but I know why it's not working... 😖

**Comment by schnek** [comment]
yes i want to open another one😀

**Comment by schnek** [comment]
fix.
