### ISSUE TITLE
👾 [Bug Report] npc attack speed is more than it should be.

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1105]
**Steps to reproduce the problem**: 

1.checked here
![image](https://github.com/AscEmu/AscEmu/assets/1216225/2610b279-615b-4d39-87d4-b899d8338abc)

2. find 2 npc's fighting each other
![image](https://github.com/AscEmu/AscEmu/assets/1216225/7ff285cf-4366-4b64-8df9-51a3f839f836)

**Expansion version**: 
    - Patch 4.3.4 - Cataclysm
    - Patch 5.4.8 - Mop

**Operating system**: 
    - Platform: Windows

**Comment by Appled** [comment]
Check from database what's their attack speed. I think some NPCs had speed at 0 or something. That's why they're attacking really fast.

**Comment by schnek** [comment]
fix. is no longer related to thrust, but it is important for the execution mechanics. npc's now kill each other, but must hit themselves forever and must be neutral. maybe add a new neutral faction?

**Comment by Appled** [comment]
> fix. is no longer related to thrust, but it is important for the execution mechanics. npc's now kill each other, but must hit themselves forever and must be neutral. maybe add a new neutral faction?

That's just a low priority visual event where some npcs should keep fighting forever without killing each other, but if the original issue (attack speed) is fixed I think this should be closed.
