### ISSUE TITLE
👾 [Bug Report] Modules not Loading

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#1108]
**Description**: 
![image](https://github.com/AscEmu/AscEmu/assets/1266630/f7badf37-8cb4-47d6-a718-36d973d807b9)

Modules are not Loading

I deleted my build folder and made an new one, and rebuild from scratch. I hope its no issue from my side :)

**Steps to reproduce the problem**: 
1. Build Develop
2. Start Worldserver
3. Watch Logs

**AscEmu hash/commit**: 
Develop

**Comment by schnek** [comment]
I'll take care of it today (most likely it is because of my changes).
