### ISSUE TITLE
💡 [Feature Request] Additional Event "onTaunt" for creature_ai_scripts

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#1115]
**Description**: 

Event_OnTaunt is not possible wit creature_ai_scripts. would be perfect to have this. @aaron02

**Comment by aaron02** [comment]
which functions do you like to happen on taunt?

**Comment by Zyres** [comment]
Cast spell and message 😊

**Comment by aaron02** [comment]
good thats working in my pr :)
