### ISSUE TITLE
👾 [Bug Report] chat problem on all versions

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1127]
**Steps to reproduce the problem**: 
1.  write a message to the chat if you don't have this problem, 

**Expansion version**: 

    - Patch 2.4.3 - TBC
    - Patch 3.3.5 - WoTLK
    - Patch 4.3.4 - Cataclysm
    - Patch 5.4.8 - Mop

**AscEmu hash/commit**: 

    - latest develop

**Operating system**: 

    - Platform: Linux
    - Platform: Windows

**Comment by Zyres** [comment]
With ruRU dbc there is no problem on my machine. maybe it is some kind of problem with client.

**Comment by schnek** [comment]
Patch 2.4.3 - TBC 
![image](https://github.com/AscEmu/AscEmu/assets/1216225/78c9d02f-c752-4cc8-97fe-aa393a01aa51)

`22:22:46 [INFO]: World : Using enGB/enUS DBC locale`

**Comment by schnek** [comment]
closed

![image](https://github.com/AscEmu/AscEmu/assets/1216225/832f3a9a-f4d9-4ca8-b686-43cec74e71bc)

**Comment by schnek** [comment]
relevant again 😅

**Comment by aaron02** [comment]
i have no chat problem tried deDE Dbcs and enUS also 2 Different Clients

**Comment by schnek** [comment]
And if you enter the gm commands, is there no problem?

**Comment by aaron02** [comment]
no problem for me atleast u did anything specific? you deleted wow cache folder?

**Comment by schnek** [comment]
the messages are the simplest, the same as yours) and I increased the speed of GM commands (3.3.5)

**Comment by aaron02** [comment]
can u provide more info when it crashes its pretty hard to find out what u did xD

**Comment by schnek** [comment]
problem in relations with LuaScripts. closed..
