### ISSUE TITLE
👾 [Bug Report] CMake Warning

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1128]
**Steps to reproduce the problem**: 

1. start building AE project with linux or ci

cmake -DCMAKE_INSTALL_PREFIX=~/server -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=WotLK

  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

![image](https://github.com/AscEmu/AscEmu/assets/1216225/be787ce5-8cb4-4594-8980-0857e1d830fd)

**Expansion version**: 

    Specify version - is required:
    - Patch 1.12.1 - Classic
    - Patch 2.4.3 - TBC
    - Patch 3.3.5 - WoTLK
    - Patch 4.3.4 - Cataclysm
    - Patch 5.4.8 - Mop

**AscEmu hash/commit**: 

    - latest dev

**Operating system**: 

    - Platform: Linux

**Comment by Zyres** [comment]
Your cmake command looks wrong.

Here an example:

```
mkdir server
cd server
cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=WotLK
cd ..
cd server
make -j 4
cd ..
```
