### ISSUE TITLE
👾 [Bug Report] Crash when entering the game.

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1139]
**Steps to reproduce the problem**: 
1. create a character format and enter the game. Crash 
![image](https://github.com/AscEmu/AscEmu/assets/1216225/e59111f8-8236-4190-9c32-0edef002178b)

**Expansion version**: 

    Specify version - is required:
    - Patch 2.4.3 - TBC (enGB)
    - Patch 3.3.5 - WoTLK (enGB/ruRU)
    - Patch 4.3.4 - Cataclysm (enGB/ruRU)

**AscEmu hash/commit**: 

latest dev

**Operating system**: 

    - Platform: Windows

**Comment by schnek** [comment]
These changes resolve the login issue [Object.cpp#L1506](https://github.com/AscEmu/AscEmu/blob/develop/src/world/Objects/Object.cpp#L1506)
```
-        delete *itr;
+        // delete *itr;
```

Test Patch: 3.3.5

**Comment by sanctum32** [comment]
can confirm, running in debugger also triggered that code line https://github.com/AscEmu/AscEmu/blob/develop/src/world/Objects/Object.cpp#L1506, can confirm, commenting out fixes issue

**Comment by schnek** [comment]
The problem is still the same upon exit, I haven’t found it yet.

**Comment by schnek** [comment]
checked, ok closed...
