### ISSUE TITLE
Instance script timers are based on update frequency

### ISSUE THREAD

**Issue by Naravia** [AscEmu/AscEmu#114]
Timers used in instance scripts are based on update frequency instead of real time

This means that using a custom update frequency will "break" all timers, in that they'll update slower - it also means if a tick takes longer than its update frequency to complete, timers will be inaccurate

Fix: Replace timer code with code based on system time instead of update ticker

Warnings: Scripts with custom update frequencies may be built around this logic - changes to this will, of course, break these scripts

**Comment by Zyres** [comment]
@aaron02 I'm pretty sure we changed something about timers in the last 1-2 years. Do you see here a problem with the statement Naravia posted in 2015? Give me a sign if we can close this issue :-)

**Comment by aaron02** [comment]
yes this should be done by now
