### ISSUE TITLE
👾 [Bug Report] caught another crash 😅(Crash, kill NPCs 10-15 minutes)

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1146]
**Description**: 
caught another crash 😅

**Steps to reproduce the problem**: 
1. just kill NPCs for 10-15 minutes. Crash
![image](https://github.com/AscEmu/AscEmu/assets/1216225/2bd586fc-b232-42f4-a2c6-eaeb56e3c9de)

**Expansion version**: 

    - Patch 3.3.5 - WoTLK

**AscEmu hash/commit**: 

dev

**Operating system**: 

    - Platform: Windows

**Comment by aaron02** [comment]
should be resolved try again

**Comment by schnek** [comment]
fix
