### ISSUE TITLE
Hackfixes and SpellLinks

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#115]
Last night I finished the implementation of the sql table spell_linked_spell.
I removed all Hackfixes for Holy Nova, started the server and test these spells. Unfortunately I forgot the values for this table, but Holy Nova works fine.... o.O
It seems we have to check the spells in Hackfixes...

**Comment by DankoDJ** [comment]
I will start with this issue the next few days... prepare yourself...

**Comment by Zyres** [comment]
I finished this task. Check out the changes in Hackfixes.cpp in our world project.
