### ISSUE TITLE
Creating a guild crashes the server

### ISSUE THREAD

**Issue by Deuzz** [AscEmu/AscEmu#116]
If you create a guild using .guild create - it will crash the server.
If you use the NPC to create one - it will crash the server too.

**Comment by Evairfairy** [comment]
I successfully created a guild using !guild create on the latest develop branch

Can someone else confirm this is an issue or not please?

**Comment by Zyres** [comment]
I changed the MOTD, Servercrash by sending unexpected packet size.

**Comment by Evairfairy** [comment]
I successfully changed the MOTD of my guild without crash. What did you change it to? What is your guild name?

**Comment by Evairfairy** [comment]
I'll take a closer look at this when I can

**Comment by Deuzz** [comment]
Using "!guild create ServerTeam" crashes the server for me too :/
It doesn't add it to the guild table

**Comment by Evairfairy** [comment]
![image](https://cloud.githubusercontent.com/assets/1409096/8551737/530fa53a-24d0-11e5-90bf-90cdc9dbdfda.png)

It works for me without any problems. Is this on develop or master?

**Comment by Zyres** [comment]
@Deuzz : Use the latest version ( a quick fix was pushed to master 40 mins ago)

**Comment by DankoDJ** [comment]
Currently if a guild was created, relog with char crashes the server.
