### ISSUE TITLE
👾 [Bug Report] errors when building on Linux (Clang)

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1161]
**Description**: 

errors when building on Linux

![image](https://github.com/AscEmu/AscEmu/assets/1216225/4e1aabda-d6d0-4063-9437-e3e510ef32bb)

**Steps to reproduce the problem**: 
1.  start assembling the kernel
cmake -DCMAKE_INSTALL_PREFIX=~/server -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=WotLK

**Expansion version**: 

**AscEmu hash/commit**: 

    - latest dev

**Operating system**: 

    - Platform: Linux (deb)

**Comment by Appled** [comment]
g++ on Linux is fine so the problem is with Clang

**Comment by schnek** [comment]
fix develop
