### ISSUE TITLE
Paladin-Actionbar

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#117]
Actionbar for Paladin.... awsome but not like it should be.

Related to issue #70 

http://www.pic-upload.de/view-27615972/paladin.jpg.html

How to reproduce:
Set your char to level 80 and use .char learn all

**Comment by Razfury** [comment]
On my old core i had this fixed, i'll see what i changed and open a P/R for this.

**Comment by Zyres** [comment]
Related to #973
