### ISSUE TITLE
👾 [Bug Report] Debugging World and logon.exe / world.exe failed

### ISSUE THREAD

**Issue by Thorek93** [AscEmu/AscEmu#1191]
**Description**: 
Hello, after the compile i have all folders with world and logon.exe i create configs and expansionfolder. All perfect only in compile i see was 1 point was skipped. Now i would start logon.exe and it open window "Microsoft Visual C++ Runtime Library: Debug Error! abort has been called (Press Retry to debug the application) 

Now i was check the Link and was use all instruction: https://ascemu.github.io/Wiki/docs/docs_core/debugging/
It stop in raw 3274  return static_cast<bool>(_Mypair._Myval2);
Mail:"Exception thrown: Read access violation
“this one” was “0x18”."

**Steps to reproduce the problem**: 
1. My Login now work becau i have the configs in the direct ascemu folder and not in the config folder used
2. Now i can start all ty
3. 
4.

**Expansion version**: 

**AscEmu hash/commit**: 

**Operating system**: 

![fehler2](https://github.com/AscEmu/AscEmu/assets/7281911/633c254b-f86f-46b6-8f53-0317e6ed941f)
![bild1fehler](https://github.com/AscEmu/AscEmu/assets/7281911/e8e5dda9-7746-4e59-b427-7ca0fc14618c)

**Comment by schnek** [comment]
https://ascemu.github.io/Wiki/docs/installation/windows/#configuration
need to move the conf directory to the server folder 🐱‍👤

**Comment by Thorek93** [comment]
Much thank you mate, now it worke! But in console much spell fails

**Comment by Thorek93** [comment]
in World exe*

**Comment by schnek** [comment]
To do this, open a new bug report.
and do it and write what exactly doesn’t work..

**Comment by schnek** [comment]
> in World exe*

If this problem is solved then it can be closed.

**Comment by schnek** [comment]
fix (closed)
