### ISSUE TITLE
👾 [Bug Report] gcc - compilation error

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1202]
**Description**: 

start building core (gcc/linux)

**Steps to reproduce the problem**: 
1. cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_INSTALL_PREFIX=~/ascemu_server -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DASCEMU_VERSION=WotLK ../ascemu
2. make -j 4
```
ascemu/src/world/Server/Packets/SmsgResurrectRequest.h:25:65: error: use of deleted function ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::nullptr_t) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::nullptr_t = std::nullptr_t]’
   25 |         SmsgResurrectRequest() : SmsgResurrectRequest(0, 0, 0, 0)
```

"hack" as a solution  those problems, it works 100% (**maybe not right**)

`-SmsgResurrectRequest() : SmsgResurrectRequest(0, 0, 0, 0)`
`+SmsgResurrectRequest() : SmsgResurrectRequest(0, {0}, 0, 0)`

**Expansion version**: 

    Specify version - is required:
    - Patch 3.3.5 - WoTLK

**AscEmu hash/commit**: 

latest develop

**Operating system**: 

    Specify the operating system - is required:
    - Platform: Linux

**Comment by Appled** [comment]
The second parameter seems to be a string so you want to do `SmsgResurrectRequest(0, "", 0, 0)`
If you want, you can make PR 😉

**Comment by schnek** [comment]
fixed in latest dev
