### ISSUE TITLE
Visual Studio 2015 (Community) not working

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#133]
Using: CMAKE 3.3.0 and Visual Studio 2015 (Community)

MSVC error:
```
<hash_map> is deprecated and will be REMOVED...
<hash_set> is deprecated and will be REMOVED...
```

**Comment by sanctum32** [comment]
it works, just modify installation and choose custom installation type - then select c++ support (dont remember exactly how its called) and cmake should detect it easily.

**Comment by Zyres** [comment]
@sanctum32 thx
 EDIT: follow this http://blogs.msdn.com/b/vcblog/archive/2015/07/24/setup-changes-in-visual-studio-2015-affecting-c-developers.aspx

**Comment by Nupper** [comment]
I am using Cmake 3.4.0-rc1

**Comment by sanctum32** [comment]
add -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to global cmake CXX flags and it will fixed, alternativelly you just could replace hash maps with unordered map
