### ISSUE TITLE
AddTimer broken

### ISSUE THREAD

**Issue by Cronicman** [AscEmu/AscEmu#134]
I've scripted many dungeons but some with the AddTimer function are broken and will not work for some reason. Please look into this. I have it under OnCombatStart and registered as int32 for example below:
void OnCombatStart(Unit* pTarget)
	{
arthassay1 = AddTimer(30000);

then at the bottom i have it registered but it will not function.. :(

private:
int32 arthassay1;

**Comment by Zyres** [comment]
Hi Cronicman...
you created this issue few month ago ( AddTimer is not working #101 )
Maybe its time to join our forum and start a discussion/request for this function.

**Comment by Cronicman** [comment]
I posted in general discussion i found an old thread on the old arcemu forums with a person having the same issues.

**Comment by Zyres** [comment]
Thank you for your testscript. AddTimer is not broken and works.
For further information look:
http://www.board.ascemu.org/index.php/Thread/35-AddTimer-implement/?postID=84#post84
