### ISSUE TITLE
Crush in front of the ICC (Linux)

### ISSUE THREAD

**Issue by master312** [AscEmu/AscEmu#136]
Video.....

https://youtu.be/Dbrm9PCjzgE
Crushes every time, on the same place, with same logs.

Linux Mint 17.2   Kernel: 3.16.0-38-generic
7c86a60, 64bit build

Log files:
http://www.filedropper.com/crushlogs

**Comment by Zyres** [comment]
Tested on Win same as master312 said.
```const uint32 & GetUInt32Value(uint32 index) const
		{
		       >>ARCEMU_ASSERT(index < m_valuesCount);
			return m_uint32Values[index];
		}```

**Comment by Zyres** [comment]
@master312 can you test it again?

**Comment by master312** [comment]
@Zyres I will test it tonight and let you know if it works.

**Comment by master312** [comment]
@Zyres I just tested. It works just fine on linux. 
Ty for the fix :)

**Comment by Zyres** [comment]
@master312 No problem :-) thank you for your report.
