### ISSUE TITLE
AddPhaseSpell/AddSpell

### ISSUE THREAD

**Issue by Cronicman** [AscEmu/AscEmu#137]
Look into this, doesn't seem like it wants to work my creatures an IDK if its just how I coded it our what script is below. (WIP)
http://pastebin.com/gdnVQB6q

yes i have an enum with spell ids for the SPELL_SHADOW_BOLT stuff.. forgot to include that in the paste

**Comment by Zyres** [comment]
Closed. This is not an issue for our framework. If you need help for your script, ask for it on our forum.
