### ISSUE TITLE
[Crash] sholazar basin @ Frenzyheart hill

### ISSUE THREAD

**Issue by Cronicman** [AscEmu/AscEmu#138]
Go to frenzyheart hill and fly up on a flying mount and you will crash.

**Comment by Zyres** [comment]
@Cronicman Now it works for me. Can you retest it with the new version and give us some feedback?
-----------
This was implemented in https://github.com/AscEmu/AscEmu/commit/dcd7ea96a21d21efbc75948eb7d9bae32618282d by me.
Same problem like #136

**Comment by Cronicman** [comment]
fixed thx!
