### ISSUE TITLE
[Instance/Dungeon] Scourgelord Tyrannus double spawn

### ISSUE THREAD

**Issue by Cronicman** [AscEmu/AscEmu#139]
There's a double spawn of him theres the one on top of rimefang then one on the ground, the one on the ground is the one that needs removed.

**Comment by DankoDJ** [comment]
Please give us the entryIDs of these two spawns...
I'm quiet shure it is not a double spawn. The one on the ground is a result of a missing script:
http://www.wowhead.com/npc=36794/scourgelord-tyrannus#comments (intro)
http://www.wowhead.com/npc=36658/scourgelord-tyrannus#comments (fight)
https://www.youtube.com/watch?v=e757ZLIp5pg

**Comment by Cronicman** [comment]
both are 36658, you can target the one ontop of rimefang, rimefang is a vehicle.

**Comment by armm77** [comment]
OMG, a mage fucking killed Tyrannus.
