### ISSUE TITLE
Rogue/Talent Improved Eviscerate

### ISSUE THREAD

**Issue by Bianott** [AscEmu/AscEmu#142]
Talent: Improved Eviscerate (14162) http://wotlk.openwow.com/spell=14162
Effect on: Eviscerate (2098) http://wotlk.openwow.com/spell=2098

Improved Eviscerate should increase the damage of Eviscerate... currently it decrease it.
# 

Hab mir nen Schurken erstellt um mal die Talente durchzugehen.
Direkt beim ersten Talent "Verbessertes Ausweiden".

Ausweiden DMG 1 Talentpunkt: 680-700 variert  (1 combo punkt)

CharLv80 kein Gear max Spells:
Ausweiden DMG ohne Talent: 701-738 variert (1 combo punkt)
Ausweiden DMG 1 Talentpunkt: 680-700 variert  (1 combo punkt)
Ausweiden DMG 2 Talentpunket: 641-689 variert  (1 combo punkt)
Ausweiden DMG 3 Talentpunkt: 607-645 variert  (1 combo punkt)
Untested mit mehreren Combopunkten auf dem Feind

Das Talent soll ja den verursachten schaden Prozentual von Ausweiden erhöhen, senkt ihn aber im Test.

**Comment by Zyres** [comment]
Please report all bugs in english with more information (ids).

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/f1a69963b701f5624e80ada7171e4932648606fa
