### ISSUE TITLE
Rogue/Talent Malice

### ISSUE THREAD

**Issue by Bianott** [AscEmu/AscEmu#143]
Talent Malice (14138) http://wotlk.openwow.com/spell=14138
The talent should increase the critical hit chance with 1%.
My char had no gear equipped (0% critical hit chance) and after learning this talent it is still on (0% critical hit chance)

I tested malice with every rank. 100 hits but no one was critical.
# 

Talent Tücke funktioniert nicht.

Das Talent erhöht pro Punkt 1% deiner Krittischen Trefferchance.
Mein Char hat kein Gear an also 0%, nach dem ausbilden des Talentes ist es immernoch auf 0%

Pro Rang 100 Schläge ausgeübt kein einziger Krittischer treffer

**Comment by Zyres** [comment]
Please report all bugs in english with more information (ids).

**Comment by Appled** [comment]
Seems to be fixed at some point
