### ISSUE TITLE
Leaving a fight

### ISSUE THREAD

**Issue by Bianott** [AscEmu/AscEmu#144]
If I leave a fight (flee) there are 2 bugs:
- Spell is still active and ready to trigger a enemy:
  Bild: http://puu.sh/kGggR/3be80f93f4.jpg
- If I "left-click" a creature to check its hp, I attack it directly (should just work with "right-click")
# 

Wenn ich einen Kampf anfange und ihn NICHT zuende bringe da mir die HP/DMG fehlt und ich weglaufe treten 2 bugs auf:

Erstens: Ich "Verlasse" zwar laut anzeige den kampf, Spell bleibt aber Aktiv und will triggern
Bild: http://puu.sh/kGggR/3be80f93f4.jpg

Zweitens: Wenn ich die Kreatur dann mit Links anklicke um dessen HP herauszufinden, greife ich direkt wieder an (was ich eigentlich nur mit rechtsklick tun/können sollte)

**Comment by Zyres** [comment]
It works as it should, we can't reproduce your issue.
