### ISSUE TITLE
Dalaran Horde/Alliance Places not working

### ISSUE THREAD

**Issue by Bianott** [AscEmu/AscEmu#145]
I can enter as Horde (without gm rank) the Alliance hall and as alliance the Horde Area

Normally players should get ported out and stunned with a msg not allowed to go in these areas when they are not within the same faction.

Testes with GM ON, GM OFF, Player Account

**Comment by Zyres** [comment]
The Silver Covenant (Alliance):
NPC 29254 cast spell 54028 on horde players

The Sunreavers (Horde):
NPC 29255 cast spell 54029 on alliance players

**Comment by Bianott** [comment]
not working for me. compiled newest ascemu under linux

**Comment by Zyres** [comment]
? It was just some missing information for our development.
