### ISSUE TITLE
GM Mode inefficent

### ISSUE THREAD

**Issue by Bianott** [AscEmu/AscEmu#148]
NPC's can still attack me even when GM On and keep attacking me when my GM was OFF and i put it to ON

**Comment by Zyres** [comment]
We are not TC... .gm on sets the gm flag on you (for support...)
If you wanna be invisible use .invis or modify your faction.
So this is not and "issue" it is something we should discuss.

**Comment by DankoDJ** [comment]
As Zyres said, gm mode is not equal to unattackable. The GM mode is tagging you ingame for some support reasons. Blizz gms are attackable by creatures too with the gm tag...
We can discuss this on our forum. So it is not an issue (nothing is broken and it works as intended)
