### ISSUE TITLE
Skybreaker & Ogrim's Hammer Icecrown

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#151]
The Two Gunships in Icecrown do not move or do not seem to appear.

Additional information (Zyres):
The Two Gunships in Icecrown do not move or do not seem to appear
was ment to be for the Open world versions of the ships in Northrend Map not the Instance Versions

**Comment by Zyres** [comment]
See #66

**Comment by Nupper** [comment]
I have managed to get the ships to move and appear in there respective areas with npcs on them...but there not interactable due to transport npcs cannot use gossip
