### ISSUE TITLE
Transport Issue

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#152]
![wowscrnshot_101715_101125](https://cloud.githubusercontent.com/assets/6026902/10558154/c7045a2a-74bd-11e5-9fc6-3ca28e390ffc.jpg)
![wowscrnshot_101715_104435](https://cloud.githubusercontent.com/assets/6026902/10558156/c72af04a-74bd-11e5-8fa1-a55a2919ba30.jpg)
![wowscrnshot_101715_105635](https://cloud.githubusercontent.com/assets/6026902/10558155/c712a076-74bd-11e5-8dbc-0faa9d5f7132.jpg)
It appears only from the transports back to kalimdor and eastern Kingdoms...i theses three i have checked i will continue to update for other issues between areas with transports

**Comment by Nupper** [comment]
Appears to be for Classic Transport Paths As well.

**Comment by Zyres** [comment]
Just asking: What is the issue here? Can you please describe the issue like: "Npcs disappear" or "Quest NAME ID not finished on talking with npc NAME ENTRY"?

**Comment by Nupper** [comment]
The Transports do not correctly go to there proper destination instead appear futher away...or out of place and only disappear when they return to nothrend or kalimdor.

**Comment by Zyres** [comment]
http://www.board.ascemu.org/index.php/Thread/52-Transport-Handler/ See my latest comment.
