### ISSUE TITLE
Achievement Titles

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#155]
Achievements do not award titles even though you get a message saying you have earned it.

**Comment by Zyres** [comment]
Please add more information to your issues... give an example, do some research on wowhead, give us images, achievement name/id, title name/id...
We are loosing a lot development-time by doing all these research stuff.

**Comment by Nupper** [comment]
I am gathering information now...should take about a day or two.

**Comment by Nupper** [comment]
![wowscrnshot_102015_152648](https://cloud.githubusercontent.com/assets/6026902/10610281/0e7c2670-773f-11e5-9ea4-288c56af9d02.jpg)

Its pretty much for all titles except the ones listed
