### ISSUE TITLE
The School of Arcane Magic - Mastery

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#158]
Will not teleport you even when your i dalaran  you get "You need to be in Dalaran."
Item id 43824

**Comment by Cronicman** [comment]
I'm looking into this issue, curious when you did this did you have your maps extracted?

**Comment by Nupper** [comment]
indeed i have the maps and everything

**Comment by Zyres** [comment]
Related to #149

**Comment by Evairfairy** [comment]
The item now correctly recognises when the user is in Dalaran, however the teleport script is currently unimplemented.

**Comment by Evairfairy** [comment]
Resolved in 82041c9af34de7343ffa74d8892af6be79fcca2a
