### ISSUE TITLE
Spell Fan of Knives

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#16]
Hello! I guess Fan Of Knives got an target failture since when i try to use it the animation cames it use energy right but it dosnt hit the mob.
Hope you can fix this for us :)

mathias234

**Comment by DankoDJ** [comment]
Closed with: https://github.com/AscEmu/AscEmu/commit/d0b01bcc6300b35a647222dc924f45ba5ce9df26

See the new opened issue with #113
