### ISSUE TITLE
The Argent Vanguard and Scourgeholme Objects

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#162]
I completely forgot to add this but same locations no objects thats ment to be there are all in phase 1 not 2

**Comment by Zyres** [comment]
How did you check this, are the objects really in phase one?

**Comment by Nupper** [comment]
Phase 2
![wowscrnshot_102115_164209](https://cloud.githubusercontent.com/assets/6026902/10641853/f085ea32-7812-11e5-9c1c-843027e98e27.jpg)
Phase 1
![wowscrnshot_102115_164303](https://cloud.githubusercontent.com/assets/6026902/10641854/f0896252-7812-11e5-87fa-92ae0875a45d.jpg)
Phase 1 Only
![wowscrnshot_102115_164315](https://cloud.githubusercontent.com/assets/6026902/10641856/f0974dae-7812-11e5-89a5-bb5f5323de9f.jpg)
Phase 1 only
![wowscrnshot_102115_164333](https://cloud.githubusercontent.com/assets/6026902/10641855/f08d7bb2-7812-11e5-87dc-63bce92206df.jpg)

**Comment by aaron02** [comment]
I thought that these are in different phases because when doibg quests in nordend you will get to diferent phases because there are different ways to quest in this zone. I dont remember all but when i was playing on official wow is long time ago ^^

**Comment by Nupper** [comment]
yeah the dragon's spawn after the initial phase not all should be in a single phase.

**Comment by Zyres** [comment]
Don't know why everything was in phase 1... I cleaned this area (phase 1) here: https://github.com/AscEmu/AscEmu/commit/f511fd3e195636c672f2b0e97378d62e086da97d

**Comment by Nupper** [comment]
Phase 2 would be the first phase you enter in the area and some stuff would be spawned after a few quests like the dragons.
