### ISSUE TITLE
Sunreaver's Senctary Emblem vendors phased

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#163]
When you enter it switches you to phase 2
Outside of token Vendor Area
![wowscrnshot_102115_153305](https://cloud.githubusercontent.com/assets/6026902/10639627/34d2fa9a-7809-11e5-8b61-b01055a672f2.jpg)
When you go Inside
![wowscrnshot_102115_153315](https://cloud.githubusercontent.com/assets/6026902/10639636/3f5a459a-7809-11e5-98c1-01c0a9b9c276.jpg)

**Comment by Zyres** [comment]
The spawns are correct... it is related to #149

**Comment by Nupper** [comment]
The emblem vendors in that area phase out when you enter the building.

**Comment by Zyres** [comment]
@Nupper the spwn is correct... that players switch the phase is incorrect... this phase switch is based on another issue #149 
So no reason to push this issue ;-)
