### ISSUE TITLE
Argent Vanguard Creatures

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#167]
I apologize for the third commit about this
Initial phase (2) is missing a few things
- [x] Supply Officer Thalmers  (Bugged not missing) (Entry: 30438)
- [x] Penumbrius (Missing) (Entry: 30227)
- [x] Webbed Crusaders (Missing) (Entry: 30273)
- [x] Forgotten Depth Slayer (Missing) (Entry: 30333)
- [x] Crusader Lord Dalfors (Missing) (Entry: 30224)
- [x] Crusader Sunborn (Missing) (Entry: 30225)
- [x] Father Gustav (Missing) (Entry: 30226)
- [x] Highlord Tirion Fordring (Missing) (Entry: 28179)
- [x] The Ebon watcher (Missing) (Entry: 30377)
- [x] Iydallus (Missing) (Entry: 30378)
- [x] Mirador (Missing) (Entry: 30187)
- [x] Crusade Commandor Entari (Missing) (Entry: 30223)
- [x] Argent Skytalons And Glory (Missing) ( Skytalon Entry: 30500, Glory Entry: 30235)
- [x] Many Crusaders of Virtue (Missing) (Entry: 30189)
- [x] Forgotten Depth Acolyte (Missing) (Entry: 30205)

Areas: 
Valley of Echoes
Argent Vanguard
Scourgeholme

Once Again I apologize for the constant commits about theses i am using blizzard servers (No quests completed) as a reference for the initial phase

**Comment by Zyres** [comment]
Can you provide entry ids for these creatures?

**Comment by Nupper** [comment]
Theses are based on ascemu at this time i added a addon for live servers (As nothrend) not been changed at all to get even more indepth ids.

**Comment by Zyres** [comment]
Please recheck latest commit. If everything looks good, close this issue.

**Comment by Nupper** [comment]
- [ ] Forgotten Depth Acolyte (Missing Area: 4505) (Entry: 30205) - One wounders the breach and a few climb down from cliffsides
- [ ] Forgotten Depth High Priest (Missing Area: 4506) (Entry: 30203)
- [ ] Lichking Should be in another phase (Area: 4506) (Entry: 30443)
- [ ] Waypoints missing for  Forgotten Depths Underking (Area: 4506) (Entry: 30544)

**Comment by Zyres** [comment]
No problem ;-) blizzlike is one of our goal, so I'm happy someone is reporting this stuff.

**Comment by Zyres** [comment]
'''Forgotten Depth Acolyte (Missing Area: 4505) (Entry: 30205) - One wounders the breach and a few climb down from cliffsides''' can you upload a screen of the position of these npcs?

**Comment by Nupper** [comment]
![wowscrnshot_102215_195548](https://cloud.githubusercontent.com/assets/6026902/10675271/2e2f9c36-78f7-11e5-9a7e-f4b6bb87e80e.jpg)
![wowscrnshot_102215_195705](https://cloud.githubusercontent.com/assets/6026902/10675275/376cd4c6-78f7-11e5-9323-effc91f6b164.jpg)

**Comment by Zyres** [comment]
> and Couple of theses climb down the cliffs in Valley of Echos on both sides.

With the same entry? where do they climb down?

**Comment by Nupper** [comment]
Same Entries yes and they climb down both sides just at the entrance of the breach. as seen in the image

**Comment by Zyres** [comment]
> Same Entries yes and they climb down both sides just at the entrance of the breach. as seen in the image

I thought you like it blizzlike... I see only one npc climbing down... so I need another screen to create the other spawns (that it is "blizzlike")

Added some of these points in cf6a0b1d8e4cea2e567060b0a703f36dc18799e0

**Comment by Nupper** [comment]
There where too fast by the time i could screenshot it half where already on the ground...but there is normally 3 coming down from each side.
