### ISSUE TITLE
Hallows end (Event)

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#168]
Hallows end event is missing a lot of stuff

**Comment by Zyres** [comment]
> Hallows end event is missing a lot of stuff
Of course... can you provide some screens/ids/positions to add the missing spawns?

**Comment by Nupper** [comment]
sadly i cannot do much due to most of the hallows end stuff being in the new worlds and new IDS.

**Comment by Zyres** [comment]
Added a lot of spawns from different sources (1K go spawns and 18 creatures added). Can you recheck it and close this issue if it is enough?
