### ISSUE TITLE
Crystalsong Forest Missing spawns & Waypoints

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#172]
- [x] Azura Manashaper (Missing Area: 4555) (Entry: 31401) - Should be four per Platform
- [x] Azura Manashaper (Missing Area: 2817) (Entry: 31401) - Should be three on Platform with crystal next to the Azure Front
- [x] Azura scalebane (Missing Area: 2817) (Entry: 31402) - Same Platform with Crystal Circling the Manashapers
- [x] Crystal wyrm (Missing Area: 4555) (Entry: 31393) - Two should be flying around the tree in the Azure Front  (One is already there but no waypoints added) both should be flying opposit directions to each other.
- [x] Azura scalebane & Azura spellwaver Corpses (Missing Area: 4556) (Entry: 31402 & 31403) - there should be four to five dead and unclickable just outside the dalaran shield dome.
- [x] Grove Walker (Missing Area: 2817) (Entry: 31228) - some wounders the area around crystalsong forest and near Violet strand
- [x] Azura scalebane (Missing Area: 2817) (Entry: 31402) - some wounders the area around crystalsong forest and near Violet strand
- [x] Azura spellwaver (Missing Area: 2817) (Entry: 31403) - some wounders the area around crystalsong forest and near Violet strand
- [x] Azura Manabeast (Missing Area: 2817) (Entry: 31404) - some wounders the area around crystalsong forest and near Violet strand (Follows along side Spellweaver)
- [x] Sinewy Wolf (Missing Area: 2817) (Entry: 31233) - some wounders the area around crystalsong forest and near Violet strand
- [x] Teleport to Dalaran Crystal (Missing Area: 4556) (Entry: 191230) 
- [x] Teleport to Violet Stand Crystal (Bug Area: 4553) (Entry: 191230) - Dose not teleport you to Violet Strand

I am using blizzard Servers as reference
I will keep update if i find more missing to to make it more blizzlike

**Comment by Zyres** [comment]
'''Teleport to Violet Stand Crystal (Bug Area: 4553) (Entry: 191230) - Dose not teleport you to Violet Strand'''

**Comment by Zyres** [comment]
cf6a0b1d8e4cea2e567060b0a703f36dc18799e0

**Comment by Nupper** [comment]
i have no idea where to find mapcoords for missing spawns at this time but i think wowhead has them.

**Comment by Zyres** [comment]
> I will keep update if i find more missing to to make it more blizzlike

No I can not work on these type of issues. For the future, create one issue for one creature. It is very difficult to track this or recheck it. I can't invest days to collect different information from different sources... 

> Azura scalebane & Azura spellwaver Corpses (Missing Area: 4556) (Entry: 31402 & 31403) - there should be four to five dead and unclickable just outside the dalaran shield dome.

How should I add spawns for this? no screen... wowhead isn't showing this... maybe the creatures are normally alive. You can download the addon MapCoord and add the coords from blizzard for these spawns to the issue, otherwise no one will be able to add anything.

**Comment by Nupper** [comment]
i am very sorry i am still getting used to this all myself.

**Comment by Nupper** [comment]
![wowscrnshot_102515_231514](https://cloud.githubusercontent.com/assets/6026902/10718575/540ecc64-7b6e-11e5-91d7-8ea7d23e1ca3.jpg)

Coords: Azura spellwaver: 18/47, Azura scalebane: 17/47, Azura scalebane: 15/46, Azura scalebane: 16/43, Azura spellwaver: 17/44
