### ISSUE TITLE
Unhandled rewards in random dungeonfinder

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#174]
> And what should happen with the function "SendLfgPlayerReward"... do you recieve a reward or not if you recieve a reward we should delete this useless function. 

aaron02: Its not handled now becausw to get a reward you neef to kill all encounters needed that means scripted instances and check if group killed all bosses for reward and give them the stuff

**Comment by aaron02** [comment]
Fixed im testing it ;)

**Comment by aaron02** [comment]
can be closed fixed now
