### ISSUE TITLE
New Accounts Refresh

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#175]
Accounts Registered by Website dose not refresh and cannot be used.

Logon and/or Worldserver won't Refresh accounts.

I have to close Logon.exe and reload it for the accounts to be able to login to.

**Comment by Zyres** [comment]
You should check your logon.conf file
> <Rates AccountRefresh = "600"> (600 = 10 mins)

**Comment by Nupper** [comment]
ah ok i think my memory is slipping :D
