### ISSUE TITLE
Battlegrounds Text

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#176]
![wowscrnshot_102615_180938](https://cloud.githubusercontent.com/assets/6026902/10737933/cd5a1d78-7c0c-11e5-97e6-b75b16401f33.jpg)
![wowscrnshot_102615_180942](https://cloud.githubusercontent.com/assets/6026902/10737932/cd5404d8-7c0c-11e5-8fb1-c2a24a9e10fc.jpg)
![wowscrnshot_102615_180943](https://cloud.githubusercontent.com/assets/6026902/10737930/cd485f7a-7c0c-11e5-938e-236a7f81bccc.jpg)
![wowscrnshot_102615_180944](https://cloud.githubusercontent.com/assets/6026902/10737934/cd5e1e32-7c0c-11e5-88f5-406ccace3fdd.jpg)
![wowscrnshot_102615_180946](https://cloud.githubusercontent.com/assets/6026902/10737935/cd5fa90a-7c0c-11e5-9b6f-fe5ce5537c6c.jpg)
![wowscrnshot_102615_180948](https://cloud.githubusercontent.com/assets/6026902/10737931/cd4da552-7c0c-11e5-8214-373f1d9c35d7.jpg)

**Comment by Zyres** [comment]
This is working for me...
http://i.imgur.com/qKqBtD6.jpg

**Comment by armm77** [comment]
me too

**Comment by Zyres** [comment]
This issue appears after clientmodification.
