### ISSUE TITLE
Crash Item's Set

### ISSUE THREAD

**Issue by armm77** [AscEmu/AscEmu#184]
Items Set.
The server crash when the Player is placed items set.

**Comment by aaron02** [comment]
I thought it was just me puuh ^^

**Comment by armm77** [comment]
we are puuh ^^

**Comment by Nupper** [comment]
It may crash due to DBC for the time being i would remove itemset from said items.

**Comment by Zyres** [comment]
Okay I don't get it. The server crashy by adding an itemset? Or what is "PJ"?

**Comment by armm77** [comment]
Sorry @Zyres.
Player

**Comment by aaron02** [comment]
Crash when puting it pn player

**Comment by Zyres** [comment]
This was implemented by me in Player.cpp Line 4101 (https://github.com/AscEmu/AscEmu/commit/09cf3fea04b73834009ee8b2dfab4f72fa6cc3d2)
http://i.imgur.com/MvFpyCb.jpg
