### ISSUE TITLE
DBC, VMaps, Maps Extractor

### ISSUE THREAD

**Issue by Ahtuno** [AscEmu/AscEmu#185]
Rev: https://github.com/AscEmu/AscEmu/commit/06a8385f0673289764aa8125185fa8a0186b2834

---

Hello,
I'm missing the extractors for DBC, Maps, VMaps, could you guys maybe upload them extra?
On Wiki Page the Installation (DBC Extraction Page) are even not avaiable.

**Comment by Zyres** [comment]
Hi Ahtuno,
you have to set the CMake values for the extractors.
![unchecked](http://i.imgur.com/F2DgCrs.jpg)

![checked](http://i.imgur.com/gt3iti9.jpg)

**Comment by Ahtuno** [comment]
Im using Ubuntu 14.04

**Comment by Zyres** [comment]
I added the extractors to our downloads: http://www.board.ascemu.org/filebase/index.php/Filebase/
I will update the installation guid.

**Comment by Ahtuno** [comment]
thanks, are the extracted data from windows, useable with ubuntu ? or must it be extracted with ubuntu?

**Comment by Zyres** [comment]
hmmm.... as far as I can see it, the extractors can only be used on windows.
@Evairfairy Can you check this and update the installation page for ubuntu?

**Comment by Ahtuno** [comment]
thanks, I will extract them on my PC and upload then on my Google Drive to get them on my server.
Im just a DB Dev, no Idea about that related stuff :)

**Comment by Zyres** [comment]
Okay :-)
If you need further support you can use our forums.

**Comment by Ahtuno** [comment]
We'll stay in contact, would be awesome If i could get a list what's working and not. Like I said wanted fix DB related Stuff. Apparently I see this Issue Tracker has not much activity
(Adde mich in Skype "wowshards" Nickname: Athelstan wenn du nach einem DB Dev suchst)

**Comment by armm77** [comment]
the correct statement is:
cmake -Dtools=1 -DBUILD_TOOLS_MAP_EXTRACTOR=1 -DBUILD_TOOLS_VMAPS=1 -DBUILD_TOOLS_MMAPS_GENERATOR=1 -DCMAKE_INSTALL_PREFIX=~/server/ ../AscEmu

**Comment by Ahtuno** [comment]
yes, thank you.
