### ISSUE TITLE
Core/Quest destructible gameobjects

### ISSUE THREAD

**Issue by Bianott** [AscEmu/AscEmu#187]
May implement the Quest feature to relate also Objects to be collected/destroyed. Maybe also add LimitTime and SpecialFlags for better quest handling.

When that Happens alot Quests can be fixed.

Greetings

**Comment by Zyres** [comment]
@Bianott Give us a few example with questid, goid, short description what should happen to the go.

**Comment by Zyres** [comment]
the function for destructible gameobjects is already implemented. Check out feature/gameobjects (https://github.com/AscEmu/AscEmu/commit/c17ea717118e45b67ad497fa59771b9fff3b124c).
Unfortunately I'm still wayting for one questid (example) where this is needed (you said alot, I just need one quest).

**Comment by Zyres** [comment]
Closed, seems this is not an issue (just a suggestion?) Can't work on it without information!
