### ISSUE TITLE
Missing structures. (Portal Isle of Conquest)

### ISSUE THREAD

**Issue by armm77** [AscEmu/AscEmu#197]
for both the horde or alliance structures missing below the conquest portal.
AscEmu
![wowscrnshot_121415_115844](https://cloud.githubusercontent.com/assets/3104815/11791223/4180ffe2-a272-11e5-963e-48f41b5e914a.jpg)
![wowscrnshot_121415_115927](https://cloud.githubusercontent.com/assets/3104815/11791224/4184e210-a272-11e5-9d3d-cae01822630c.jpg)
Trinity Core 3.3.5
![wowscrnshot_121415_112526](https://cloud.githubusercontent.com/assets/3104815/11791280/85f7848e-a272-11e5-8ef3-1816a823a5ad.jpg)
![wowscrnshot_121415_112424](https://cloud.githubusercontent.com/assets/3104815/11791294/9484a6d0-a272-11e5-8a4a-018bdf1ee4d4.jpg)

**Comment by Nupper** [comment]
Structure seems to be set to phase 2 not 1

**Comment by armm77** [comment]
Nupper're right, and I'll fix it.

**Comment by Zyres** [comment]
Closed with 413a348cb845c9dcb9ba8466e2f5f343419e602e
