### ISSUE TITLE
 Events Disappear.

### ISSUE THREAD

**Issue by armm77** [AscEmu/AscEmu#199]
After a random time are not displayed, the events still active. 
And when this happens when you restart the X event, the server crashes.
![wowscrnshot_121815_105711](https://cloud.githubusercontent.com/assets/3104815/11900300/40fc07e4-a577-11e5-97b5-76e04158380d.jpg)

**Comment by Nupper** [comment]
Reload client for a second time they seem to show after that,

**Comment by Zyres** [comment]
I noticed the server crash related thing. It mostly appears by closing the world-server instead of safety shutdown (Ctrl + C) or doing a normal shutdown.

**Comment by Zyres** [comment]
After a few tests during the last few weeks I can't reproduce this issue anymore. If you still have this issue with the latest version, comment on this issue.
