### ISSUE TITLE
Random Battlegrounds

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#2]
Not working, I didn't know if you fixed it already.
- [X] RBG handling
- [X] RBG join
- [X] RBG honor + config

**Comment by Zyres** [comment]
Unfortunately this is not fixed...
master312 submitted this patch: https://github.com/AscEmu/AscEmu/commit/bc920e9ba6f2a0759893a394d02927ad86b30cd7
Currently we check his second patch for rbg honor: http://www.board.ascemu.org/index.php/Thread/48-RBG-Stats-saving-question/?postID=129#post129

**Comment by Zyres** [comment]
Closed in: https://github.com/AscEmu/AscEmu/commit/7dbc7bf236999daa78fee7a17d975c94b7d334d1
