### ISSUE TITLE
Standing up for a talk

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#20]
If a char is sitting on a chair and is speaking (in say channel f.ex.) the char regularly (about every 5th sentence) stands up and sits down. This looks quite strange especially in RP gameplay. I and other players thinks that this behaviour is not blizzlike.
Magnifikator

**Comment by Zyres** [comment]
Not reproduceable in 5697e35f52bef857f7650365d01309cedbcb78f7
