### ISSUE TITLE
Vehicle controler faction ignored

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#205]
If you are casting a vehicle spell, it looks like it is ignored by creatures/destructible gos.

Example:
Vehicle (creature) 28094. Cast Hurl Boulder (spell id: 50896). (No effect for enemies/gos)

The vehicle should change its faction to the controler faction.

**Comment by Cronicman** [comment]
Add this in Vehicle.cpp under Vehicle::AddPassengerToSeat, I did this and could attack anything and creatures attack the vehicle instead of you.

	Creature* c = static_cast<Creature*>(owner);
	c->SetFaction(passenger->GetFaction());
