### ISSUE TITLE
Totem madness in Hellfire Peninsula / Zangarmarsh

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#208]
I'm not familiar with this area but it looks wrong...
#Honor Hold
![honor_hold](http://i.imgur.com/2Y1WbCd.jpg)

#Temple of Telhamat
![temple_telhamat](http://i.imgur.com/RqVi4Nz.jpg)

#Falcon Watch
![falcon_watch](http://i.imgur.com/rlquONt.jpg)

=Zangarmarsh=
#Cenarion Refuge
![renarion_refuge](http://i.imgur.com/u33bc06.jpg)

**Comment by armm77** [comment]
Where did these totem. lol, we have to clean the database.

**Comment by Zyres** [comment]
It is not related to the event system. @armm77 feel free to do it ;)

**Comment by armm77** [comment]
the database is very dirty. ok I'll take to fix this. @Zyres  :+1:

**Comment by Zyres** [comment]
@armm77 these spawns are correct, there is just a problem with visibility.
