### ISSUE TITLE
Skybreaker & Ogrim's Hammer NPCs and objects

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#213]
Just to let that due to the new handler we got npcs and objects in the sky from the old spawns...
I will be fixing this in time.

**Comment by Zyres** [comment]
I added a new label for transport related issues.
Please do not change any transport spawns until @Evairfairy checked/fixed the new transport handler.

So these issues will be fixed after the new transport system is implemented.

**Comment by Nupper** [comment]
i will postpone the changes then... :)
