### ISSUE TITLE
Flying npcs

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#216]
All flying npcs should fall to the ground when dead.

**Comment by Cronicman** [comment]
add & try this under Creature::Die
	if (GetAIInterface()->IsFlying())
	{
		GetAIInterface()->StopFlying();
	}

it should force the creature to stop flying and drop to the ground.

**Comment by Nupper** [comment]
but would the flying return when it respawns.

**Comment by Cronicman** [comment]
yes, when it respawns it loads the data from Creature::Load && Creature::PushToWorld

**Comment by Nupper** [comment]
I hope they add it :+1:   it would be very handy and realistic

**Comment by Zyres** [comment]
@Nupper did you test the suggestion? Does it work?

**Comment by Nupper** [comment]
i do not know there the codes are handled but sure i can test.

**Comment by Nupper** [comment]
1>C:\Users\Nupper\Desktop\Ascemu\source\src\world\Creature.cpp(2612): error C2059: syntax error : 'if'

2>C:\Users\Nupper\Desktop\Ascemu\source\src\world\Creature.cpp(2613): error C2143: syntax error : missing ';' before '{'

3>C:\Users\Nupper\Desktop\Ascemu\source\src\world\Creature.cpp(2613): error C2447: '{' : missing function header (old-style formal list?)

**Comment by Cronicman** [comment]
I'm updating and fixing right now guys I got the npc to land but it won't work if hes dead, so its almost fixed & updated.

**Comment by Cronicman** [comment]
Fixed it works blizzlike & will be posting on the forum with a phone video.
