### ISSUE TITLE
Character Customize Naming

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#217]
Renaming using this function will appear as the name has changed...but in-game the chat will show the old name.

**Comment by Cronicman** [comment]
Did you restart your wow client and clear the cache?

**Comment by Nupper** [comment]
indeed i did.

**Comment by Zyres** [comment]
is it changed in characters table?

**Comment by Nupper** [comment]
Indeed it shows new name in tables.

**Comment by Cronicman** [comment]
Cannot re-produce this, did .char rename and the ingame chat shows the new name? Cleared my cache also.

**Comment by Nupper** [comment]
its using the Character select function....during Character re-customization or forced renamed.

**Comment by Zyres** [comment]
Currently it seems to be "blizzlike".
Player A sees Player B before he renamed his character.
If Player B finished the rename he/she appears for Player A with the old name (until Player A do a relogg).
Two people should retest it on blizz server, if it works there without relogg, feel free to comment to this issue.
