### ISSUE TITLE
Creature regenerating health

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#218]
This is related to quests like "Rescue the Survivors" or the Priest Initiation Quests.
The core realizes that they are not in combat and they regenerate, giving them full health again and making it impossible to heal them as they are already healed.

Make a new flag to stop them healing

 http://www.wowhead.com/quest=9283/rescue-the-survivors#videos:id=33206

**Comment by Cronicman** [comment]
Working on this will update the forum post when completed
