### ISSUE TITLE
Heroic Encounters

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#219]
i Will be handling Heroic Proto Difficulty

**Comment by Zyres** [comment]
This is no issue... just to keep in mind "all changes to creature_proto_difficulty" has to rever to this issue.

**Comment by DankoDJ** [comment]
https://github.com/AscEmu/AscEmu/commit/9a7dd7bcf4a236c31fb5cf63c8593eabaa3b4541 Ahn'Kahet applied
