### ISSUE TITLE
Quest 12641: Death Comes From On High

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#22]
"Death Comes From On High" is one of quests that must be done in order to use Death Knights.
I should use the "Eye of Acherus" but it is not possible to attack or see the targets (related to #11)

https://www.youtube.com/watch?v=VAQwxyWrXrc

**Comment by Appled** [comment]
Same as https://github.com/AscEmu/AscEmu/issues/404 which is more generic issue so closing this one
