### ISSUE TITLE
The Nexus Alliance and Horde

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#220]
Both Alliance Forces  and Horde  Forces appear.
Should be 
Horde Player = Alliance Forces
Alliance players  = Horde Forces

**Comment by Cronicman** [comment]
I have this issue solved will be posting on forums later in day

**Comment by Cronicman** [comment]
fixed on my fork.

**Comment by Zyres** [comment]
@Cronicman applied. I changed some style related things, will push it later to master.
