### ISSUE TITLE
Flying npcs Fall though buildings on dead

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#224]
I testing flying npcs while it works amazing....they fall though the building they fly over in which makes little sense as obtaining loot from said npcs would be impossible.

I know this feature was just fixed and some other problems is expected but i am prone to report any issue i see :D

**Comment by Zyres** [comment]
This is the result of fixing this issue #216 (just a link for later development)

**Comment by Cronicman** [comment]
Shouldn't the maps manager tell if the object is a WMO and calculate the position Z with that?

**Comment by RAlexis** [comment]
I haven't tested if it works, but could someone please try to change in Creature.cpp line 2528 to:
`GetAIInterface()->MoveFalling(GetPositionX(), GetPositionY(), GetMapMgr()->GetADTLandHeight(GetPositionX(), GetPositionY()), GetPositionZ() + 2);`

Thanks.
