### ISSUE TITLE
Duel Spec Bad string text

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#225]
I cannot seem to locate them.

**Comment by Zyres** [comment]
It is not an extra trainer... most class trainers with a higher level than 40 can train the dual specialization.

**Comment by Nupper** [comment]
I checked with stormwinds warrior trainer...there is no function for it.

**Comment by Zyres** [comment]
![it works](http://i.imgur.com/0R4vmuh.jpg)
Not reproduceable....

**Comment by Nupper** [comment]
Fixed but 
![wowscrnshot_010716_170152](https://cloud.githubusercontent.com/assets/6026902/12176693/9066b31c-b560-11e5-9524-1a98ddfb1679.jpg)

**Comment by armm77** [comment]
SQL apply updates, I correct this text.

**Comment by armm77** [comment]
https://github.com/armm77/AscEmu/commit/2b2070a525c0c2040ecfd243ee9cbba3d9641bb5

**Comment by Zyres** [comment]
It was already fixed in 2b2070a525c0c2040ecfd243ee9cbba3d9641bb5
See: https://github.com/AscEmu/AscEmu/blob/master/sql/world_updates/2015-12-13_01_misc_updates.sql#L69
