### ISSUE TITLE
Creature spawns with .npc spawn / SpawnCreature

### ISSUE THREAD

**Issue by Cronicman** [AscEmu/AscEmu#226]
Spawning a creature either with the GM command or by MoonScript/EasyFunctions should spawn with the weapons currently they don't. Techinally this isn't a bug but a feature/enhancement. Trinity has had this since they started and Arc had it working alog time ago but is currently broke due to an unknown rev.

If somebody could test: http://www.board.ascemu.org/index.php/Thread/113-Possible-Fix-Creature-spawning-with-weapons-using-npc-spawn-or-SpawnCreature/

**Comment by Zyres** [comment]
![slot_works](http://i.imgur.com/nqURImj.jpg)
