### ISSUE TITLE
Auctionshouse GUID 1 in mailbox

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#23]
When an auction has ended the items comes by internal mail.

The sender_guid is always 1.

Because of that the player is informed in the minimap icon that he got a new mail from [Charname of GUID 1]. Normally that's the admin char name because he is the first one creating a char.

Workaround would be to change the charname of guid 1 to something useful like [server] or [auctionhouse].
Magnifikator
------------------------------------------------

Confirmed. It'll show the name of the character with GUID 1 ( assuming the first character it comes across) on the minimap icon, however when you check the mail it lists the auction house. It also shows that the buyer received mail from the first character.

Another problem noticed is that my mail expires in 34,000 days. (Modded my level to 80 and it now shows the correct time period.)

Sending mail from player to player works correctly.

After some research, I noted that the id for the SW Auction house is 1 in the dbc and the sender guid is 1, Removed my character with the guid of 1 and it now just says I have Unread mail. I decided to move to a different auction house, which still uses 1 as the sender guid.

Further Edit: As I said earlier, the sender_guid is always 1. I've now figured out that it always saves the auction house as 1, which is the stormwind auction house. I've pretty much narrowed it down to dbc->id always pointing to a 1.
ghost

**Comment by Zyres** [comment]
Seems to be already fixed :)
Tested with db6d874df282ac2e99fb3d682f101b2e67fcbab8
