### ISSUE TITLE
Client stops working

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#232]
Client stops working around Commander Lynore Windstryke Wintergarde keep.
World of warcraft Retail has stopping
![untitled](https://cloud.githubusercontent.com/assets/6026902/12268686/b783f2c8-b945-11e5-87e8-39dc2d04a953.png)

**Comment by Zyres** [comment]
Can you try this sql?
INSERT INTO spell_disable (`spellid`, `replacement_spellid`) VALUES (46598, 0);
