### ISSUE TITLE
Strand of the Ancients

### ISSUE THREAD

**Issue by armm77** [AscEmu/AscEmu#235]
The server crashes when the character enters the battlefield. Possibly by the features of the objects or units.

**Comment by Zyres** [comment]
Okay I got it, setting a invalid faction for gos Line 524 and the following line in StrandOfTheAncient.cpp

**Comment by Nupper** [comment]
I can confirm that the server crashes

**Comment by Zyres** [comment]
Does this appear for AV too?

**Comment by armm77** [comment]
Only SOTA
