### ISSUE TITLE
Vendors should show only class items (Some)

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#236]
![wowscrnshot_011616_003240](https://cloud.githubusercontent.com/assets/6026902/12368943/b0fdebca-bbe8-11e5-8651-3f73cd3cc621.jpg)
Some Wrath tier vendors show only the items required for that class.

**Comment by aaron02** [comment]
That is blizzlike i trust

**Comment by Zyres** [comment]
What is blizzlike:
- To show all Items?
- To show only class items?

**Comment by aaron02** [comment]
Only your class items but with gm char you see all items

**Comment by Zyres** [comment]
So it is already like suggested. A normal player account didn't see other items.
I will change that, so you see all items if you set gm on.

**Comment by Nupper** [comment]
they are only supposed to show useable items as well so for warlocks will only show cloth,cloak and so on.

**Comment by Zyres** [comment]
As Nupper suggest it should show all useable items, not only the class items

**Comment by Nupper** [comment]
Blizzlike Function (Wrath Standard)
* Class Only Items (Items that can only be used by said class)
* Useable items (Items that can be used by that class ((Back, Trinkets, Rings and neck do not apply unless class restricted))
