### ISSUE TITLE
localized deDE

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#242]
/* SQL Error (2006): MySQL server has gone away */

**Comment by Zyres** [comment]
... how to reproduce this?

**Comment by Lectro** [comment]
change MAX_ALLOWED_PACKET in mysql/mariadb settings

**Comment by Zyres** [comment]
No please do not change your mysql services/programms.
First ->What have you done? Localized sqls which ones?

If he gets this error, we should change the sql (otherwise we have to tell everyone who is going to use this sql to change his/her settings...)

**Comment by Lectro** [comment]
mysqldump database_name --max-allowed-packet=1 > filename.sql ;)
