### ISSUE TITLE
Negative EXP for Discoverey

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#251]
![wowscrnshot_012116_191432](https://cloud.githubusercontent.com/assets/6026902/12491545/a06100ec-c073-11e5-9d00-638b10cce42b.jpg)

**Comment by Zyres** [comment]
? What was the issue and how did you solved it?

**Comment by Nupper** [comment]
No  fix but its ment to be a lvl 90 custom zone

**Comment by Zyres** [comment]
Don't forget to add the information to AreaTable.dbc for the structure you can check out world/DBC/DBCStructures.hpp line 131 - 143

**Comment by Nupper** [comment]
Info is in areatable.dbc
