### ISSUE TITLE
Blood Presence bug

### ISSUE THREAD

**Issue by ghost** [AscEmu/AscEmu#256]
Healed by 4% of damage dealt. <- this part does not work.
Spell ID: 48266

need to add either into hackfixes.cpp or a different method. The proc spell id is (Non-Existing) ???
Apply Aura: Proc Trigger Spell 
Proc Spell ID: 1206
Value: 4

**Comment by Lectro** [comment]
I'm sure its bug caused by heal effect actually because healing effect is scripted exclusivelly in this effect script and just instead of adding more hacks, fix this this effect instead

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/f1a69963b701f5624e80ada7171e4932648606fa
