### ISSUE TITLE
Priest spell Penance bug

### ISSUE THREAD

**Issue by ghost** [AscEmu/AscEmu#257]
This spell dopes not function right at all, go to stormwind around npcs and use penance it is suppose to shoot 3 bolts at your current target, it only shoots 1 and the other 2 shoot at other random npcs around it.

**Comment by Zyres** [comment]
hmmm.... which one is it?
![penance](http://i.imgur.com/QBnqNcc.jpg)

This is a nice addon showing you the spell id inside the tooltip ingame http://www.curse.com/addons/wow/spellid/436536

**Comment by Cronicman** [comment]
spell id: 47540 (rank 1)
spell id: 53005 (rank 2)
spell id: 53006 (rank 3)
spell id: 53007(rank 4)

**Comment by Zyres** [comment]
Check out issue #381
