### ISSUE TITLE
Death knight runes cooldowns

### ISSUE THREAD

**Issue by Lectro** [AscEmu/AscEmu#259]
ascemu core: 0780e22ae73ad7995e9565ec61e8bfefe012e907
world_db: clean world database with no modifications, updated to core commit
OS: antergos OS x64
compiler: clang
build type: debug
additionaly used tools: valgrind

Description: Death knight runes does not get any cooldown after spell cast, instead of that all runes are resetted.

How to reproduce: cast any dk spell which requires runes

**Comment by Zyres** [comment]
See: https://github.com/AscEmu/AscEmu/commit/06658513afdc3878c1b3bd6a9e7fdb224efc0e8b
