### ISSUE TITLE
Shaman Totem Buffs

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#26]
Totems with effects apply buff, but the buff does not increase stats (e.g: strength of earth totem rank 1: applies buff that increases strength and agility by 10 : stats do not change in character panel.)

http://old.wowhead.com/spell=8075
salamanda

**Comment by Appled** [comment]
Works in https://github.com/AscEmu/AscEmu/commit/6609712a8cb7e5283effdd46064c499c6812d694
