### ISSUE TITLE
NPC cannot use other types

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#269]
NPCs should be able to rage and Enegy as well as mana.

**Comment by Zyres** [comment]
## Opening new issues
Be patient with us and give us details.
 1. How to reproduce the issue
 2. How should it work
 3. Images will help us a lot

**Comment by Zyres** [comment]
@Nupper Why do you close this issue?

**Comment by Nupper** [comment]
NPCs will only ever show mana bars. They do not visibly generate energy or rage. Instead, their abilities simply have cooldowns, and the AI for the game chooses when to use each ability.
