### ISSUE TITLE
Transporter stuck in ground, wrong waypoints/period creation

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#276]
Investigate wp generation for transports. It seems there is a flaw inside wp-generation/period which has an impact on player teleportation between maps.
To see an extreme example this issue will produce, board on transporter 181688 (Baradin <-> Daggercap Bay) and watch what happen. (Player gets teleported the first time can't walk/do anything, waiting a few seconds and gets teleported to the "correct" position).
See this:
![image-stuck](https://cloud.githubusercontent.com/assets/6026902/10558154/c7045a2a-74bd-11e5-9fc6-3ca28e390ffc.jpg)

**Comment by Nupper** [comment]
I do not think its the DBCs as they have been unchanged since got knows when.

**Comment by Zyres** [comment]
@Nupper no one said anything related to DBC changes. This issue is not "new" it was already in arc there.

**Comment by Lectro** [comment]
i did couple tests, it seems player is teleported 3x times during transaction (from point A to B, B to A, A to B) at transaction between maps. To reproduce this, just add debug message in transport handler teleportTransport event for given cordinates.

**Comment by Zyres** [comment]
Check out issue #516
