### ISSUE TITLE
Devotion Aura Bug

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#279]
shows all ranks instead of just the latest and overrides the other Abilitys for a paladin
![wowscrnshot_030516_085735](https://cloud.githubusercontent.com/assets/6026902/13546794/9e352f82-e2b0-11e5-952a-ad5a62f12671.jpg)

**Comment by aaron02** [comment]
Did you learned the spells with gm command ?

**Comment by Nupper** [comment]
Yes.

**Comment by aaron02** [comment]
Only happens with m commabd with trainer it works fine

**Comment by Lectro** [comment]
it seems this command wasnt updated for cataclysm, on cata there's no ranks for class spells (except for professions and similar spells). Spells like paladin aura scales together with player level.

**Comment by Lectro** [comment]
I see that you're running cataclysm client, Spells like paladin auras in cataclysm scales with level so it mostly its gm command issue - comman simply wasnt updated for cataclysm values

**Comment by Zyres** [comment]
Duplicate issue see #117
