### ISSUE TITLE
ProfessionTrainer: Skill Learning

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#28]
A small but strange bug appearing on profession trainers:
Learning any skill, given that you already learned the first rank, always causes the menu to show all learned ranks (apprentice, journeyman etc.) and selecting apprentice as default choice. Those skills are red, as they are already learned, and they are not filtered even if you select to show only available skills.
Phil92

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/9e15b06a80c9041a7dc6cfd3f70c8614f3d35ea5
