### ISSUE TITLE
Branch Develop: worldserver Assertion failed

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#288]
Closing the worldserver wit Ctrl + C hits two Assertions:
![assertions](http://i.imgur.com/ayWs5dd.jpg)

Implemented in: https://github.com/AscEmu/AscEmu/commit/b48fecb23ce9b2d43cc00c9e4bbd8852708274d8

Call Stack:
![callstack](http://i.imgur.com/Ft0kdHl.jpg)

**Comment by Lectro** [comment]
actually its not related to this commit because this happens randomly, i got this assert on random data loads... yesterday was trying to fix transports, didnt had time to run valgrind but its somewhere related in database queries

**Comment by Lectro** [comment]
and i found fix for this, actually void SubGroup::Disband() is dealing this... iterators are just dublicated and increased twice...

**Comment by Zyres** [comment]
I would not open an issue if it is not a problem.
It was implemented in https://github.com/AscEmu/AscEmu/commit/b48fecb23ce9b2d43cc00c9e4bbd8852708274d8
It was not "randomly" and appears every time on shutdown the worldserver.
Subgroup::Disband was not related to this issue (check out the CallStack the assertion happened in the loop "for (GroupMap::iterator itr = m_groups.begin()"...
