### ISSUE TITLE
Explosive Sheep

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#29]
Explosive Sheep creates a companion that doesn't explode, doesn't attack but simply follows you.
It even follows you when the duration is over with, same applies to other engineered constructs, like Target Dummy.
Not sure wether this is a bug or it is simply a not implemented feature.

**Comment by Cronicman** [comment]
fixed in f39a9340fd1c9b7f0ff5ebad5d91fa1cf9f479ac
