### ISSUE TITLE
The mounts show only display to the respective factions

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#292]
Horde MammothID: 31852, SpawnID: 128960
Alliance MammothID: 31851, SpawnID: 128959
Alliance GryphonID: 32335, SpawnID: 129859
Horde wind riderID: 32336, SpawnID: 129860
Alliance brown BearID: 32206, SpawnID: 129346
Horde brown BearID: 32207, SpawnID: 129347
![wowscrnshot_031116_121746](https://cloud.githubusercontent.com/assets/6026902/13702151/6fc471c0-e784-11e5-8ca1-ca84b3e4a257.jpg)

**Comment by Lectro** [comment]
i'm not sure about this but are entries same for horde and alliance? also isnt it specifically phased for each faction?

my first guesing is: core might track male_display2 from creature_names for horde and male_display1 for alliance - its just guesing.

**Comment by Nupper** [comment]
each one has a different ID...but they only display the ones for the respective factions...Alliance will only show for alliance and horde will only show for horde.

**Comment by Lectro** [comment]
@Nupper, do you have any posibility to get sniff data for these spawns? i'm pretty sure that it can be fixed by spell area data

**Comment by Nupper** [comment]
Sadly they are not as up to date for me. i can check on Live servers for ID though

**Comment by Nupper** [comment]
ID's are correct.

**Comment by Lectro** [comment]
alright, i cannot promise but after transports fix i'm going to check this... movement system is little mixed up

**Comment by Cronicman** [comment]
I'm looking in this also, will come back with a fix. I'm finally back after a month in the hospital.

**Comment by Zyres** [comment]
The following issue has an impact tho this: #149
