### ISSUE TITLE
Northrend Client Crashes

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#298]
I set the mode do debug mode and all i get was HandletimeSyncRasp: Not Handled.
HandleCalandergetNumPending: Not handled

Around Dalaran and Argent Vangard And Venture Bay and most of northrend

**Comment by Zyres** [comment]
> HandletimeSyncRasp: Not Handled.
> HandleCalandergetNumPending: Not handled
All debug information are already known.

Your title "Northrend Client Crashes". So does the client crash or do you just see these debug information?

**Comment by Nupper** [comment]
Client crashes.

**Comment by Zyres** [comment]
Can't reproduce this issue, no client crash on the latest version.
We had a server crash near Argent Vangard but this was already fixed.

If someone else can verify this issue, feel free to comment.
