### ISSUE TITLE
GCC Version

### ISSUE THREAD

**Issue by camscottFS** [AscEmu/AscEmu#299]
Can you please tell us what version of gcc is required to compile AscEmu? We are trying to compile this on CentOS 7 and it ships with gcc 4.8 which cmake says is an unsupported version. Will a newer build of Cmake fix this or is there any hope for updating the core so that it works under CentOS 7 + gcc 4.8?

**Comment by Zyres** [comment]
It compiles fine on gcc 4.8 .
Check out the travis command file here: https://github.com/AscEmu/AscEmu/blob/master/.travis.yml (maybe this will help).

**Comment by camscottFS** [comment]
Are there any DBC extractors available here for 2.4.3 and if not where can I get the right one. Tried some and they don't work.

**Comment by Zyres** [comment]
Looks like off-topic talk. Please use the forum for requests. This repo is for 3.3.5 and not 2.4.3...
