### ISSUE TITLE
Dungeon finder

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#3]
The Dungeon finder didn't work.
The needed opcodes are not available.

**Comment by Zyres** [comment]
Opcodes found but not handled.

**Comment by aaron02** [comment]
i have some scripts for it but not working at all :D you find quque and get matched and get request to accept. i need to fix it completly but i dont know when

**Comment by Zyres** [comment]
Hi aaron02
thanks for this information but it is useless... feel free to post your scripts in our forum... maybe someone (with more time) can work on it.
