### ISSUE TITLE
[Mage Spell] Invisibility

### ISSUE THREAD

**Issue by ghost** [AscEmu/AscEmu#303]
I have 3/3 in Prismatic Cloak talent which makes invisibility instant cast however when I cast it it just says "immune". Going to check without the talent to see if it says the same thing.

**Comment by Cronicman** [comment]
Seems that if you are using the any rank of the talent Prismatic Cloak it causes Invisibility to not work at all

**Comment by Cronicman** [comment]
Talent ids:
31574, 31575, 54354
spell id for invis:
66

**Comment by Zyres** [comment]
@Appled hmmmm this seems to be a problem with the spell itselfe

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/f1a69963b701f5624e80ada7171e4932648606fa
