### ISSUE TITLE
[Mage Talent] Impact (All Ranks)

### ISSUE THREAD

**Issue by ghost** [AscEmu/AscEmu#305]
The talent is not working as intended, it procs but it seems that that if you cast any spell rather than fire blast it stuns the target for 2 secs. Sometimes you get stunned by it as well this is not blizzlike.

**Comment by Zyres** [comment]
? Please install an addon and post the entry.... thanks.

**Comment by Cronicman** [comment]
Rank 1: 11103
rank 2: 12357
rank 3: 12358

**Comment by Zyres** [comment]
@Appled still a valid issue?

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/f1a69963b701f5624e80ada7171e4932648606fa
