### ISSUE TITLE
[Mage Talent]Firestarter

### ISSUE THREAD

**Issue by Cronicman** [AscEmu/AscEmu#306]
This talent is bugged, it procs on ALL spells when it is only suppose to proc on Dragon's Breath and Blast Wave.

**Comment by Cronicman** [comment]
Fixed: http://www.board.ascemu.org/index.php/Thread/151-TALENT-FIX-Mage-Firestarter/

**Comment by Zyres** [comment]
Closed in 092ee6796f56c8f9829296c041753a97f829ff93
