### ISSUE TITLE
[Mage] Summon Water Elemental crash in worldserver

### ISSUE THREAD

**Issue by Cronicman** [AscEmu/AscEmu#308]
casting this whenever you have the glyph of eternal water active, crashes the server.

**Comment by Zyres** [comment]
spellid?

**Comment by Cronicman** [comment]
won't let me upload the dump here ill post on forums

**Comment by Zyres** [comment]
If I try to cast Summon Water Elemental the server crashes without Glyph of Eternal Water.

**Comment by Zyres** [comment]
Closed: The crash is solved.
