### ISSUE TITLE
[Mage] Summon Water Elemental 

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#309]
casting this whenever you have the glyph of eternal water active didn't work.

Summon Water Elemental: spell id 31687 (?)
Glyph of Eternal Water: item id: 50045 (http://wowwiki.wikia.com/wiki/Glyph_of_Eternal_Water)?

If Glyph of Eternal Water is active, spellid 70908 will be casted (instead of 70907) but no element appears.

**Comment by Evairfairy** [comment]
Resolved in 3b80c5b2dfb506c0266b3d1f3be64e4c51d1abfc
