### ISSUE TITLE
Arena Team Create Command not functional

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#310]
.arena createteam <Name>

Result:
Invalid Syntax.

**Comment by Zyres** [comment]
.arena createteam is not an AscEmu command.
Check out the wiki: http://www.ascemu.org/wiki/index.php?title=Command_Documentation

**Comment by Nupper** [comment]
its in the command list in-game.

**Comment by Zyres** [comment]
the command works for me.

**Comment by Zyres** [comment]
Update wiki: http://www.ascemu.org/wiki/index.php?title=Command_Documentation#.arena
