### ISSUE TITLE
Isle of Conquest gates disappear

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#311]
The gates for alliance base and possible horde seem to disappear after the bg starts.

**Comment by Cronicman** [comment]
Same thing appears in WSG with the portcullis in both horde & alliance starting zones.

**Comment by Nupper** [comment]
there ment to do that to allow players to play the match in WSG

**Comment by armm77** [comment]
if we increase the amount of MapCellNumber = "4", you can see the well are away. (world.conf)

**Comment by Zyres** [comment]
@armm77 This issue is not related to the cell config. The gates disappear a few minutes after opening.
Gates entrys:
 195698, 195699, 195700, 195494, 195495, 195496
Door entrya:
 195703, 195491
