### ISSUE TITLE
[Warrior Talent] Improved Hamstring

### ISSUE THREAD

**Issue by ghost** [AscEmu/AscEmu#314]
This talent does not proc at all but the ids below are in the proc table.

Improved Hamstring talent ids:
12289(rank 1), 12668(rank 2), 23695(rank 3)

**Comment by Zyres** [comment]
@Appled still valid with the latest extensive changes to spells?

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/f1a69963b701f5624e80ada7171e4932648606fa
