### ISSUE TITLE
Quest - Inoculation

### ISSUE THREAD

**Issue by S7urp33** [AscEmu/AscEmu#315]
Quest: http://db.hellground.net/?quest=9303
Spell: http://db.hellground.net/?spell=29528
Video of whats supposed to happen: https://www.youtube.com/watch?v=g3Qz_liqHR0

What actually happens:
1. When you use Inoculating Crystal: http://db.hellground.net/?item=22962 it automatically makes the target attack you when they are supposed to be passive and not. The creature will however face you after the spell has channeled and finished.
2.  The units are supposed to have an inoculation debuff on them that using the crystal will remove but I don't know what the debuff spell is on them currently I figured this is a DB issue.

**Comment by AMDIvailo** [comment]
Is this problem in the 3.3.5 or 2.4.3 branch?

**Comment by armm77** [comment]
2.4.3 & 3.3.5

**Comment by S7urp33** [comment]
Could we do an aiinterface call to stop movement and stop attack from spell aura with the Id for the spell like how the hunter training rods work.  I think there is probably a lot of item based quests that don't work properly like the shrine quest as a blood elf where you have to read it but get no quest update.

**Comment by S7urp33** [comment]
I've been leveling each race to level ten and finishing there zones and logging any dB or core bugs but I reverify I'd I think it's bugged by checking YouTube or wowhead

**Comment by Cronicman** [comment]
Temporary fix with creature AI. Needs to be done by spell when I get time. I tested my fix on the TBC core and the spell works how it should in the video at this time.
https://github.com/AscEmu/AscEmu_TBC/commit/70f6076065000b9c408ddbab22f487df241299b6
