### ISSUE TITLE
Quest - Taming the beast (all - TBC)

### ISSUE THREAD

**Issue by S7urp33** [AscEmu/AscEmu#316]
On Ascemu_TBC version the Taming the beast quest for any race / combination automatically completes which I'm guessing is some sort of work around that was in place before instead of fixing the issue.

When using the taming rod it doesn't tame the creature and set it to a 15 minute timer as it should. The creature only attacks you then continues and never is tamed by you which means you can't complete the quest.

I saw some code in the WoTLK version under the QI spells that I'm guessing could be ported and tested, the current implementation for the rods and quest is under SpellAuras.cpp if you search "tamingspellid" it will pull it up quickly.

**Comment by Cronicman** [comment]
Can you post this issue on the issue tracker on the ascemu tbc page also since it effects TBC & wotlk.

**Comment by Cronicman** [comment]
since this is a TBC issue and not a wotlk i'm closing this.
