### ISSUE TITLE
NPCs aren't stopping when GOSSIP HELLO is called.

### ISSUE THREAD

**Issue by S7urp33** [AscEmu/AscEmu#317]
If you interact with a quest giver they will continue walking even though you have the quest menu open with them. I see this is something Arcemu had under their To-Do as well to fix and said its an issue with waypoints. I look at the code and found a reference to where it should make the NPC stop under: HandleGossipHelloOpcode in the NPCHandler it shows (180000) which I'm assuming is in milliseconds but it never actually comes across to the NPC to make them stay put.

**Comment by Zyres** [comment]
This repository is for wotlk and NPCs are stopping when you talk to them.
Report AscEmu_TBC issues to the issue tracker on the AscEmu_TBC repository.
