### ISSUE TITLE
[DK] Blood Boil

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#333]
Spell ID: 49941
http://wotlk.openwow.com/spell=49941
No dmg

Reported by RyffLe

**Comment by aaron02** [comment]
http://www.wowhead.com/spell=50842/blood-boil
Says the dmg  is 375% of attack power

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/f1a69963b701f5624e80ada7171e4932648606fa
