### ISSUE TITLE
[General][Crash] World crashes on creature attack

### ISSUE THREAD

**Issue by Eatos** [AscEmu/AscEmu#339]
Using newest revision starting world and attacking creature will result in crash due to MonsterSay[] array being uninitalized thus comparing with NULL will not work.

Creature.cpp 
void Creature::HandleMonsterSayEvent(MONSTER_SAY_EVENTS Event)
{
NpcMonsterSay* ms = creature_properties->MonsterSay[Event];
		if (ms == nullptr)
			return;

-----------------------------------------------------------

Solution initialize MonsterSay array in 
sMySQLStore.GetCreatureProperties

**Comment by Zyres** [comment]
Which platform?

Do you received MySQL errors while importing the world db?

**Comment by Eatos** [comment]
Tested on Windows 10
There were not any errors while importing world DB although i had to use older version as current one was empty.

in void MySQLDataStore::LoadCreaturePropertiesTable()

just add
for (int i = 0; i < NUM_MONSTER_SAY_EVENTS; i++) 
{
    creatureProperties.MonsterSay[i] = nullptr;
}

and it will fix the issue regarding of allocating and initializing memory for MonsterSay array
