### ISSUE TITLE
GO loot - not lootable after respawn

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#353]

**Comment by Sdyessdev** [comment]
@Zyres Examples of this? Does this apply to quest objects as well or only things like chests?

**Comment by Zyres** [comment]
@Sdyessdev Ryffle reported this. According to the conversation, all lootable gameobjects missing the loot after it respawns.
The loot is defined in loot_gameobjects.

**Comment by Sdyessdev** [comment]
In case I don't end up finishing this, an example is the "Hidden Strongbox" object id 165972
