### ISSUE TITLE
Stat and spell bug in WotLK 3.3.5a 

### ISSUE THREAD

**Issue by RyffLe** [AscEmu/AscEmu#364]
some Spell's dosn't work, all maths calc for dmg and heal is rong. Stat maths aren't Blizz like.

**Comment by Zyres** [comment]
@RyffLe please be more specific and provide as many information as possible (means 1 issue for one spell)
Just to remember this text:
![readme](http://i63.tinypic.com/2q3rfhy.png)
This is a nice addon showing you the spell id inside the tooltip ingame http://www.board.ascemu.org/filebase/index.php/File/16-idTip-3-3-5/
