### ISSUE TITLE
SPELL REPORT: Penance

### ISSUE THREAD

**Issue by RyffLe** [AscEmu/AscEmu#381]
Buggy Spell Report:

Spell Name: Penance
Spell ID: 47540
Screenshots: 
[http://www.fotos-hochladen.net/uploads/wowscrnshot120yinwagt40l.jpg](http://www.fotos-hochladen.net/uploads/wowscrnshot120yinwagt40l.jpg)

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/66b78257de799533ee571a80fe3c09c0fa91d2a0
