### ISSUE TITLE
Instance Encounter Map

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#391]
BuildEncounterMap gives a error msg. it canf find creature_names.

void MoonInstanceScript::BuildEncounterMap()
{
    if (mInstance->pInstance == NULL)
        return;

    QueryResult* KillResult = WorldDatabase.Query("SELECT id, entry FROM creature_spawns WHERE map = %u AND entry IN (SELECT entry FROM creature_names WHERE encounter = 1)", mInstance->GetMapId());
    if (KillResult != NULL)
    {

**Comment by Inifield** [comment]
creature_name was merged into creature_proprietes need to be adjusted
