### ISSUE TITLE
Server crash moonscript ai

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#398]
Assertation error by fighting a boss when he is casting a spell
I updated the core todsy to the latest version tested on my scripts for pit of saron. Evrything was working just fine bevore i updated. World.exe crashes and windows asks to debug or close the application
**Steps to reproduce the problem**:

1. Go to a instance
2. Fight a boss
3. Wait until he casts a spell
4. Crash

**win32**:

**Comment by Zyres** [comment]
Reproduced:
- CombatStatus for scripts (InstanceScripts) hit _SCL_SECURE_OU_OF_RANGE debug error in xtree.

![image](http://i.imgur.com/DCOWs97.png)

**Comment by Zyres** [comment]
Further Information:
Use .debug spawnwar 10 2959 in a flat area. If you try to run to another position the server crash until you are outside of the attack range.
![run_away](http://i.imgur.com/b4keyu2.png)


If you use the command in invisibility (.invis) mode the creatures fight each other and the server crash after a few minutes after the fight.
![afterfight](http://i.imgur.com/d7eerXM.png)

**Comment by aaron02** [comment]
Hmm possible. But i was not leaving the fight or run away it happend after few seconds all the time he began zo cast his first spell. It must be  target issue

**Comment by Zyres** [comment]
@aaron02 I just added what I tested. I never said that it is not a target issue, It is not related to casting creature exclusive.

**Comment by aaron02** [comment]
Sorry misunderstood your post :*

**Comment by Zyres** [comment]
Update:
If you target a creature and attack it, everything is fine.

If you get attacked by a creature and you do not attack it, the worldserver will crash here:
![crash in for](http://i.imgur.com/S9mmsYy.png)

**Comment by Zyres** [comment]
Related commit: a614e45310299d7aa42293d31db553ce1a3e707e

**Comment by Zyres** [comment]
@aaron02 try it with the latest version.

**Comment by aaron02** [comment]
I try it later

**Comment by aaron02** [comment]
working now
