### ISSUE TITLE
Transport npc bug

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#408]
Creatures on transporters dont get updated. By changing the creatures flags or letting then send a chatmessage dont gets updated. I think the create update block dont gets send for them. Also they cant attack. When the transport npc is a vehicle you cant use it. I testet this on a transport in icecrown citadel spawned with the creatures on it. The transporter was stopped ( on its spawn position ). After a relog the flags are getting updated but still no ai ir usage of vehicles

**Comment by Zyres** [comment]
Check out issue #516
