### ISSUE TITLE
Prowling worg

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#409]
**Description**:

**Current behaviour**: new copy every 5 seconds
http://www.wowhead.com/npc=24206/prowling-worg 
entryID 24206 
displayID 22003
![wowscrnshot_021417_002349](https://cloud.githubusercontent.com/assets/1216225/22904072/0c0afe1e-f24c-11e6-8a50-74b010af0a9c.jpg)

**Steps to reproduce the problem**:

1. ![wowscrnshot_021017_040455](https://cloud.githubusercontent.com/assets/1216225/22903238/152d628c-f249-11e6-85a7-6401806e6342.jpg)
2. ![wowscrnshot_021317_224620](https://cloud.githubusercontent.com/assets/1216225/22903515/ef1cb4ca-f249-11e6-87f9-2f702e419610.jpg)
3. ![wowscrnshot_021017_040524](https://cloud.githubusercontent.com/assets/1216225/22903432/a03f9476-f249-11e6-9cea-b5af3675ddf9.jpg)

**Branch(es)**: 4.3.4 / 3.3.5

**AscEmu hash/commit**:  https://github.com/AscEmu/AscEmu/commit/c05b4a77275097538a80dce737914959d8e94dea

**Operating system**:  Windows 10

**Comment by Zyres** [comment]
A trap is casting a spell which spawns this creature....
Further investigation needed.

**Comment by schnek** [comment]
@Zyres I can make a video with the NPC with a similar problem.

**Comment by Zyres** [comment]
@schnek no video needed.... just add the entryid and name for other creatures

**Comment by schnek** [comment]
@Zyres Prowling worg entryID 24206 displayID 22003
