### ISSUE TITLE
Crash after equipping any item and logging out!

### ISSUE THREAD

**Issue by brotalnia** [AscEmu/AscEmu#412]
**Description**: If i equip an item to any character and attempt to log out the server crashes. After the new item has been equipped attempting to unequip it also crashes the server. This happens every time.

Video: https://www.youtube.com/watch?v=oJV3Vi3-kx8

**Current behaviour**: Server closes upon log out after equipping items, and also when unequipping items.

**Expected behaviour**: The server should not crash.

**Steps to reproduce the problem**:

1. Create a new character.
2. Add an item to the character and equip it.
3. Log out.

**Branch(es)**: 3.3.5

**AscEmu hash/commit**:  c730e34f

**Operating system**:  Windows 7 x64 Ultimate

**Lua scripts**:  No.

**Other Customizations**: Instant 80.

[dump-world.exe-c730e34f-2017-2-19-1-16-24-4872.zip](https://github.com/AscEmu/AscEmu/files/785405/dump-world.exe-c730e34f-2017-2-19-1-16-24-4872.zip)

**Comment by Zyres** [comment]
You should update your AscEmu version.
Please check out world and character db updates.

**Comment by brotalnia** [comment]
I switched to another version and this bug is not present anymore.
