### ISSUE TITLE
Having lots of issues compiling

### ISSUE THREAD

**Issue by mwaning** [AscEmu/AscEmu#423]
Hello, I keep getting errors like this. Is there any known fix?

/home/ascemu/installer/ascemu/code/src/shared/Util.cpp: In function ‘std::string Util::GetCurrentDateTimeString()’:
/home/ascemu/installer/ascemu/code/src/shared/Util.cpp:90:15: error: ‘put_time’ is not a member of ‘std’
         ss << std::put_time(std::localtime(&in_time_t), "%Y-%m-%d %X");
               ^
/home/ascemu/installer/ascemu/code/src/shared/Util.cpp: In function ‘std::string Util::GetCurrentTimeString()’:
/home/ascemu/installer/ascemu/code/src/shared/Util.cpp:107:15: error: ‘put_time’ is not a member of ‘std’
         ss << std::put_time(std::localtime(&in_time_t), "%X");
               ^
/home/ascemu/installer/ascemu/code/src/shared/Util.cpp: In function ‘std::string Util::GetDateTimeStringFromTimeStamp(uint32_t)’:
/home/ascemu/installer/ascemu/code/src/shared/Util.cpp:123:15: error: ‘put_time’ is not a member of ‘std’
         ss << std::put_time(std::localtime(&raw_time), "%Y-%m-%d %X");
               ^

**Comment by Zyres** [comment]
Which compiler?

**Comment by Zyres** [comment]
Closed until further information is provided:
- compiler
- platform
- version hash

**Comment by mwaning** [comment]
Compiler is CMake
Platform is Debian 8
Version hash is 3b30c5e8b25d0706eba05b279d9e3c027a2b7f7e (I think?)

**Comment by Zyres** [comment]
CMake is the precompiler.
AscEmu requires at least Clang 3.8 / GCC 6.2 / MSVC 2015
Update your compiler to the minimum required version.

**Comment by mwaning** [comment]
Hmm, I tried updating all of those, but I'm afraid the same issue is still there.
Sorry, I'm not super smart in this field. I just wanted to try compiling Ascemu. I've tried this once before a few months ago and this issue didn't appear. Compiling Arcemu is also going fine without issues. Not sure what could be wrong...

**Comment by Zyres** [comment]
Please retry with the latest version (updated few minutes ago)

**Comment by mwaning** [comment]
Yes, that worked! Thanks for the update.

**Comment by mwaning** [comment]
Oh, and it tried compile the server directory to /root/. Was easy to fix, but thought you might wanna know.
