### ISSUE TITLE
Combat bug

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#427]
**Description**:
Combat status not changed after a fight.

**Current behaviour**: Tell us what happens
Combat status not changed after a fight.

**Expected behaviour**: Tell us what should happen instead
Combat status should change after a fight.

**Steps to reproduce the problem**:

1. Kill a mob

**Branch(es)**: master 

**AscEmu hash/commit**:  
5a9fbc7784fa78915b251d504d5f813f492fd39c

**Operating system**:  
Win 10

**Introduced in**:
13fc49b84aafb407efaf00285dca4d2670db6d59
5d7f980c49ce19bb8064c65c52d52d23a65c67d2
c520af242a01941cb58bd5cc05e86fe58605504f
6ab17d20cc85364ca8315c92617a87dc3c219d0c
2c034f9c2fc4abb544914bc48c1a69cf9cd7af46
d7a4f8c1db56ec25230369c6051ebbc3cfcd694c

Images uploaded by schnek:
![first](https://cdn.discordapp.com/attachments/227808274488098819/294134321445470208/unknown.png)
![second](https://cdn.discordapp.com/attachments/227808274488098819/294134606163214336/unknown.png)
![third](https://cdn.discordapp.com/attachments/227808274488098819/294134780310585344/unknown.png)

**Comment by Tulba** [comment]
omg @Zyres please fix it... it is so annoying
