### ISSUE TITLE
Multiversion Essentials - Status

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#428]
# A short introduction
We decided to support tbc, wotlk and cataclysm in one branch (we have not enough developers to handle multiple branches/repositories). This PR provides essential functions to move on with multiversion support.
All version specific code goes to an seperated dir and will be released under the MIT license.

### Classic (Build 5875 account flags: 0)
- [x] Authentification
- [x] Worldsocket
- [x] Char Enum
- [x] Char create
- [x] Char delete
- [ ] Log into world

### The Burning Crusade (Build 8606 account flags: 8)
- [x] Authentification
- [x] Worldsocket
- [x] Char Enum
- [x] Char create
- [x] Char delete
- [x] Log into world

### Cataclysm (Build 15595 account flags: 32)
- [x] Authentification
- [x] Worldsocket
- [x] Char Enum
- [x] Char create
- [x] Char delete
- [x] Log into world
- [x] Guild commit https://github.com/AscEmu/AscEmu/commit/a15eb6550849aa38a5c709edae19088702db67ec , https://github.com/AscEmu/AscEmu/commit/44756d2d8aab257f1818b75d7586f53181e9947f , https://github.com/AscEmu/AscEmu/commit/f9698f3e5eaf4874684da9d811e082217d60b08a, https://github.com/AscEmu/AscEmu/commit/01b31bf8a6e4943aae8709292d46a46312f0a854

## Questions popping up during the development
* How to handle the different dbc structure?
* How to handle different database content?

**Comment by schnek** [comment]
0 - Classic WoW
8 - The Burning Crusade
16 - Wrath of the Lich King (only)
24 - Wrath of the Lich King & The Burning Crusade
32 - Cataclysm

**Comment by Zyres** [comment]
Test

**Comment by Tulba** [comment]
> ...we have not enough developers...

most of the time YOU work on it, so you should do yourself a favor and concentrate on one version

**Comment by Zyres** [comment]
tbc login since 49c9873ad97a4dba672be9e610ca216073ab24d4

**Comment by Zyres** [comment]
Check out #545
