### ISSUE TITLE
Player position... no update for other players

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#431]
**Description**: Player position... no update for other players.

**Current behaviour**: Walk around, other Players see you at the same position as you entered the world.

**Expected behaviour**: If you are Walking around, others should see you walking around.

**Steps to reproduce the problem**:

1.  Enter world with a char
2. Enter world with another char
3. Walk around.

**Branch(es)**: master, build Cata

**AscEmu hash/commit**:  45a81d58487d8b13ae42a074ef91692bb5c719a7

**Operating system**:  Win10

**Lua scripts**:  No

**Other Customizations**: No

**Comment by aaron02** [comment]
This was working at ascemu cata branch i had
