### ISSUE TITLE
Configfiles and missing values

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#432]
This issue was created to track the current/upcoming changes to our configuration files.

## Missing values in world.conf
- [x] **<WorldDatabase ConnectionCount = "number"**. You can define how many connections should be opened to the database. 3 by default.
- [x] **<CharacterDatabase ConnectionCount = "number"**. You can define how many connections should be opened to the database. 5 by default.
- [x] **<Log Players = "true or false"**. Log Player actions.
- [x] **<Server CacheVersion = "12340"**. Client build. - Removed
- [x] **<Server BanTable = "sql table name"**. You can save all character bans in a table. The tablestructure should be something like varchar(20), varchar(25), int(30), int(30), text. (gm_name, banned_char_name, Unixtime, banned_til_Unixtime, ban reason.
- [x] **<WorldSocket SendBuffSize = "number"**. Max send buffer size. - Removed
- [x] **<WorldSocket RecvBufSize = "number"**. Max recv buffer sizer. - Removed

## Unused values in world.conf
- [x] **<Startup Preloading**. Loading all spawns on all maps... - Removed
- [x] **<Startup BackgroundLootLoading**. Load Loot data in Background? - Removed
- [x] **<Periods HonorUpdate**. Period of honor update. - Removed

## Unused values in optional.conf
- [x] **<Optional AdditionalFun= "enable or disable"**. No fun stuff available. - Removed
- [x] **<Optional Unstuck = "enable or disable"**. Enable unstuck command? - Removed
- [x] **<Optional UnstuckCooldown = "time in seconds"**. Defining unstuck command cooldown? - Removed
- [x] **<Optional UnstuckToBind = "true or false"**. Defining unstuck command port location? - Removed

## General config mess
In world.conf and realms.conf we have in both files a section named <LogonServer> - this makes no sense.
Most configs in optional.conf are not optional.
Do we really need 3 config files for the world server?

## General
- [x] configure data dir for dbc, maps, vmaps, mmaps.
- [x] Merge all config into one.

## Linked commits:
da1ed4869b11813cf51fa5dcdc3ee95fc1270961, 298cdd3864c1d87812cd580c42bcd06e54023a0a, 8abcbeeaba225066b3d0938e7422cb355a4f04a0, 2bc31c07e8653de1bf95d93e22e2f0f7a75029ac, 59a8df7f2c7c27aae4dfa973d114bb25337b0222, 4a47843128b99a33719aafb24fa045559fa0ae6b, 8edfe5dcaa06d5787fad4999c740f56784f81c16, eaffb5aac1f056fdbcab12f5b036ea6ebb2ddffc, 5bf9223625a021b8603c7e0735cc8b2378f77503, 5bf9223625a021b8603c7e0735cc8b2378f77503, 82db685fa49fc615ff2cd2186b0f4b8f40682c1f, cd4b36d669b943c11ea17da893528f5810995d70, 4f3910fdc515404858b03a060c675f8357bd52bd

## You miss some configs?
Post it as detailed as possible below.

**Comment by Zyres** [comment]
So lets get creative

**Comment by schnek** [comment]
@Zyres Make configuration files via cmake =)
