### ISSUE TITLE
CID 52550 (#1 of 1): Resource leak in object (CTOR_DTOR_LEAK)

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#434]
![cid](http://i.imgur.com/Dny3YfO.png)

**Comment by Eatos** [comment]
Hey @Zyres  didnt know where to ask you this but regarding using converty scan can you tell me the difference between it and cpp check. As at work we are using cpp check and does pritty good job :) Thanks

**Comment by Zyres** [comment]
@Eatos coverity scan does a good job reporting possible and actual issues and is widely used around other open source projects. You can simply use it with TravisCI and implement it within your workflow (assign defects to other team members and track them inside the coverity dashboard). We choose it also to compare us with other projects.
Unfortunately your comment is unrelated to this issue and AscEmu, I'm not a product advisor for external programs and you should check out the specifications of these two programs on your own.

**Comment by Eatos** [comment]
@Zyres Didn't expect answer straight away :D Thanks for elaboration :)
