### ISSUE TITLE
Modules are not loaded during worldserver start up on Ubuntu Server 16.04.

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#449]
**Description**:
Modules aren't loaded on worldserver start up. Error message "ERROR: Cannot find version functions." refers to [here](https://github.com/AscEmu/AscEmu/blob/master/src/world/Server/Script/ScriptMgr.cpp#L124). After failing to load each module last error message is "[ERROR] LoadScripts No external scripts found! Server will continue to function with limited functionality". Like the error message states there are no instance scripts, gossip scripts, quest scripts nor spell scripts loaded. The modules are definitely from same compile as the worldserver and they are in their respective folder in core folder (core/modules/XX.so).

![The error](http://i.imgur.com/ZiYRbGM.png)

**Current behaviour**: 
Modules aren't loaded

**Expected behaviour**:
Modules should load?

**Steps to reproduce the problem**:

1. Install Ubuntu Server LTS and clone source
2. Compile
3. Start worldserver

**Branch(es)**: 4.3.4 / 3.3.5 (Specify the branch(es) affected by this issue)
Master

**AscEmu hash/commit**: 
e44b59578e15f39aff2b18d37f1901cd44d74afa

**Operating system**: 
Ubuntu Server 16.04 LTS 

**Lua scripts**:  Are you using any Lua scripts? if yes, list them
None

**Other Customizations**: Are you using any customizations? If yes please specify them here.
None

**Comment by Zyres** [comment]
According to the history these checks changed here: https://github.com/AscEmu/AscEmu/commit/a759be6bf522d111f5a84d331f6bf6b06fe19fc9?diff=unified

![checks](http://i.imgur.com/KPGnWLm.png)

**Comment by Appled** [comment]
@Zyres I tried to comment "set_serverstate_call" and "if (!vcall || !rcall || !scall)" lines, and I added the old null checking but it didn't change

**Comment by Zyres** [comment]
Do you have a folder modules in your server dir and does it include files like libSpellHandlers.so?

**Comment by Zyres** [comment]
Closed in 5871f4d41e260da1281b710298059033543e5bf7
