### ISSUE TITLE
Some gameobjects/chest loot is broken

### ISSUE THREAD

**Issue by dhmann** [AscEmu/AscEmu#453]
**Description**: Certain gameobjects give way too much loot. Battered Chest (ID=2843) for example gives the Player around 4 pages of green Items and no gold.

**Current behaviour**: See above.

**Expected behaviour**: Most chests give the player some amount of gold, after investigating in the core it seems like gold sometimes does not get properly handled. Do the values for gold need to be hardcoded or is it better to store them in the DB? Need to investigate. 

Players should loot around 1-3 green items instead of 4 pages. I certainly do not remember the retail dropchances in my head but we need to take a look if this is:

-A Problem with the Dropchances in the DB
-Or a problem within the Core on how Loot is handled for gameobjects.

**Steps to reproduce the problem**:

1. .go sp 2843
2. loot
3. Check with a database like old.wowhead.com

**Branch(es)**: 4.3.4 / 3.3.5 (Specify the branch(es) affected by this issue)
-Tested on 3.3.5

**AscEmu hash/commit**:  f82b7202cee213517860dd20034fb92fda285761

**Operating system**:  Windows 7 64bit

**Lua scripts**:  Are you using any Lua scripts? if yes, list them
-No

**Other Customizations**: Are you using any customizations? If yes please specify them here.
-No

**Comment by Zyres** [comment]
Added to #777 - we should rewrite the loot system anyway.
