### ISSUE TITLE
Players are facing the wrong orientation when first created

### ISSUE THREAD

**Issue by dhmann** [AscEmu/AscEmu#454]
**Description**: Players are facing the wrong orientation when first created. Orientation gets set to 0 even when it's not supposed to be.

**Current behaviour**: Players are facing the wrong orientation when first created. Orientation gets set to 0 even when it's not supposed to be.

**Expected behaviour**: Players should face the right direction when created. Most likely saved in the DB.

**Steps to reproduce the problem**:

1. Create character
2. Enter World

For example when you make a new Undead Character, your Character should face the first QuestNPC on entering the world, however he faces in the nearly opposite direction.

**Branch(es)**: 4.3.4 / 3.3.5 (Specify the branch(es) affected by this issue)
-Tested on 3.3.5

**AscEmu hash/commit**:  This bug exist since ArcEmu times.

**Operating system**:  Windows 7 64 bit.

**Lua scripts**:  Are you using any Lua scripts? if yes, list them
-No

**Other Customizations**: Are you using any customizations? If yes please specify them here.
-No

**Comment by dhmann** [comment]
Orientation also gets set to 0 when walking through the Dark Portal. Maybe this is a general problem with orientation.

Further Questions:
-Is the orientation wrongly stored as 0 for these "teleports"?
-Or is it a problem with some kind of Move function again?

**Comment by Zyres** [comment]
We have no orientation information for new created players (table playercreateinfo)
Portals should cast a spell on you (maybe the orientation is currently unhandled).

**Comment by dhmann** [comment]
Is the Black Portal handled like a normal portal though?

**Comment by Zyres** [comment]
For teleports: Table areatriggers miss some orientation data.
