### ISSUE TITLE
Chat System is Broken

### ISSUE THREAD

**Issue by dhmann** [AscEmu/AscEmu#456]
**Description**: Several things do not work correctly in the Chat.

**Current behaviour**: 
-Players are unable to change channels by typing "/1 " for example.
-Players get automatically added into the Guild Recruitment Channel, which also gets set to 1

**Expected behaviour**: 
-"/CHANNELNAME " should change the channel
-You should not be added to channels which you do not specify

**Steps to reproduce the problem**:

1. Use "/1 " in Chat
![wowscrnshot_050517_162342](https://cloud.githubusercontent.com/assets/18444786/25749669/9fbb222c-31af-11e7-9b49-6af0f995f7e7.jpg)

**Branch(es)**: 4.3.4 / 3.3.5 (Specify the branch(es) affected by this issue)
-Tested on 3.3.5
**AscEmu hash/commit**:  f82b7202cee213517860dd20034fb92fda285761

**Operating system**:  Windows 7 64bit

**Lua scripts**:  Are you using any Lua scripts? if yes, list them
No

**Other Customizations**: Are you using any customizations? If yes please specify them here.
No

**Comment by Zyres** [comment]
Maybe I'm wrong but is it not /NUMBER like /2 to write a message to a channel?

**Comment by dhmann** [comment]
Yep. /1 for General didn't Work. Didn't test every channel though only /1

**Comment by aaron02** [comment]
Was working for me.
Edit maybe i should test it on the current branch instead if the cluster repo ^^

**Comment by dhmann** [comment]
Well now we know that the bug was introduced some time between forking the cluster branch and now ^^

**Comment by aaron02** [comment]
Maybe i am wrong but was it mot 1/ to switch channels. Its not core based?

**Comment by Zyres** [comment]
It works on 7dccf555c81662f8d137357b9ffc117a793b95b4
