### ISSUE TITLE
Unknown opcodes on bg master hello opcode

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#467]
**Description**: Unknown opcodes on bg master hello opcode
[CLIENT]: received CMSG_BATTLEFIELD_LIST (0x3814) of 4 bytes.
[CLIENT]: received CMSG_BATTLEFIELD_LIST (0x3814) of 4 bytes.
[CLIENT]: received UNKNOWN_OPCODE (0x2423) of 1 bytes.
[CLIENT]: received UNKNOWN_OPCODE (0x5B3) of 0 bytes.
[CLIENT]: received UNKNOWN_OPCODE (0x780C) of 0 bytes.
[CLIENT]: received UNKNOWN_OPCODE (0x24A1) of 0 bytes.
[SERVER]: sent SMSG_BATTLEFIELD_LIST (0x71B5) of 33 bytes.
[SERVER]: sent SMSG_BATTLEFIELD_LIST (0x71B5) of 33 bytes.
[Session] Received unhandled packet with opcode UNKNOWN_OPCODE (0x2423)
[Session] Received unhandled packet with opcode UNKNOWN_OPCODE (0x05B3)
[Session] Received unhandled packet with opcode UNKNOWN_OPCODE (0x780C)
[Session] Received unhandled packet with opcode UNKNOWN_OPCODE (0x24A1)

**Solution**: Investigate unknown packages and handle them.

**Comment by armm77** [comment]
hello @Zyres , this was what I got from other emulators.
 CMSG_REQUEST_RATED_BG_INFO = 0x2423,                    // new
 CMSG_REQUEST_RATED_BG_STATS = 0x05B3,                   // new
 CMSG_REQUEST_PVP_REWARDS = 0x780C,                      // new
 CMSG_REQUEST_PVP_OPTIONS_ENABLED = 0x24A1,       // new
