### ISSUE TITLE
Stop spell cast - unknown packet/missing handler

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#475]
**Description**:
Stop spell cast - unknown packet/missing handler
[CLIENT]: received UNKNOWN_OPCODE (0x115) of 5 bytes.
[Session] Received unhandled packet with opcode UNKNOWN_OPCODE (0x0115)

**Comment by armm77** [comment]
CMSG_CANCEL_CAST                                  = 0x0115
