### ISSUE TITLE
Inspect player - unknown packets on pvp inspect

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#477]
**Description**:
Inspect player - unknown packets on pvp inspect

[CLIENT]: received UNKNOWN_OPCODE (0x791E) of 2 bytes.
[CLIENT]: received UNKNOWN_OPCODE (0x2704) of 8 bytes.
[CLIENT]: received UNKNOWN_OPCODE (0x3010) of 2 bytes.
[Session] Received unhandled packet with opcode UNKNOWN_OPCODE (0x791E)
[Session] Received unhandled packet with opcode UNKNOWN_OPCODE (0x2704)
[Session] Received unhandled packet with opcode UNKNOWN_OPCODE (0x3010)

**Comment by armm77** [comment]
CMSG_INSPECT_HONOR_STATS                          = 0x791E
MSG_INSPECT_ARENA_TEAMS                            = 0x2704
CMSG_REQUEST_INSPECT_RATED_BG_STATS       = 0x3010
