### ISSUE TITLE
Missing handler for CMSG_QUERY_BATTLEFIELD_STATE

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#480]
**Description**:
Missing handler for CMSG_QUERY_BATTLEFIELD_STATE

**Comment by schnek** [comment]
CMSG_QUERY_BATTLEFIELD_STATE = 0x7202

WorldPacketHandlers[CMSG_QUERY_BATTLEFIELD_STATE].handler = &WorldSession::HandleBattlegroundStateQuery;

void WorldSession::HandleBattlegroundStateQuery(WorldPacket& /*recvData*/)
 {
 }
