### ISSUE TITLE
[4.3.4] Auras do not work

### ISSUE THREAD

**Issue by Razfury** [AscEmu/AscEmu#485]
**Description**:  
Auras do not work as in you cannot see them where your buff bar is
**Steps to reproduce the problem**:
1. Create a paladin, login.
2.  Use seal of righteousness and notice no aura buff
3.  notice no aura buff

**Version**: WotLK / Cata (Specify Version)
Cataclysm - 4.3.4

**AscEmu hash/commit**:  
36e33aff8b08160e01dc94c6d1cc32652c3b42be

**Operating system**:  
Windows 7

**Comment by Zyres** [comment]
Fixed in e1c97ec115fbe916b0c7725808670c70f175ed4c
