### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by mwaning** [AscEmu/AscEmu#489]
After compiling and setting up, I got this error when I run the world file. Couldn't really make anything out of it myself.
Is this a known issue?

Assertion Failed: (this->mSingleton == 0)
Location: /home/ascemumaster/installer/ascemu/code/src/shared/Singleton.h(46)
Segmentation fault (core dumped)

**Steps to reproduce the problem**:
Running world

**Version**: WotLK

**AscEmu hash/commit**:  
?

**Operating system**:  
Debian 8.3 x64

**Comment by Zyres** [comment]
We need a hash... you can find it in your log file:
![](https://i.imgur.com/J6H3owW.png)

**Comment by mwaning** [comment]
Ahh, sorry. The latest hash I can find is 1faf0e0

**Comment by Zyres** [comment]
There shouldn't be this issue.... can you update to the latest version?

**Comment by mwaning** [comment]
Hmm, I got the same error after recompiling again. Maybe I should have a look at the database.

**Comment by mwaning** [comment]
Well, seems I'm left with this:

[ERROR] LoadGameObjectModelList Unable to open 'GameObjectModels.dtree' file.
Loading Weather...
Sql query failed due to [Error writing file '/tmp/MYCISxZK' (Errcode: 28)], Query: [SELECT * FROM loot_creatures ORDER BY entryid ASC]
[ERROR] LoadLootTables Loading loot from table loot_creatures failed.
Assertion Failed: (this->mSingleton == 0)
Location: /home/ascemumaster/installer/ascemu/code/src/shared/Singleton.h(46)
Segmentation fault (core dumped)

The hash is 9a626f1

**Comment by sanctum32** [comment]
try http://www.arcemu.org/wiki/Debugging, instead of arcemu-world use world and capture it

**Comment by Zyres** [comment]
Never use old articles, go with http://www.ascemu.org/wiki/index.php?title=Crash_Debug

According to your errors:

> [ERROR] LoadGameObjectModelList Unable to open 'GameObjectModels.dtree' file.

Did you extract vmaps?


> Sql query failed due to [Error writing file '/tmp/MYCISxZK' (Errcode: 28)], Query: [SELECT * FROM loot_creatures ORDER BY entryid ASC]

Your MySQL-Server runs out of disk space o.O?
