### ISSUE TITLE
Quest 5441 - Lazy Peons

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#503]
**Description**:  
Quest 5441 - Lazy Peons

**Steps to reproduce the problem:**
1. we take the quest
2. hit 
3. non-fulfillment
![image](https://user-images.githubusercontent.com/1216225/33242147-4a423ece-d2e1-11e7-992e-f1816f2dfec0.png)

**Version:** All

**Operating system:**
Not related to the issue

**Comment by schnek** [comment]
the script is already added. but for some reason it does not work.
https://github.com/AscEmu/AscEmu/blob/master/src/scripts/MiscScripts/Creatures.cpp#L98

**Comment by Razfury** [comment]
That is a creature script, it is missing the spell (handler) script I will code and p/r in a few days.

**Comment by schnek** [comment]
❤
