### ISSUE TITLE
Quest 590 - A Rogue's Deal

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#504]
**Description**:  
https://classic.wowhead.com/quest=590/a-rogues-deal

**Steps to reproduce the problem:**
1. it is impossible to kill npc
2. npc does not attack
![2017-11-26_12-08-48](https://user-images.githubusercontent.com/1216225/33243751-12a12cf2-d2fd-11e7-8ed3-61a64caa4b9a.png)

**Version:** All

**Operating system:**
Not related to the issue

**Comment by schnek** [comment]
https://www.youtube.com/watch?v=5WpMjzX8Kg0
![wowscrnshot_121717_112052](https://user-images.githubusercontent.com/1216225/34077768-7d3b4cac-e31d-11e7-9780-fadb3dedd2fa.jpg)

**Comment by Razfury** [comment]
Needs an updated AI in creature scripts to change npc flag from unattackable to attackable will p/r a fix in a few days.

**Comment by Razfury** [comment]
Wrong quest id btw, it's 590 not 8.

**Comment by schnek** [comment]
perhaps we need some function that, when a certain% hp is reached, performs a certain action..

**Comment by Appled** [comment]
> perhaps we need some function that, when a certain% hp is reached, performs a certain action..

There are 'on damage taken' functions https://github.com/AscEmu/AscEmu/blob/master/src/world/Server/Script/CreatureAIScript.h#L102

**Comment by schnek** [comment]
fix (https://github.com/AscEmu/AscEmu/pull/1023)
