### ISSUE TITLE
Creature respawn by using despawn

### ISSUE THREAD

**Issue by sanctum32** [AscEmu/AscEmu#508]
**Description**:  
When Unit::despawn(despawnTimer, respawnTimer); is called, newly respawned creature still sometimes holds dead unit data (flags).

In addition by using zero despawn timer - server crashes if there was perviously manually added events to eventmgr.

**Steps to reproduce the problem**:

1. Create creature script
2. call despawn(1000, 1000)
3. For second issue call the same function with despawn(0, 0);

**Version**: WotLK / Cata (Specify Version)

server build is WOTLK

**AscEmu hash/commit**:  

https://github.com/AscEmu/AscEmu/commit/2adcf432c5364a11825e7b13363ad1fec33ec2e1

**Operating system**:  

Windows 10 x64 bit professional build 1703

**Comment by Zyres** [comment]
I don't know what you mean with "still sometimes", since I've never experienced this issue.
The second issue is solved on the develop branch.

Can you give us a example (creature) where you wexperience the first issue (dead unit data flags).

Best regards.
