### ISSUE TITLE
Scripting - AIUpdate

### ISSUE THREAD

**Issue by sanctum32** [AscEmu/AscEmu#509]
**Description**:  
AIUpdate is called everytime even when there RegisterAIUpdateEvent wasnt called. On this scenario creature on static timers (like black temple akama events) are working without player action.
By speaking about static timers - its AIUpdate call events registered on specific time - RegisterAIUpdateEvent, ModifyAIUpdateEvent and etc or non template based timers which are calculated inside of AIUpdate function.

**Steps to reproduce the problem**:
Go to black temple and start any of akama's events

**Version**: WotLK / Cata (Specify Version)
WOTLK

**AscEmu hash/commit**:  
https://github.com/AscEmu/AscEmu/commit/2adcf432c5364a11825e7b13363ad1fec33ec2e1

**Operating system**:  
Windows 10 x64 build 1703
Arch Linux x64

**Comment by aaron02** [comment]
we have new timers for aiupdate evafairy made these. maybe you should try these.

**Comment by aaron02** [comment]
https://github.com/AscEmu/AscEmu/commit/52d7b6987429d8d9a2f0bce0f47f46d3e5635ea4

**Comment by Zyres** [comment]
Basically we moved to a steady update and there was already a discussion about it on our discord channel.
The steady update rate is 1000ms - goal is 400ms (spell update rate).
