### ISSUE TITLE
Problems with vehicles.

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#522]
**Description**:  

**Steps to reproduce the problem**:
1.  .npc spawn 28312

![image](https://user-images.githubusercontent.com/1216225/34473273-c4ab9888-ef81-11e7-9bd8-c7243e08ef40.png)
when you call the transport/vehicle, it is split into two parts..

**Version**: WotLK / Cata (Specify Version) All

**Comment by Zyres** [comment]
Sidenote:
Wintergrasp Siege Turret (28319) is a accessory (seat 7) for Wintergrasp Siege Engine (28312). However, the accessories are not bound to the defined seats (MySQL table vehicle_accessories.

**Comment by schnek** [comment]
https://github.com/AscEmu/AscEmu/issues/884 most likely this is the same

**Comment by Zyres** [comment]
Closed, check out #884
