### ISSUE TITLE
Classic: Enter world - stuck in login screen

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#545]
**Description**:  
Login requires some work since we stuck before actually log into world

**Steps to reproduce the problem**:
1.  Build AE for classic
2.  try to log into world

**Version**: Classic

**AscEmu hash/commit**:  
a6d56a8be3b49f95a16077dd7d26f0fd4ce712b5

**Operating system**:  
Win10/x64

**Comment by Zyres** [comment]
New behavior since 55bfd67bf3b33174c4794b50b2c941b95a903315 no stuck just getting throw back to character screen.

**Comment by Viste** [comment]
why not actual client 1.13.X?

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/3467f3eda4ec345ebbc025b7560e332b6f95f9b0

**Comment by schnek** [comment]
![image](https://user-images.githubusercontent.com/1216225/162738813-4c936e14-a07e-48c8-bc02-a865ea9b3dd8.png)
unpin 😅😁

**Comment by Appled** [comment]
Hehe 😛
