### ISSUE TITLE
Doc: Creature and InstanceScripts

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#547]
**Description**:  
Documentation is required for the entire Instance- and CreatureScript class since a user already ragequited twice.

**Steps to reproduce the problem**:
1.  Open wiki
2.  Search for documentation
3.  Become angry and leave the project because there is no documentation

**Version**: All

**Comment by jameyboor** [comment]
Are you okay friend?

**Comment by Zyres** [comment]
@jameyboor of course, hope you are okay too?

**Comment by jameyboor** [comment]
I am, I am. Hang in there

**Comment by Zyres** [comment]
@jameyboor I do for an eternity. I've created these sarkastic issues to keep track of all the things people complaining. No need to worry about me, I'm fine ;-)
