### ISSUE TITLE
Simplify spell_* tables - and custom values

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#556]
**Description**:  
The following tables holds override values for dbc spells and/or its custom fields in class SpellInfo:
- spell_ranks (custom_RankNumber)
- spell_custom_assign (custom_BGR_one_buff_on_target, custom_self_cast_only, custom_c_is_flags)
- spell_coef_flags (custom_spell_coef_flags)
- spell_proc (custom_proc_interval)

The following vars gets set by the core (SpellCustomization.cpp):
- custom_is_melee_spell
- custom_is_ranged_spell
- custom_c_is_flags
- CustomFlags
- custom_apply_on_shapeshift_change

Several changes to the basic data (dbc) are applied in Hackfixes.cpp

The idea after a short discussion on discord was, to hold all these values in a single table to reduce the complexity of the several sources.
We can add another key to this table (statet in https://github.com/AscEmu/AscEmu/issues/541) to ship the correct override values to the correct game version.

Just an idea to simplify spellfixes by override values.

**Comment by Appled** [comment]
Honestly I don't know the point of spell_ranks and custom_ranknumber. The data in spell_ranks is 99,8% false and has unused/test spells. Besides spell ranks are already provided in DBC files.
spell_coef_flags also seems to have unused/test spells.

But combining the four tables into one could definitely be a effective solution, not just for community but for us as well. Like you said, less complex.

**Comment by Zyres** [comment]
Done in AscEmu/OneDB@d3d7d31ebfc933d16743a49dc59724132975243b
