### ISSUE TITLE
Project: GitHub Pages for Wiki replacement.

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#557]
**Description**:  
Currently we use mediawiki for our wiki and it is, as you can guess, as painfull as it could get.
The big benefit of GitHub is to colaborate, track development and just simply work together.
If we are talking about wikis in general we all know that wikis are often out of date or just not as good as it should be. The wiki available on Github is really not a solution to take care about our documentation.

But there is hope and a solution is called GitHub Pages. Everyone is familiar with pullrequest and issues and can participate in a GitHub Page.. so why should we use something else?

It is open for debate, so what is your opinion on this?

**Comment by Sdyessdev** [comment]
I think GitHub pages would be fine, there's no reason not to use it. Modern and has everything that should be offered in documentation ability.

A Doxygen is always nice though as well, but it would serve as a supplementary item.

**Comment by armm77** [comment]
I agree with @Zyres , we handle the information with Github, it is a unique point of work.

**Comment by Zyres** [comment]
Available on https://ascemu.github.io/Wiki/
