### ISSUE TITLE
Missing NPCs Injured Soldiers (classic)

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#559]
**Description**:  
According to the file Quest_FirstAid.cpp we change the health of several npcs.
The following npcs are not in our spawn table:
- 12923 (added in patch 1.11.1.7272)
- 12924 (added in patch 1.11.1.7272)
- 12925 (added in patch 1.11.1.7272)

The npcs are part of the quest: 6622
This issue is for the upcomming classic changes.

**Comment by Appled** [comment]
The NPCs should be spawned by a script when starting the quest 6622, they do not exist elsewhere in world.
See here https://www.youtube.com/watch?v=nTMuoifKnMw
Same quest is for hordes in Arathi Highlands.

**Comment by Zyres** [comment]
As statet they will be spawned by script. No need for them to be in our spawntables
