### ISSUE TITLE
Multiversion DB - open discussion

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#561]
In 2017 we decided to support multiple game versions in one repo. The basic argument for this was "We are to not enough devs to support more than one repo" and "We have to change/rewrite most/all basic functions and it is a lot of work for one repo".

After this decision, we modified the login server to handle classic, TBC, WotLK and cataclysm based on the client version. We ported our cataclysm development entirely into our main repo and working right now on TBC/classic. The world server gets build for a specific game version, declared by the CMake options.

Now we have to decide how we will support our database and we will have two options:
1. Separated WorldDBs
2. OneDB for all versions

I would appreciate your opinions on this topic. Here are the results of my last weeks brainstorming:

|  OneDB - pro  | OneDB - con  |
|---|---|
| Only one DB to develop | Complexity |
| reduce (amount) update files | worry about all versions |
| (simple) switch to another game version | |
| full overview of data history | |

## How to achieve a single DB for all versions?
First of all, we have to add one or even two additional key to our tables. I already tested something in this direction. From my point of view, we need two new fields.

## *_properties tables
**The first field** is to determine in which version the data was **introduced**. Since we have to deal with a lot more than just a minor patch version, we could use the build number instead. (we already use the build number for version specific code in our core) e.g. https://ascemu.github.io/Wiki/docs/unsorted/clientversions/.

**The second field** is to determine in which version the data was **removed**. Brotalnia already stated, that some data like items never was removed (players will have them forever), but it is important to check if the data is still available for loots/quests/...

## *_spawns, *_loot tables
There is a problem with spawn and loot tables. Since Cataclysm, most areas changed and most spawns from WotLK are no longer valid there. We already have at least two possible solutions.

A **second key** to check if the spawn is valid for the version or **separated tables** for each version.
1. The key value could be a flag like 1 = classic, 2 = TBC, 4 = WotLK and 8 = Cata. (an even larger amount of data in these tables)
2. The separated can be loaded based on the game server build. (clean solution, but ugly as hell)

## What to load?
We never load newer data. all properties data introduced in a newer build than the core version will be ignored.
e.g. `SELECT * FROM item_properties WHERE valid_since_build <= VERSION_STRING;`

We never load older and outdated data (like altered items).
e.g. `SELECT * FROM item_properties WHERE valid_since_build <= VERSION_STRING AND deprecated_since_build > VERSION_STRING;`

If data is not deprecated in any build or we simply don't know when it was deprecated, we could leave it with 0:
e.g. `SELECT * FROM item_properties WHERE valid_since_build <= VERSION_STRING AND (deprecated_since_build > VERSION_STRING OR deprecated_since_build = 0)`;

## Table changes
At this point we differ between properties and spawns.
Properties tables will include the build number for historical reference. Almost every item which gets removed from the world will be altered so players can use/trade them or still use them but with other stats. Spawns will include the valid version flag since we support only the last patch of every version.

To replace the old primary/unique key for **properties**, here is an example:
```
ALTER TABLE `item_properties`
ADD COLUMN `valid_since_build` SMALLINT(6) NOT NULL DEFAULT 0 AFTER `entry`,
ADD COLUMN `deprecated_since_build` SMALLINT(6) NOT NULL DEFAULT 0 AFTER `valid_since_build`,
ADD COLUMN `comment` LONGTEXT NULL AFTER `food_type`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`entry`,`valid_since_build`,`deprecated_since_build`),
ADD UNIQUE KEY `unique_index` (`entry`,`valid_since_build`,`deprecated_since_build`) USING BTREE;
```

To replace the old primary/unique key for **spawns**, here is an example:
```
ALTER TABLE `creature_spawns`
ADD COLUMN `build_flag` SMALLINT(2) NOT NULL DEFAULT 0 AFTER `id`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`,`build_flag`),
ADD UNIQUE KEY `unique_index` (`id`,`build_flag`) USING BTREE;
```

## Structural differences between versions
To achieve a single DB for all versions, we have to create standard table structures. This will led to unused columns in the different versions. We can leave the data unloaded if we do not need them. On the bright side, we will have a much simpler documentation on our wiki (documentation is written for all versions instead of writing documentation for every supported version.)

**I would love to read your opinion on this.**

**Comment by armm77** [comment]
I think it would be easier to manage and maintain a single database for all versions, and we can handle each version with flags. From the classic version to the woltk the npc and objects have remained in the same places or changed very few, they can be reused, and with certain adjustments everything can work well. In cataclysm several maps changed and the npc and objects where they can be relocated but also the same ones that were not modified can be used.

Handle multiple versions would be more cleaning work relocation removal etc.

**Comment by Appled** [comment]
I'm all in for one DB. Also with a quick glance it seems at least these following tables would require a gamebuild field:
- ai_agents (or the new script system in future)
- creature_*
- event_*
- fishing
- gameobject_*
- gossip_menu_*
- graveyards
- instance_bosses
- item_*
- itemset_linked_itemsetbonus
- lfg_dungeon_rewards
- locales_* (although they are empty right now)
- loot_*
- npc_*
- pet*
- player_xp_for_level (amount of XP required for 1-60 was for example reduced in TBC)
- playercreateinfo*
- quest_*
- reputation_*
- spell_*
- trainer_*
- vehicle_* (not sure actually)
- vendors
- worldmap_info

**Comment by schnek** [comment]
a single solution will be more correct. this will help to find no match.
![image](https://user-images.githubusercontent.com/1216225/36776551-48749026-1c77-11e8-9d1a-f946d552c27c.png)

**Comment by Zyres** [comment]
Closed since oneDB is already implemented
