### ISSUE TITLE
Failed to create linked trap (entry: 195641) for GameObject 191488 ( Smoldering Brazier ). Missing GOProperties!

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#562]
**Description**:  Failed to create linked trap

**Expected behaviour**: No error in world console and this go should be available in db

**Steps to reproduce the problem**:
1. Start AE
2. Zone Howling Fjord

**Version**: WotLK / Cata 

**AscEmu hash/commit**:  

**Operating system**:  Win 10

**Lua scripts**: No

**Other Customizations**: No

Failed to create linked trap (entry: 195641) for GameObject 191488 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191489 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191490 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191491 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191492 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191493 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191494 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191495 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191496 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191497 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191486 ( Smoldering Brazier ). Missing GOProperties!
Failed to create linked trap (entry: 195641) for GameObject 191487 ( Smoldering Brazier ). Missing GOProperties!

**Comment by Zyres** [comment]
Should be fixed with the db updates in the last year. However, the gameobject_properties are available, so closed for now.
