### ISSUE TITLE
TBC: MONSTER_MOVE - spline missing for now

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#566]
**Description**:  
SMSG_MONSTER_MOVE crashed the client. The packet lack now spline movement.
Movement/CreatureMovement.cpp / void SendMoveToPacket(Unit* pUnit)

**Version**: TBC

**AscEmu hash/commit**:  c3cfbb2e74d47340f2e035eda86b90010bff9c5c

**Operating system**:  Win10

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/pull/879
