### ISSUE TITLE
Lesser ranks of talents should be removed upon learning higher rank

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#570]
**Description**:  
Title. I think it works for most talents but talents which give you additional spells aren't working properly. See this talent for example https://wotlk.evowow.com/?spell=64353. When you learn its higher rank, it "properly" removes the lower rank but does not remove the spells the talent gave you. 
I will personally look into it, I just had to make an issue or I'll forget otherwise 😄 

**Version**: WotLK / Cata (Specify Version)
All

**Comment by Zyres** [comment]
Is there an update on this?

**Comment by Appled** [comment]
@Zyres already done but can't pr yet

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/e1f4a622bb6eae0ffed4364d8669932805c3bfa0
