### ISSUE TITLE
Assertion Failed: (this->mSingleton == 0)

### ISSUE THREAD

**Issue by theralio** [AscEmu/AscEmu#574]
I configurated everything and wanted to start the world and i cant bcs of this issue

Assertion Failed: (this->mSingleton == 0)
Location: /home/ascemu/installer/ascemu/code/src/shared/Singleton.h(46)
Segmentation fault (core dumped)

Steps to reproduce the problem:
When i run the world

Version: WotLK

AscEmu hash/commit:
AscEmu b1e283a9/Release-Linux (X64)

Operating system:
Ubuntu 17.10

**Comment by Zyres** [comment]
The following modules are the reason of this world crash:
* libBattlegrounds.so
* libEventScripts.so
* libGossipScripts.so
* libLuaEngine.so
* libMiscScripts.so
* libSpellHandlers.so

**Comment by Zyres** [comment]
Not fixed.
