### ISSUE TITLE
AscEmu under Debian 9 use MariaDB by default (wiki not up to date)

### ISSUE THREAD

**Issue by Inifield** [AscEmu/AscEmu#576]
**Description**:  
Title

**Steps to reproduce the problem**:
1. Follow the wiki tutorial (for ubuntu)
2. Realize Debian 9 use MariaDB by default

**Version**: WotLK

**AscEmu hash/commit**:  https://github.com/AscEmu/AscEmu/commit/b1e283a91ad21fd88b483a5aecb75bbe779c22f7

**Operating system**:  
Debian 9  x64

https://pastebin.com/LKr14Ftq

**Comment by Zyres** [comment]
Closed, it is a wiki issue not a core issue.
