### ISSUE TITLE
Talents and Glyphs Cataclysm

### ISSUE THREAD

**Issue by armm77** [AscEmu/AscEmu#580]
**Description**:  
1. The talents in cataclysm are 41, they start at level 10 and they only increase in inparent levels, when they reach level 81 and then all levels up to 85, example {10,11,13,15,17 ..... 81,82,83,84,85}. When the 30 points used in a specific branch are reached, the two alternate branches are activated in order to use the points.
2. The glyphs activate in level 25 the first 3, then the next 3 in the 50 and the last 3 in the 75.
3. Currently the talent points counter is working with the woltk version, it is counting 76 talent points and the glyphs are only activated 3 in level 25, then in level 50 the 50 are activated and those in 25 are deactivated, and in level 75 those of level 75 are activated and those of 25 and 50 are deactivated.

**Steps to reproduce the problem**:
1. Upload any character of any race to level 85 and check the points and glyphs.

**Version**: Cata (Specify Version)

**AscEmu hash/commit**:  
https://github.com/AscEmu/AscEmu/commit/c81805ca4e4aaf005707eff228110bebb3d10523
**Operating system**:  
WIN/MAC

**Comment by Appled** [comment]
I'm next looking at some issues with talents so I can try to take a look at this as well.

**Comment by Razfury** [comment]
used to be in player.cpp but now it's gone somewhere ❌

**Comment by Appled** [comment]
I've fixed the issues locally but I have yet to finish some other things before pushing.

**Comment by Zyres** [comment]
@Appled some update on this?

**Comment by Appled** [comment]
@Zyres there are still some issues in the talent system but I'm trying to sort them out asap.

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/e1f4a622bb6eae0ffed4364d8669932805c3bfa0
