### ISSUE TITLE
[Cataclysm] Spell visuals are missing

### ISSUE THREAD

**Issue by Razfury** [AscEmu/AscEmu#586]
**Description**:  
Spell visual after casting spells are not displaying
**Steps to reproduce the problem**:
1. Create a human mage 
2.  Cast fireball at a monster
3.  Notice there is no spell visual after casting the spell, damage works as intended however the spells visual does not work.

**Version**: WotLK / Cata (Specify Version)
4.3.4 Cata
**AscEmu hash/commit**:  
17f466b60247e3fda3f9ee3c727ad562ed2435e5
**Operating system**:  
win 10- 64bit

**Comment by Zyres** [comment]
From chat: found out it needs updated in unit.cpp
WorldPacket data(SMSG_PLAY_SPELL_VISUAL, 8 + 4 + 8);
should be
WorldPacket data(SMSG_PLAY_SPELL_VISUAL_KIT, 4 + 4+ 4 + 8);
it is using an old obsolete opcode
SMSG_PLAY_SPELL_VISUAL_KIT replaced SMSG_PLAY_SPELL_VISUAL after 4.0

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/25bdfddbd431d7f06c832f035d7819d0e929d4b2
