### ISSUE TITLE
Fail with the Orcs

### ISSUE THREAD

**Issue by armm77** [AscEmu/AscEmu#587]
**Description**:  
Creating an Orc does not allow you to be in the world for more than 5 minutes when the client crashes.

**Steps to reproduce the problem**:
1. Enter the game create an orc any gender and class, and wait for the client to crash.

**Version**: WotLK / Cata (Specify Version)
4.3.4 (15595)

**AscEmu hash/commit**:  
https://github.com/AscEmu/AscEmu/commit/39d8230f6f0e0cf4449a238c0139e81db135a488

**Operating system**:  
Win7 x64 / OSX 10.12.6

**Comment by Razfury** [comment]
Can you provide a crashdump either RelwithDebug or debug compile please?

**Comment by armm77** [comment]
I can not because the server does not crash, it's just the client.
