### ISSUE TITLE
error mount 

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#590]
**Description**:  

**Steps to reproduce the problem**:
1. pass training in horse riding
2. buy a mount
http://www.wowhead.com/item=29470/red-skeletal-warhorse
http://www.wowhead.com/item=13332/blue-skeletal-horse
http://www.wowhead.com/item=13334/green-skeletal-warhorse
http://www.wowhead.com/item=18791/purple-skeletal-warhorse
http://www.wowhead.com/item=47101/ochre-skeletal-warhorse
http://www.wowhead.com/item=46308/black-skeletal-horse
3. сast error

**Version**: WotLK / Cata

**AscEmu hash/commit**: 5a82ee7dcee5c5e1802714bda947c6c18be51fc3

**Comment by Zyres** [comment]
1. AscEmu hash of your version is missing.
2. Which mount/spell (id)?
3. error mount/cast error is not useful at all! What error? What message?...
