### ISSUE TITLE
[Error] Trainer Buy Spell Opcode 

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#592]
**Description**:  

**Steps to reproduce the problem**:
[DETAIL] WorldSession::handleGossipSelectOptionOpcode Received CMSG_GOSSIP_SELECT_OPTION: 0 (gossipId), 1 (option), 2768240810 (guidLow)
![wowscrnshot_070618_224826](https://user-images.githubusercontent.com/1216225/42398179-768513e6-8171-11e8-8e09-2e89e6f4e77f.jpg)
Try to learn the ability
[DEBUG] WorldSession::handleTrainerBuySpellOpcode Received CMSG_TRAINER_BUY_SPELL: 170 (guidLowPart)
The ability is not studied

**Version**: WotLK

**AscEmu hash/commit**:  d680126

**Operating system**:  10/win64

**Comment by Zyres** [comment]
The spell (33388) requires level 40 serverside. Currently looking into it to find the reason.

**Comment by Zyres** [comment]
closed in 8c0c2d9ce08e11df5e38a3de6e0be091e41e60aa
