### ISSUE TITLE
TBC: No spells in action bar/spellbook

### ISSUE THREAD

**Issue by Inifield** [AscEmu/AscEmu#599]
**Description**:  
We should have default spells

**Steps to reproduce the problem**:
1. Create a character
2. Look in your action bar/spellbook
3.  https://i.imgur.com/Fy4XqUz.jpg

**Version**: TBC

**AscEmu hash/commit**:  492f7f111a216426db5f7c268ac5b6b29cff37ed

**Operating system**:  Windows 10 x64

**Comment by Appled** [comment]
Playercreateinfo_spells table has only default spells for 3.3.5a and 4.3.4 builds
