### ISSUE TITLE
TBC: Missing weapon models

### ISSUE THREAD

**Issue by Inifield** [AscEmu/AscEmu#600]
**Description**:  
Some npcs are missings their weapon models

**Steps to reproduce the problem**:
1. Find an NPC that should have a weapon
2.  https://i.imgur.com/29yCE9t.jpg
3. 

**Version**: TBC

**AscEmu hash/commit**:  492f7f111a216426db5f7c268ac5b6b29cff37ed

**Operating system**:  Windows10

**Comment by Zyres** [comment]
Duplicate check out #568
