### ISSUE TITLE
TBC: Can't sell items

### ISSUE THREAD

**Issue by Inifield** [AscEmu/AscEmu#603]
**Description**:  
We can't sell items

**Steps to reproduce the problem**:
1. Log any char
2. Try to sell anything, it will become gray and that's it.
3. log out and try to log back in you'll get wow error you will need to restart the server to be able to log back

**Version**: TBC

**AscEmu hash/commit**:  https://github.com/AscEmu/AscEmu/commit/492f7f111a216426db5f7c268ac5b6b29cff37ed

**Operating system**:  Windows 10

**Comment by Zyres** [comment]
> log out and try to log back in you'll get wow error you will need to restart the server to be able to log back

should no longer happen
