### ISSUE TITLE
TBC: Mob run crazy fast when attacking you

### ISSUE THREAD

**Issue by Inifield** [AscEmu/AscEmu#606]
**Description**:  
When you attack a moband you get him to attack you, he will run at you crazy fast

**Steps to reproduce the problem**:
1. Attack a mob and see his movement speed go crazy
2. https://streamable.com/q31zt
3. 

**Version**: TBW

**AscEmu hash/commit**:  https://github.com/AscEmu/AscEmu/commit/492f7f111a216426db5f7c268ac5b6b29cff37ed

**Operating system**:  Windows 10

**Comment by Appled** [comment]
Also same as https://github.com/AscEmu/AscEmu/issues/612#issuecomment-407611307
