### ISSUE TITLE
TBC: Rogue don't have energy

### ISSUE THREAD

**Issue by Inifield** [AscEmu/AscEmu#609]
**Description**:  
Title

**Steps to reproduce the problem**:
1. Create a rogue
2. Look your energy bar, it's empty
3. https://i.imgur.com/6U0M5Yh.jpg

**Version**: TBC

**AscEmu hash/commit**:  https://github.com/AscEmu/AscEmu/commit/492f7f111a216426db5f7c268ac5b6b29cff37ed

**Operating system**:  Windows 10

**Comment by Appled** [comment]
Missing energy regen flag for classic and TBC? See https://github.com/AscEmu/AscEmu/commit/00f1bf647f0a9e83893c0898f689643bb283908a
