### ISSUE TITLE
TBC: Mob aren't moving at all

### ISSUE THREAD

**Issue by Inifield** [AscEmu/AscEmu#610]
**Description**:  
IT seems monster aren't moving (they just stay at one place)

**Steps to reproduce the problem**:
1.  Log a char
2. Observe any creature
3. 

**Version**: TBC

**AscEmu hash/commit**:  https://github.com/AscEmu/AscEmu/commit/492f7f111a216426db5f7c268ac5b6b29cff37ed

**Operating system**:  Windows 10

**Comment by Appled** [comment]
Same as https://github.com/AscEmu/AscEmu/issues/612

**Comment by Zyres** [comment]
Related to #566
