### ISSUE TITLE
TBC: Aggro range

### ISSUE THREAD

**Issue by Inifield** [AscEmu/AscEmu#612]
**Description**:  
The aggro range seems weird, mobs are slightly slow, they need a good second to see that i'm near them, as level 1 I shouldn't be able to go near them

**Steps to reproduce the problem**:
1. Get a level 1 char and find a level 7 "hostile" mob and go as near him as possible
2. https://streamable.com/lmhgm
3. 

**Version**: TBC 

**AscEmu hash/commit**:  https://github.com/AscEmu/AscEmu/commit/492f7f111a216426db5f7c268ac5b6b29cff37ed

**Operating system**:  Windows 10

**Comment by Appled** [comment]
Try extract mmaps. I had that similiar behaviour when I didn't have mmaps.

**Comment by Inifield** [comment]
I'll try but I heard they takes ten years to extract, so i'll take a while
