### ISSUE TITLE
[Cata] SMSG_UPDATE_OBJECT fails and disconnects client

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#625]
**Description**: 
Your client gets randomly disconnected while moving around. This can also happen on login. For example I was logging in and in the end of loading screen, the loading screen like repopped and started over. After that I got sent back to realmlist. Worldserver says this: https://image.ibb.co/cAz8Xz/worldserver.jpg
Another picture (this happened while I was moving around): https://image.ibb.co/fRCvCz/disconnects.jpg

Also sometimes it doesn't disconnect, it puts your character into weird state where you are not in game according to worldserver and you cannot see any textures.

**Steps to reproduce the problem**:
I got it reproduced everytime with these steps:
1. Logon any character
2. .recall port stormwindharbor
3. Move the stairs up behind / in front of you

**Version**: WotLK / Cata (Specify Version)
Cata only
**AscEmu hash/commit**:  
https://github.com/AscEmu/AscEmu/commit/4dabcc10417e064f0999970929700656ceb53722
**Operating system**:  
Win 10 Pro

Additional notes: I have vmaps and maps built

**Comment by Appled** [comment]
Another pic, I was running to Westfall and mob was attacking me: https://image.ibb.co/fRCvCz/disconnects.jpg

**Comment by aaron02** [comment]
maybe this means something to the zones they added crossrealm support so opcode needs to be handled in someway but its just a guessing

**Comment by Appled** [comment]
@aaron02 weren't crossrealm zones added later in MoP? I can be mistaken though

**Comment by aaron02** [comment]
i played evry expansion correct me if i am wrong but first cross realm zone was westfall / bridge to wald of elwin added in cata

**Comment by Meltie2013** [comment]
First parts of Cross Realm Zones where implemented in 4.3.4a, near the end of the Cataclysm Expansion. The full CRZ was done in MoP.

**Comment by Appled** [comment]
So far we know that this is caused by SMSG_UPDATE_OBJECT opcode but this opcode is sent from so many different places so it will take time to find the faulty packet.

**Comment by Zyres** [comment]
While trying to reproduce this issue...
![random teleport](https://i.imgur.com/SdU62Xj.png)

I got teleported to the area, not really sure if it is related to this issue.

**Comment by Appled** [comment]
Yeah, that also happened to me several times

**Comment by Zyres** [comment]
Not reproduceable with 7df0940a5040b9ff2a43d0cc73fb700d30888c1a

**Comment by Appled** [comment]
Happens again with https://github.com/AscEmu/AscEmu/commit/4dabcc10417e064f0999970929700656ceb53722
I've updated the issue with new steps to reproduce the issue. 
Worldserver spams "Object update failed for playerguid".

**Comment by Appled** [comment]
Actually it was a mistake in my PR XD
