### ISSUE TITLE
Experimental filesystem; configs directory

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#632]
**Description**:  
Experimental filesystem checks for configs, dbc and maps directories atm.
On unix systems configs folder is called etc, by default I guess, and filesystem won't find it.
See here https://github.com/AscEmu/AscEmu/blob/master/src/world/Server/Master.cpp#L129
In Windows' cmake you can change the name of the configs directory as well so that needs to be taken in account. Maybe replace hardcoded 'configs' from Master.cpp to https://github.com/AscEmu/AscEmu/blob/master/src/world/WorldConf.h.in#L8 ?

**Comment by schnek** [comment]
@appled check?, close

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/2085d3da6c2576517bcdbac69b0e6a2fc690f334
