### ISSUE TITLE
Creature movement without mmaps

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#634]
**Description**:  
At the moment creatures don't move at all if you don't have movement maps (mmaps) extracted. If you go in-game you can see all mobs standing still and doing nothing. If you attack one and you move around, you can see the creature "teleporting" to your location.
But when you extract mmaps, these issues go away. Someone said it could be a spline issue?

**Expected behavior**:
Creatures should move like they move with movement maps extracted but they just shouldn't use pathfinder between movement points.

**Steps to reproduce the problem**:
1. If you have mmaps loaded, disable them from configs file
2. Start server and log in
3. Observe creatures anywhere in the world and try attacking them (More steps and videos in issues in the comment below)

**Version**: WotLK / Cata (Specify Version)
So far confirmed on wotlk and tbc but I'm going to assume it affects all versions.

**AscEmu hash/commit**:  
https://github.com/AscEmu/AscEmu/commit/da2b65c658f5679e149da008aa3e57e6ad2f4ad8

**Operating system**:  
Doesn't matter

**Comment by Appled** [comment]
https://github.com/AscEmu/AscEmu/issues/610
https://github.com/AscEmu/AscEmu/issues/612
https://github.com/AscEmu/AscEmu/issues/606

**Comment by Zyres** [comment]
Works for me with the latest dev version, can you retest it?

**Comment by Evairfairy** [comment]
@Zyres I think this was related to a different issue that I resolved while working on BC enter world/creature movement, but I'd have to double check.

**Comment by Appled** [comment]
Partly working. Creatures now can move without mmaps but when attacked they still "teleport" to your location.

**Comment by Zyres** [comment]
@Evairfairy already double checked?
