### ISSUE TITLE
Proposal Roadmap 2020

### ISSUE THREAD

**Issue by Zallios** [AscEmu/AscEmu#651]
This issue is for topic collection and planning of the roadmap 2019.

**Ideas:**

**Goals:**
- [x] LUAEngine documentation

**Data:**

- [x] Add recall positions for cata (#707)
- [x] holiday events for cata (#706)
- - [x] gobj spawns
- - [ ] npc spawns

Feel free to post more ideas or goals to be achieved.

**Comment by Inifield** [comment]
Revamp the way we do scripting (ai_agents & related) to something better and take a look at this, very good read https://github.com/TrinityCore/TrinityCore/pull/22461

**Comment by schnek** [comment]
LUAEngine documentation: [clik](https://ascemu.github.io/Wiki/docs/standards_sctipts/standards_lua/)

**Comment by Zyres** [comment]
Seems we missed our goals for 2019, so let us set it up for 2020 ;-)

**Comment by Zyres** [comment]
Closed. There are now issues for the important ideas/bugs.
