### ISSUE TITLE
Position update after teleporting

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#655]
**Description**:  
Your position does not update properly after teleporting.
After relogging once, your position is now updated correctly.

**Steps to reproduce the problem**:
1. Create new horde character
2. It's best to do .cheat god
3. Teleport to goldshire, .recall port goldshire
4. Notice how npcs attack you
5. Move around and see that npcs don't follow you but they're still attacking you (if you relog once, then your position is updated)

or

1. Use whatever character
2. Teleport to human starting area, .recall port northshire
3. Move around (like to the closest tree) and relog
4. Notice after relogging you're still at the position where you teleported.

**Version**: WotLK / Cata (Specify Version)
All

**AscEmu hash/commit**:  
https://github.com/AscEmu/AscEmu/commit/08c28a1235263aa3c55f0dce7de64bb6524ab43d

**Operating system**:  
All

**Comment by Inifield** [comment]
Can this issue by extended to ship etc ? or is it just a teleport problem ?

**Comment by Appled** [comment]
I haven't tested transports but it could also happen with them since with transports you'd teleport to another location

**Comment by Zyres** [comment]
Resolved

> or
> 1. Use whatever character
> 2. Teleport to human starting area, .recall port northshire
> 3. Move around (like to the closest tree) and relog
> 4. Notice after relogging you're still at the position where you teleported

In 73ab3b8a3084c83e76809f19359dd65a0158cd0f
