### ISSUE TITLE
[Talent - Warrior] Juggernaut

### ISSUE THREAD

**Issue by Razfury** [AscEmu/AscEmu#658]

**Comment by Appled** [comment]
Earlier I had narrowed the issue to aura updating. If you do ".debug auraupdate 64976 0 0", without quotes of course, you can now cast charge in combat until you relog.
Seems like somewhere there is missing an aura update to client.

**Comment by Zyres** [comment]
Why do you close it?

**Comment by Zyres** [comment]
Invalid issue, description removed by author.
