### ISSUE TITLE
ICC: Gunship Battle

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#66]
# The Gunship Battle
- [x] Gunships not moving
- [ ] Missing Gunship Battle event

See also: #65

**Comment by Zyres** [comment]
@aaron02 This is scripted, can we close this issue?

**Comment by aaron02** [comment]
its scripted about 70 % a little part of the battle is still missing atm had some spell issues i will look at it and finish the gunshipbattle script

**Comment by Zyres** [comment]
Closed for now, we will track this in #65
