### ISSUE TITLE
[Dungeon Finder] If player leaves, group cannot requeue

### ISSUE THREAD

**Issue by Razfury** [AscEmu/AscEmu#660]

**Comment by Zyres** [comment]
Why do you close the issue? there is nor reference that this issue was fixed.

**Comment by Razfury** [comment]
Seems as if rolecheck never makes it to the player to click accept or decline - if you wait about 2 minutes the error message comes up with the rolecheck failed message.

**Comment by Zyres** [comment]
Closed since description is missing.
