### ISSUE TITLE
Рroblem with the quest npc at different levels of the character.

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#671]
**Description**:  
When you're level 1-5 the npc won't send the starting quest to player. Nothing happens when you try to interact with him.
But when you're level 6, the npc now sends the starting quest to player.

**Steps to reproduce the problem**:
1. сreate undead.
2. interact with the first NPC

3. from 1-5 lvl
![wowscrnshot_010219_150041](https://user-images.githubusercontent.com/1216225/50651346-172e5680-0f94-11e9-9580-c1119250c010.jpg)

4. from 6-.... lvl
![wowscrnshot_010219_141219](https://user-images.githubusercontent.com/1216225/50651390-3af19c80-0f94-11e9-83d3-c37444eb7662.jpg)

**Version**: WotLK

**Comment by Appled** [comment]
Can you test other races?

**Comment by schnek** [comment]
tested on all professions undead. for all other races this quest is not available (as the first quest. as I understand it).

**Comment by Zyres** [comment]
Same issue for Orc starting quest
