### ISSUE TITLE
LearnSpell: Spellbook + GUI Rebuilding

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#70]
Another minor issue I came across:
When you learn spells that have ranks, your spellbook gets a new entry for each rank, yet all ranks are updated to the highest achieved rank. So for instance you learn heroic strike 2+3 you would have three entries all entitled heroic strike 3.

While this is not really a striking issue another one is really annoying and I'm sure it originates in the same source: Skills that have an extra bar (Paladin Auras, Shapeshifting etc.) also get second entries in the GUI, so that not only your spellbook is spammed with skills but your GUI as you have, let's say for instance, 4 times the Devotion Aura in your Interface.

The good thing about this issue: The GUI gets rebuild after logout/login so there is some function that handles this rebuilding, it only needs to be called after learning a new skill, this would certainly fix this issue.
## Phi92

When learning paladin spells from trainer, case for auras, look how my action bar looks after I Train all my spells from trainer:

2x Devotion Aura, 2x Retribution Aura, 2x Shadow Resistance Aura, 2x Frost Resistance Aura

http://img37.imageshack.us/img37/8543/wowscrnshot020913131223.jpg

After you relog looks rebuilded:

http://img221.imageshack.us/img221/6176/wowscrnshot020913131614.jpg
ghost

**Comment by Zyres** [comment]
Closed check out #973
