### ISSUE TITLE
problems loading world.exe

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#703]
**Description**:  
The problem appears when loading world.exe. Appears when downloading 3 .. and 4 .. versions.

**Steps to reproduce the problem**:
1. deletes all files. Download again 👌
2. copy AscEmu/configs 
3. compile and run

loading stops at ...

`  InstanceMgr : Deleting Expired Instances...` 
`  InstanceMgr : Loading 0 saved instances.` 

`void Instance::LoadFromDB(Field* fields)` 

if you comment out the function then the load will be already 

`[DETAIL] Map::LoadSpawns 0 creatures / 0 gobjects on map 616 cached.`
`[DETAIL] Map::LoadSpawns 0 creatures / 0 gobjects on map 628 cached.`

**Version**: WotLK / Cata

**Comment by Zyres** [comment]
I can't reproduce it with a fresh db, anybody else?

**Comment by schnek** [comment]
using full db + updates from db repository + latest core updates

**Comment by schnek** [comment]
yesterday checked again the problem was resolved. 
> https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by schnek** [comment]
closed.
