### ISSUE TITLE
Flight Master Cata - Server crash or no flight path

### ISSUE THREAD

**Issue by Zallios** [AscEmu/AscEmu#708]
**Description**:  
Some flight master let crash the server after you speak with them.
Other give you a flight path but the next flight master say you didn't have a flight path.

**Steps to reproduce the first problem**:
1. Go to the flight master in goldshire (human, alliance)
2. Speak to him.
3. Open map. - Server crashes -

**Steps to reproduce the second problem**:
1. Go to the flight master in bloodhoof billage (tauren, horde)
2. Speak to him. He give you a flight path/point.
3. Go to the flight master in thunder bluff.
4. Speak to him. He says no flight path.

**Version**: Cata

**Operating system**:  Windows 10

**Comment by Zyres** [comment]
packet issue. the size of taximask is now 114.
It is pretty possible that the wrong packet size leaks some other functions.
