### ISSUE TITLE
Vehicle Faction Bug

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#71]
I don't know what it is like on retail but when you enter a vehicle it
should probably take on your faction ID. For instance the horse vehicles
in The Scarlet Enclave keep their faction, so when you take a ride into
Death Breach, all the NPC's that are friendly to you will kill your horse
and then leave you alone.

Maybe this is not a core issue and on retail servers the horse vehicles
just have a different faction by default, in this case i apologize for
bothering you with this bug.

As the entire DK starting area needs scripting I just posted this because
it might be an issue to vehicles in general.

Keep up the good work ;)
blackdragon145
blackdragon145 commented on 10 Nov 2011

The horse vehicles in The Scarlet Enclave have the right faction. We only need to script the entire DK starting area. But vehicles is new, So we didn't get the time to script vehicles things.
Phi92
Phi92 commented on 10 Nov 2011

Yes, I was just thinking that this is not DK-Area related but in general to vehicles. I mean basically vehicles do work it is just that when you enter the vehicle, the vehicle itself should take on your faction (at least I think so, not sure about retail but everything else would not be logical)

Another solution would be making mobs only aggro towards / vehicles attackable for players IF an additional check that would have to be always executed returns that the faction of the controling player is hostile. I guess this would function the same but just be much more complicated so yeah ... not sure about it ;)
blackdragon145
blackdragon145 commented on 10 Nov 2011

I will script the entire DK starting zone when I will be done with the setup of Project Sanctum.

P.S: this is not a bug, just a missing script.
MesoX
MesoX commented on 15 Nov 2011

Well basically it is a bug. I see 2 possible reasons: those vehicles has bad faction generally, so it's needed to update database (I can try to track real factions from some of my 3.3.5a sniffs) or vehicle should get owner's faction as Phi92 already wrote here. Would be nice to have some answer from dfighter, as he created the whole vehicle system for ArcEmu.
Phi92
Phi92 commented on 15 Nov 2011

It's just the question how the thing is handled on retail, the horses are certainly not unfriendly to either Death's Breach or Havenshire, but also I am pretty sure that on retail you will get into trouble in Havenshire even if your on a friendly horse, this is why I would believe it is the best way to adjust faction of a vehicle to its owner

It would also safe you and everyone from WhyDB, a lot of effort and time ;)
Laszlo Kis-Adam
dfighter1985 commented on 23 Jan 2012

I have no idea if they change faction or not, someone has to figure this out.
I do have some logs about the DK starting zone myself too tho, I might take a look eventually.

**Comment by Zyres** [comment]
Main issue was fixed in 1ff12002f089db08e3f24b85ad62287f77e11407
