### ISSUE TITLE
Worldserver Crash

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#714]
Worldserver Crashes when the Scripts Folder is not existant:  

Steps to Reproduce:
1. Delete The Scripts Folder
2. Start the Server

**Version**: ALL?

**AscEmu hash/commit**:  971ac8bc4df2367521da0bda76a83cffe7cbed14

**Operating system**:  Windows

**Comment by schnek** [comment]
most likely it `sSpellMgr.loadSpellScripts();`
if return `SpellHandlers.dll` crashes won't be.
