### ISSUE TITLE
Quest: 1719 The affray Bugged

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#73]
Quest ID: 1719

Kill Big Will (id = 6238), then speak to Klannoc Macleod (id = 6236) on Fray Island.

```
Big Will slain
Step on the grate to begin the Affray Description: If you want to learn from me, then you must first pass The Affray. It is a challenge we on Fray Island like to offer rising warriors who think they're tough, and if you can pass this test then I'll know you are.
```

To begin, walk into the middle of that crowd yonder and step on the grate. That'll tell Twiggy Flathead you're ready, and he'll send challengers against you.

Beat all the challengers and he'll call out Big Will. Kill Big Will, and return to me in the time we allow.
Rewards
You will learn:
Berserker Stance (id = 2458)
You will also receive: (or 19 84 50 if completed at level 90)

http://www.wowhead.com/quest=1719/the-affray

**Comment by Zyres** [comment]
Video: https://www.youtube.com/watch?v=41GiF6D-VCA

**Comment by Zyres** [comment]
hmmm
