### ISSUE TITLE
Error loading table spell_custom_override

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#735]
**Description**:  

**Steps to reproduce the problem**: 
1. start error WorldServer.exe

- [ ] spell_custom_override

`
Sql query failed due to [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', assign_on_target_flag, assign_self_cast_only, assign_c_is_flag, proc_flags, pr' at line 1], Query: [SELECT spell_id, rank, assign_on_target_flag, assign_self_cast_only, assign_c_is_flag, proc_flags, proc_target_selfs, proc_chance, proc_charges, proc_interval, proc_effect_trigger_spell_0, proc_effect_trigger_spell_1, proc_effect_trigger_spell_2 FROM spell_custom_override]`

**Version**: TBC,  WotLK,

**Comment by Zyres** [comment]
which version?

**Comment by schnek** [comment]
3.x.x 4.x.x

**Comment by Zyres** [comment]
Tested with latest dev version with a new db. I can't reproduce the issue.

**Comment by schnek** [comment]
I reproduce the issue on tbc
![image](https://user-images.githubusercontent.com/1216225/81121613-d358b200-8f37-11ea-953b-5235d4776b98.png)

**Comment by schnek** [comment]
fix https://github.com/AscEmu/AscEmu/commit/169a01907b3f3ba5264a02b53d184a3425525e05
