### ISSUE TITLE
👾 [Bug Report] Transport do not work.

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#754]
**Description**: 

**Steps to reproduce the problem**: 
1. Not one of the tested ships is working.
![image](https://user-images.githubusercontent.com/1216225/81121387-4a417b00-8f37-11ea-9650-c30a18a0c13b.png)
![image](https://user-images.githubusercontent.com/1216225/81121394-52011f80-8f37-11ea-8e28-ba28ed19610a.png)
![image](https://user-images.githubusercontent.com/1216225/81121503-91c80700-8f37-11ea-9230-e7c6885d1320.png)

**Expansion version**: 

All version

**AscEmu hash/commit**: 

last dev

**Operating system**: 

Platform: Windows

**Comment by Zyres** [comment]
See #516
