### ISSUE TITLE
👾 [Bug Report]stacking classes on the target is doubled for each spell

### ISSUE THREAD

**Issue by pshamy** [AscEmu/AscEmu#760]
**Description**: 

sorry i compiled the source for tbc correctly.
now i'm having a little auras problem stacking,
I have warriors I use sunder armor for each warrio increases 5 + 5 total of 10 sunder
i think it's problem of the unit.cpp
I am here because I like to work with lua
but the stacking classes on the target is doubled for each spell of the same class as that error

something similar was fixed in another competition https://github.com/cmangos/issues/issues/388

**Steps to reproduce the problem**: 
the truth is that the Unit.cpp is somewhat wrong the stackable aura of the same name for each character of the same class increases x5 for each of them

    - Patch 2.4.3 - TBC

**Comment by Zyres** [comment]
@Appled can you check this out?

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/a435087cb38b00c6523ed07d4c44ea7c1515b600
