### ISSUE TITLE
👾 [Bug Report] quest system the inability to track the quest and pass it.

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#761]
**Description**: 

the quest system has stopped working correctly

**Steps to reproduce the problem**: 
1. start quest.
![image](https://user-images.githubusercontent.com/1216225/83295910-7085ce00-a1f8-11ea-8fc2-e2b25e4369b6.png)
2. quest is not in the quest log.
![image](https://user-images.githubusercontent.com/1216225/83296075-c2c6ef00-a1f8-11ea-88a9-c8f4c8fd49bd.png)
3. lack of taskbar.
![image](https://user-images.githubusercontent.com/1216225/83296154-ed18ac80-a1f8-11ea-8471-8a6043bd4763.png)
4.incorrect completion of quests.
![image](https://user-images.githubusercontent.com/1216225/83296307-408afa80-a1f9-11ea-8909-f1ab09f15a64.png)

**Expansion version**: 

Patch 3.3.5 - WoTLK

**AscEmu hash/commit**: 

last dev

**Operating system**: 

Platform: Windows

**Comment by Zyres** [comment]
questlog works for bc and cata.

**Comment by schnek** [comment]
https://github.com/AscEmu/AscEmu/issues/761
