### ISSUE TITLE
Nordend Ghost Mount when dead

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#77]
In Nordend you can fly when you are dead on a ghost mount (Spell 55164)

In  Wrath of the Lich King, when dying in Icecrown or Storm Peaks, players will have access to a spectral gryphon upon death to retrieve their corpse because you cannot always climb the mountainous regions. However, since Night Elves are wisps they don't have the gryphon, they can simply fly.

**Comment by Zyres** [comment]
How should it work?
You are dead -> gets teleported to graveyard -> get mounted automatically?

**Comment by aaron02** [comment]
Yes you get mounted automatically

**Comment by Zyres** [comment]
Can you accept the resurrection after claiming your corpse?
If not, please create a new issue...

**Comment by aaron02** [comment]
yes you can accept resurrection after claiming corpse
