### ISSUE TITLE
⚙ [Support Request] Outdated info in the Windows guide?

### ISSUE THREAD

**Issue by mwaning** [AscEmu/AscEmu#780]
**Description**: 
Hi, I followed the steps described in the Windows getting started guide, but at step 2 under CMake Precompile I get stuck. Could it be that the guide is outdated, or am I making some stupid mistake?
It says "Error in configuration process; project files may be invalid"
It's probably the easiest to show it to you in a screenshot
https://i.imgur.com/ioBjTtZ.png

**Steps to reproduce**: 
1. Following the steps in https://ascemu.github.io/Wiki/docs/installation/windows/
2. Getting stuck at CMake Precompile step 2

**Expansion version**:
    Specify version - is required:
    - Patch 3.3.5 - WoTLK

**AscEmu hash/commit**: 
Not sure where to find that

**Operating system**: <!-- (Add / Remove lines if necessary)
    Specify the operating system - is required:
    - Platform: Windows 10

**Comment by Zyres** [comment]
Did you test it with Win32 or leaving it blank?

**Comment by schnek** [comment]
@mwaning hi guide is relevant. Сmake version 3.17.2 compiles without problems. 
check if visual studio is worth it [Visual Studio](https://visualstudio.microsoft.com/ru/downloads/).

**Comment by mwaning** [comment]
Ah darn, I already had Visual Studio installed on my PC, so I assumed this step was alright. But after reinstalling it with Desktop Development with C++ enabled it indeed does suddenly work.
Sorry guys... Thanks for the quick helpful replies though.
