### ISSUE TITLE
👾 [Bug Report] "Make this inn your home" not work. 

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#781]
**Description**: 

"Make this inn your home" not work. When using the stone, it returns to the starting location (the place of the first appearance of the character). Not one of the proven Innkeepers not works.
![image](https://user-images.githubusercontent.com/1216225/84600623-62d07980-ae83-11ea-94d0-eb74dea72145.png)
![image](https://user-images.githubusercontent.com/1216225/84600628-682dc400-ae83-11ea-961a-8238faeba63d.png)

**Expansion version**: 

all version 

**AscEmu hash/commit**: 

last dev

**Operating system**: 

Platform: Windows

**Comment by Zyres** [comment]
[ERROR] Spell::SpellEffectCreateItem Spell 3286 (Bind) has a create item effect but no item count to add, Spell needs to be fixed! Count overriden to 1.
@Appled

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/6f0435069e8d8594bb71dea27c8c1f401560c373
