### ISSUE TITLE
👾 [Bug Report] New characters are missing reputations

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#799]
**Description**: 
New characters have no reputations

**Steps to reproduce the problem**: 
1. Create new character
2. Login
3. Look at the empty reputation tab

**Expansion version**:
All versions

**AscEmu hash/commit**: 
af4dfefe489c113f718972dfa1e59dcb51aa4e0f

**Comment by schnek** [comment]
fix https://github.com/AscEmu/AscEmu/pull/801
