### ISSUE TITLE
Vendorspawns for Arena Seasons

### ISSUE THREAD

**Issue by DankoDJ** [AscEmu/AscEmu#80]
Since we move to automatic event manager, all (most) events are controlled.
We move all (most) old sql/lua data to core/db.

All eventspawns: DB event_creature_spawns / event_gameobject_spawns
All wps (they are grouped for these "static" spawns): creature_waypoint_manual (linked by wpgroup to spawn).

Please check out our wiki-pages for mor information.

- [x] event 57 (Arena Season 5)
- [x] event 58 (Arena Season 6)
- [x] event 59 (Arena Season 7)
- [x] event 60 (Arena Season 8)

The event_entry can be found in event_names.

**Comment by DankoDJ** [comment]
Arena Season are controlled by config (sWorld.Arena_Season)
Season 8 = Event 60
Season 7 = Event 59
Season 6 = Event 58
Season 5 = Event 57

**Comment by Evairfairy** [comment]
I'm currently only adding arena seasons 5 through 8, as seasons 1 and 2 are missing from the database

**Comment by DankoDJ** [comment]
Spawns for 1 - 4 are really old (Season 5 info: Arena Season 5 began on December 16th, 2008[1] and closed on April 14th, 2009.).
I think 1 - 4 is not needed... (only someone plan to development 2.4.3 or vanilla... o.O)

**Comment by Zyres** [comment]
Closed with: https://github.com/AscEmu/AscEmu/commit/3ca3ea5969dab39f26b82d61143cedb1cc5859e7
Thanks to Evairtairy
