### ISSUE TITLE
👾 [Bug Report] no NPC on version greater than cata

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#808]
**Description**: 

Description: There is no settlement of all mobs in Northrend, Outland, the starting islands of the Blood Elves and Draenei.

**Steps to reproduce the problem**: 
![image](https://user-images.githubusercontent.com/1216225/96337694-8a358e00-1091-11eb-9302-fe96e897a4f7.png)
![image](https://user-images.githubusercontent.com/1216225/96337704-93265f80-1091-11eb-8d01-205247037554.png)
![image](https://user-images.githubusercontent.com/1216225/96337724-ad603d80-1091-11eb-8d31-75b330cfc4b9.png)

**Expansion version**: 
Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 
last dev

**Operating system**: 
Platform: Windows

**Comment by Zyres** [comment]
Open issues for a specific zone/area from now on. We have to adjust these spawn data, WIP
