### ISSUE TITLE
👾 [Bug Report] WorldRunnable Update

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#813]
**InWorldRunnable.cpp at threadRunner is a diff time generatet to update different things and on my machine this diff time is always 0, this makes certain things dont update, for example lfg queue update**: 

**Expansion version**: 

**5e4ae77 (newest master)**: 

**Operating system**:

**Comment by Zyres** [comment]
void Transporter::Update() does not work too, at least it seems to be a timer problem.
