### ISSUE TITLE
💡 [Feature Request] CellLoading Distance in Instances

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#817]
**Description**: 
Increase CellLoading distance in Instances, for example in ICC when u stand at Lady Deathwisper the entrance door of the room despawns seems not no be a good idea. Maybe Load all Cells in Instances or up to 4 cells

**Comment by Appled** [comment]
I'd load all cells in instances and battlegrounds.
@Zyres thoughts?

**Comment by Zyres** [comment]
That would be okay for me.

**Comment by aaron02** [comment]
maybe also att the ability to load all cells in a specific area/zone would be good for open pvp at wintergrasp

**Comment by Razfury** [comment]
- [ ] The Burning Crusade
- [x] Wrath of Lich King ( #945 )
- [ ] Cataclysm
- [ ] Mists of Pandaria

**Comment by Appled** [comment]
Implemented in https://github.com/AscEmu/AscEmu/commit/d1f180970f80f00c961f5a96349e33af98728bc6
