### ISSUE TITLE
Prevent escorts running back to home position

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#82]
Currently if an creature (with waypoints) leaving a comabt it is running back to spawn position.
This is not the way escorts should work.
See AIInterface and (STATE_EVADE).
Use a new MovementType (MOVEMENTTYPE_ESCORT) to handle it.

**Comment by RAlexis** [comment]
TBH, escorts/waypoints should be rewritten.

**Comment by DankoDJ** [comment]
@RAlexis Your sentence match to every part of this framework.

**Comment by RAlexis** [comment]
Not really, but OK.

**Comment by RAlexis** [comment]
Not really, but OK.
