### ISSUE TITLE
💡 [Feature Request] utf8 support messages "Logger" in console.

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#831]
**Description**:  add utf8 support 
how does it look now

![image](https://user-images.githubusercontent.com/1216225/102540665-6659ed00-40c0-11eb-8ccd-3fb355e84058.png)

Player ╨╜╨░╨║╨░╨╗╨╕╨▓╨░╤В╨╡╨╗╤М logged in.
Player ╨╜╨░╨║╨░╨╗╨╕╨▓╨░╤В╨╡╨╗╤М gets prepared for login.
Sent initial logon packets for ╨╜╨░╨║╨░╨╗╨╕╨▓╨░╤В╨╡╨╗╤М.
Received CMSG_NAME_QUERY for:  ╨╜╨░╨║╨░╨╗╨╕╨▓╨░╤В╨╡╨╗╤М.

from test .a Привет, мир! (Hello, world!)

non-latin characters are not displayed (displayed incorrectly)

**Comment by Zyres** [comment]
I need a client in you language to check out the problem...

**Comment by schnek** [comment]
then you need a _russian client_ 😉

**Comment by schnek** [comment]
due to the fact that there is no native utf8 support in the console, it needs to be added as in the database.
in c++ 20 the parameters we need appeared. (u8string, char8_t)

**Comment by schnek** [comment]
Fix https://github.com/AscEmu/AscEmu/pull/1134
