### ISSUE TITLE
👾 [Bug Report] Skills/Spells

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#834]
**Description**: 
I tried to learn axe (proficiency) on cata without a possitive result.
It seems it does not work as intended.

**Steps to reproduce the problem**: 
1.  try to learn axe as shaman
2. you are still not allowed to wear axes

`.char learn 196
for one handed
.char learn 202
for two handed`

**Expansion version**: 
    - Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 
https://github.com/AscEmu/AscEmu/commit/bbac7a8606a67475d72eabde7ac04f96a31e92a5

**Comment by aaron02** [comment]
in cataclysm you have all weapon skills by default ( only for your class ) weapon trainers where removed in 4.0.1

**Comment by Zyres** [comment]
Closed clientside restriction
