### ISSUE TITLE
👾 [Bug Report] Warsong Gulch, you cannot pick up the flag

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#843]
**Description**: when playing Warsong Gulch, you cannot pick up the flag

**Steps to reproduce the problem**: 
1.  when playing Warsong Gulch, you cannot pick up the flag
![image](https://user-images.githubusercontent.com/1216225/104217260-3d711180-544c-11eb-89d7-faff33f4b1b7.png)

**Expansion version**: 

Patch 3.3.5 - WoTLK

**AscEmu hash/commit**: 

last dev

**Operating system**: 

Platform: Windows

**Comment by Zyres** [comment]
@Appled Spell related?

**Comment by Appled** [comment]
I've seen that many gameobjects have flag 4 ("not targetable") set in database even when they should not have that, i.e loot chests, quest items, quest givers, so I wouldn't be surprised if that is the case here too.

However, if that's not the case, then the object is missing a script to cast the proper spells.

**Comment by schnek** [comment]
```
void Aura::SpellAuraModEffectImmunity(AuraEffectModifier* /*aurEff*/, bool apply)
{
    ....

    if (m_spellInfo->getId() == 23333 || m_spellInfo->getId() == 23335 || m_spellInfo->getId() == 34976)
```

there is a function but it does not work...

**Comment by Appled** [comment]
I don't get any error messages and I didn't use GM commands to enter Warsong Gulch. Nothing happens when you click on the flag because it has no code in it https://github.com/AscEmu/AscEmu/blob/develop/src/world/Objects/GameObject.cpp#L1593

**Comment by Appled** [comment]
I will fix this later tonight

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/eed9b57cf9dff421f6cccc41a1ed237187270982
