### ISSUE TITLE
👾 [Bug Report] impossibility to create class / race

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#852]
**Description**:   impossibility to create class / race

![image](https://user-images.githubusercontent.com/1216225/114207929-9413bc00-9965-11eb-9e6b-ba593176a75a.png)

**Steps to reproduce the problem**: 
1. create a marked race
2. try to enter the world
3. 
4.

**Expansion version**: 

~~Patch 3.3.5 - WoTLK~~
Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 

last dev

**Operating system**:

**Comment by Zyres** [comment]
@schnek is it related only to race or race-class combination?

**Comment by Zyres** [comment]
Works fine for me on wotlk
![image](https://user-images.githubusercontent.com/8825392/115952518-adc90d80-a4e6-11eb-966f-ba65f9362516.png)

**Comment by Zyres** [comment]
on cata I have a problem with Draenei Mage. Please verify class/race combinations:
![image](https://user-images.githubusercontent.com/8825392/115952724-faf9af00-a4e7-11eb-84cf-a66dfd1ac71e.png)

**Comment by Zyres** [comment]
@schnek: can you test alls races/classes and provide a list (race/classids) (maybe wotlk too)

**Comment by schnek** [comment]
i will check all classes / races.

**Comment by Zyres** [comment]
Works now for me with the latest dev version (pushed right now)

**Comment by Zyres** [comment]
@schnek please retest with latest dev ;-) if it works, close the issue

**Comment by schnek** [comment]
![image](https://user-images.githubusercontent.com/1216225/117132216-2ebbbb00-adab-11eb-8ff8-e9ea57117b33.png)
