### ISSUE TITLE
👾 [Bug Report] Creature Say

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#854]
**Description**: 
Creatures no Longer have theyre text in the chat. For example Stormwind bread seller, npcs with a yell at attack.
 go ingame select a npc and type:

testet on latest develop branch

.npc say hi

**Expansion version**: 

    - Patch 3.3.5 - WoTLK

**Comment by Appled** [comment]
Confirmed on c5b85481836f3931c7a2e36c759b50172f485eaa, SMSG_MESSAGECHAT is not sent at all according to console output. Player chat works though. On newer develop .npc say is also broken, says "This command requires a selected a creature". Seems like in ChatHandler::GetSelectedCreature the getTargetGuid() is giving wrong guid?

**Comment by aaron02** [comment]
also creatures cant be gossips or vendors now not working at all

**Comment by Appled** [comment]
@Zyres the guid issue seems to be fixed but the original issue still persists.

**Comment by aaron02** [comment]
smsgmessagechat seems to dont get build correctly for creatures

**Comment by aaron02** [comment]
not working for scripts but fixed for the ingame command

**Comment by aaron02** [comment]
added creature part to PR #857
