### ISSUE TITLE
👾 [Bug Report] chat not work

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#855]
**Description**: 

**Steps to reproduce the problem**: 
1.  create ~~Tauren/Priest/Paladin~~
1.2. ~~Troll/Druid/Warlock~~
1.3 ~~Undead/Hunter~~
1.4. ~~Orc/Mage~~
2. enter cheat commands or just say hi
test: .char set speed (not work)
.kill (work)

**Expansion version**: 

Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 

latest develop

**Operating system**: 

Platform: Windows

**Comment by Appled** [comment]
Can you retest with the new develop commit https://github.com/AscEmu/AscEmu/commit/51beece87c9a245b45e69a3bbcc5fc105e8daff7 ?

**Comment by Appled** [comment]
Test again 😃

**Comment by schnek** [comment]
![image](https://user-images.githubusercontent.com/1216225/116792495-9fbc5380-aac9-11eb-8f41-4ba347e4c956.png)
