### ISSUE TITLE
👾 [Bug Report] Crash when loading corpses in worldserver startup

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#878]
**Description**: 
Server crashes in Corpse::setCorpseDataFromDbString when loading corpses
![Callstack](https://i.ibb.co/f8cFcMP/crash.jpg)

**Steps to reproduce the problem**: 
1. Kill your character and logout
2. Close server and restart it
3. Look at the crash

**Expansion version**: 
All

**AscEmu hash/commit**: 
https://github.com/AscEmu/AscEmu/commit/e174571d954cad00fc2254061af81e30bb15484e

**Comment by Zyres** [comment]
Can't reproduce the crash, tested on WotLK
