### ISSUE TITLE
👾 [Bug Report] Some WoWData fields / former UpdateFields are not used correctly

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#889]
**Description**: 
Like the title says some WoWData fields or formerly UpdateFields are not used correctly. 
Let's use one gameobject field for example as I noticed this issue there. In UpdateFields.h (which is now removed from source) if we look at GAMEOBJECT_DYNAMIC field, it says:
`GAMEOBJECT_DYNAMIC                               = OBJECT_END + 0x0008, // Size: 1, Type: TWO_SHORT, Flags: DYNAMIC`

Note how it says TWO_SHORT for type and not INT. Normal uint32_t field would have:
`GAMEOBJECT_FLAGS                                 = OBJECT_END + 0x0003, // Size: 1, Type: INT, Flags: PUBLIC`

Apparently fields that have type TWO_SHORT should have low and high uint16_t field in them. At the moment we handle all(?) TWO_SHORT fields as regular uint32_t fields.

As @aaron02 was working on transports, he noticed how this GAMEOBJECT_DYNAMIC field is used in other emulators. For example here from mangos:
```
SetUInt16Value(GAMEOBJECT_DYNAMIC, 0, GO_DYNFLAG_LO_STOPPED);
SetUInt16Value(GAMEOBJECT_DYNAMIC, 1, pathProgress % GetPeriod());
```

As we can see, the low field in GAMEOBJECT_DYNAMIC is used for dynamic flag and the high field is used for transport path progress. Non-transporter objects don't touch that high value as far as I know.

How do they update uint32_t field to have two uint16_t fields? Again, here's code from mangos:

```
void Object::SetUInt16Value(uint16 index, uint8 offset, uint16 value)
{
    MANGOS_ASSERT(index < m_valuesCount || PrintIndexError(index, true));

    if (offset > 2)
    {
        sLog.outError("Object::SetUInt16Value: wrong offset %u", offset);
        return;
    }

    if (uint16(m_uint32Values[index] >> (offset * 16)) != value)
    {
        m_uint32Values[index] &= ~uint32(uint32(0xFFFF) << (offset * 16));
        m_uint32Values[index] |= uint32(uint32(value) << (offset * 16));
        m_changedValues[index] = true;
        MarkForClientUpdate();
    }
}
```

Now, this gameobject field is not the only TWO_SHORT field. Here are links to UpdateFields.h for every expansion before they were removed from source, if you're curious which fields use this type:
Classic: https://github.com/AscEmu/AscEmu/blob/e4d394502782fac0804cf6f55b24761965ecada7/src/world/GameClassic/UpdateFields.h
TBC: https://github.com/AscEmu/AscEmu/blob/e4d394502782fac0804cf6f55b24761965ecada7/src/world/GameTBC/UpdateFields.h
WotLK: https://github.com/AscEmu/AscEmu/blob/e4d394502782fac0804cf6f55b24761965ecada7/src/world/GameWotLK/UpdateFields.h
Cata: https://github.com/AscEmu/AscEmu/blob/e4d394502782fac0804cf6f55b24761965ecada7/src/world/GameCata/UpdateFields.h
Mop: https://github.com/AscEmu/AscEmu/blob/e4d394502782fac0804cf6f55b24761965ecada7/src/world/GameMop/UpdateFields.h

It is also possible for some fields, which have these two uint16_t fields, that only the lower field is used.

Fields to implement:
classic:
- [x] unit_training_points
- [x] unit_field_attack_power_mods
- [x] unit_field_ranged_attack_power_mods
- [x] player_visible_item_X_properties
- [x] player_skill_info_1_1

tbc:
- [x] unit_training_points
- [x] unit_field_attack_power_mods
- [x] unit_field_ranged_attack_power_mods
- [x] player_visible_item_X_properties
- [x] player_skill_info_1_1
- [x] player_field_kills

wotlk:
- [x] unit_field_attack_power_mods
- [x] unit_field_ranged_attack_power_mods
- [x] player_skill_info_1_1
- [x] player_field_kills
- [x] item_field_enchantment_X_3
- [x] player_quest_log_X_3
- [x] player_visible_item_X_enchantment
- [x] gameobject_dynamic

cata:
- [x] unit_field_attack_power_mod_pos
- [x] unit_field_attack_power_mod_neg
- [x] unit_field_ranged_attack_power_mod_pos
- [x] unit_field_ranged_attack_power_mod_neg
- [x] item_field_enchantment_X_3
- [x] player_quest_log_X_3
- [x] player_visible_item_X_enchantment
- [x] player_skill_lineid_0
- [x] player_skill_step_0
- [x] player_skill_rank_0
- [x] player_skill_max_rank_0
- [x] player_skill_modifier_0
- [x] player_skill_talent_0
- [x] player_field_kills
- [x] gameobject_dynamic

mop:
- [x] unit_field_attack_power_mod_pos
- [x] unit_field_attack_power_mod_neg
- [x] unit_field_ranged_attack_power_mod_pos
- [x] unit_field_ranged_attack_power_mod_neg
- [x] item_field_enchantment_X_3
- [x] player_quest_log_X_3
- [x] player_visible_item_X_enchantment
- [ ] player_skill_lineid_0
- [ ] player_skill_step_0
- [ ] player_skill_rank_0
- [ ] player_skill_starting_ranks_0
- [ ] player_skill_max_rank_0
- [ ] player_skill_modifier_0
- [ ] player_skill_talent_0
- [x] player_field_kills

**Comment by Evairfairy** [comment]
For an example of how we set high/low fields in AscEmu, look at the WoWObject GUID struct. https://github.com/AscEmu/AscEmu/blob/master/src/world/Data/WoWObject.hpp#L23

**Comment by Zyres** [comment]
Hey there, just messed arounf with a little testcode to sort some stuff out:

`
void Master::PrintBanner()
{
    sLogger.file(AscEmu::Logging::Severity::FAILURE, AscEmu::Logging::MessageType::MINOR, "<< AscEmu %s/%s-%s (%s) :: World Server >>", BUILD_HASH_STR, CONFIG, PLATFORM_TEXT, ARCH);
    sLogger.file(AscEmu::Logging::Severity::FAILURE, AscEmu::Logging::MessageType::MINOR, "========================================================");

    // testcode offsets
    {
        //////////////////////////////////////////////////////////////////////////////////////////
        // mangos like byteshift
        // set low
        uint32_t field = 0;
        uint32_t offset = 0;
        uint16_t value = 15;

        field &= ~uint32(uint32(0xFFFF) << (offset * 16));
        field |= uint32(uint32(value) << (offset * 16));

        // set high
        offset = 1;
        value = 40;

        field &= ~uint32(uint32(0xFFFF) << (offset * 16));
        field |= uint32(uint32(value) << (offset * 16));

        std::cout << "TEST MANGOS byteshift two shorts: " << field << std::endl;

        //////////////////////////////////////////////////////////////////////////////////////////
        // ascemu like byteshift
        union
        {
            struct
            {
                uint16_t low;
                uint16_t high;
            } field_parts;
            uint32_t dynamic_field;
        };

        // set low
        value = 15;
        *reinterpret_cast<uint16_t*>(&field_parts) = value;

        // set high
        value = 40;
        *(reinterpret_cast<uint16_t*>(&field_parts) + 1) = value;

        std::cout << "TEST ASCEMU byteshift two shorts: " << dynamic_field << std::endl;
        
    }
}
`

![image](https://user-images.githubusercontent.com/8825392/123505157-bdd3a980-d65d-11eb-8ee8-3e62c0168d91.png)

**Comment by Zyres** [comment]
The following list includes "TWO SHORT" fields but never used as TWO SHORTS
- unit_training_points
- ...

**Comment by Zyres** [comment]
@Appled / @aaron02 
I'm currently struggling with skill_info. I've come up with the following fields:
   // 1 uint32_t
    // 1.1 - uint16_t id
    // 1.2 - uint16_t step
    // 2 uint32_t
    // 2.1 - uint16_t current_value
    // 2.2 - uint16_t max_value
    // 3 uint32_t
    // 3.1 - int16_t bonus_temporary
    // 3.2 - int16_t bonus_permanent

Any thoughts/verification?

**Comment by aaron02** [comment]
this should be correct yes

**Comment by Appled** [comment]
Not sure really but they look reasonable

**Comment by Zyres** [comment]
Done as much as it is testable (mop can't be tested....)
