### ISSUE TITLE
Quest Issues (RAlexis List)

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#89]
# Quest Issues

## Spawning npc or gob
- [x] quest 11613 - spawn - 25521, 25522
- [x] quest 11619 - spawn 26449 (in cave)
- [x] quest 11620 - spawn 25450
- [x] quest 11625 - spawn 26451
- [x] quest 11626 - spawn 26452 (under the iceberg)
- [x] quest 11908 - spawn object 188120
- [x] quest 11872 - spawn 25800 (underwater)
- [x] quest 11968 - spawn 26266
- [x] quest 11956 - spawn npc: 26225
- [x] quest 11942 - spawn npc (en kilah): 25392, 26076, 26073

## Gossip
- [x] quest 11708 - tell story: http://www.wowhead.com/quest=11708 (script)

## GO quest_starter
- [x] object 187851 - starts quest 11920

All other quests on this list should pe reported in detail (one issue for one quest)

Ref: https://github.com/DarkAngel39/ArcDB/issues/1

**Comment by DankoDJ** [comment]
quest 11708 - tell story: http://www.wowhead.com/quest=11708 (script) closed in:
https://github.com/AscEmu/AscEmu/commit/110d299245747d42605f3d596e7aad3189771a43

**Comment by Zyres** [comment]
object 187851 - starts quest 11920
starts quest correctly

**Comment by Zyres** [comment]
Closed: See also #90, #91, #92, #93, #94, #95
