### ISSUE TITLE
👾 [Bug Report] Client Freeze when turning in Quests

### ISSUE THREAD

**Issue by shagu** [AscEmu/AscEmu#895]
**Description**: 
When turning in quests on the TBC flavor, the Gameclient will freeze.

**Steps to reproduce the problem**: 
1. Launch game with `-opengl` parameter
2. Create Orc
2. Take quest: "Your Place In The World"
3. Turn in quest at Gornek
4. Client Freezes/Crashes

Doing the same on OregonCore, mangosone and cmangos-tbc does **not** crash the client. So even if it's some weird client issue, it is somehow connected to the server.

**Expansion version**:
    - Patch 2.4.3 - TBC

**AscEmu hash/commit**: 
    - server: 2076dbd75696a44e44f029f85b978e2d1af37e1a (develop)
    - database: 169446947460e094ae33bfe0d3c5b9b05990b066 (master)

**Operating system**:
    - Platform: Linux

**Comment by shagu** [comment]
If you relog between step 2. and 3., the client won't freeze.

**Comment by shagu** [comment]
After having the issue 4 times in a row, I'm no longer able to reproduce it (tried it again 10 times) :/

**Comment by shagu** [comment]
It only freezes on AscEmu when the client is started with the `-opengl` parameter.
However, using the same client, with the same parameter on both `mangosone` and `cmangos-tbc` does not crash the client.

Maybe some sort of wrong spell/animation on quest-completion is sent to the client, that can't be displayed on TBC and only crashes in opengl mode? Just guessing..

Would be great if someone could give it a test on windows too.
Please close again if you think this is irrelevant.

**Comment by Zyres** [comment]
Okay, so I tested this with 678b03f29f47af8e19ce0ec4a008932d1c48b371 (latest dev).
No freeze on turning in the quest, but nearby is something possibly related to the opengl parameter.
![image](https://user-images.githubusercontent.com/8825392/123504296-94fce580-d658-11eb-90a3-5a52584c9bf7.png)

@shagu Can you try to remove this guy (spawnid 25491) and retest it again?

I've created an orc hunter, which class do you use?

**Comment by Zyres** [comment]
some feedback?

**Comment by shagu** [comment]
> some feedback?

Sorry, I don't have those things set up anymore :(

> I've created an orc hunter, which class do you use?

I've been an orc warrior

**Comment by Zyres** [comment]
Not reproduceable on [3d72453](https://github.com/AscEmu/AscEmu/commit/3d72453b17b7d77e48771c5477eeadb7476dc028), closed since OP no longer available to retest.
