### ISSUE TITLE
👾 [Bug Report] Client freeze, when distributing talent points

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#896]
**Description**: 

When confirming the distribution of points, the client freezes.
When re-entering the character, the client hangs at the loading stage.
Relevant for almost all specs of all classes.

Otherwise, a bug appears in the frost branch magician - When confirming the distribution of talent points, the client does not freeze, but when you exit the game world, the bug appears, when entering a character, the client does not hang.
![image](https://user-images.githubusercontent.com/1216225/121933062-42652480-cd4e-11eb-8e3f-bff53a1da503.png)

**Expansion version**: 

Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 

dev latest

**Operating system**: 

Windows
MacOS Mojave (@armm77, thank you)

**Comment by armm77** [comment]
Confirmed
Expansion version:
Patch 4.3.4 - Cataclysm

AscEmu hash/commit:
dev latest

Operating system: 
MacOS Mojave

**Comment by aaron02** [comment]
after some tests it dont seems like the error is in the learn talents packet. because even after a restart the client freezes at login to world.

**Comment by aaron02** [comment]
sendSpellModifierPacket is causing it after disabling this apcket it nomore crashed

**Comment by Appled** [comment]
Thanks for research @aaron02 😃 
I will look into this maybe tomorrow

**Comment by schnek** [comment]
#897 Fix
