### ISSUE TITLE
Vehicle Falling dmg

### ISSUE THREAD

**Issue by Tulba** [AscEmu/AscEmu#9]
If I enter a car and I road though down a road 
(ex. scarlet crusade zone: from the mine's car to the beach)
and I leave the car, I receive falling damage even if I didn't fall anywhere and I die.
dberga

**Comment by Zyres** [comment]
Tested with rev: bc85d96ff42ef7b276d35e15a6f81569013fb92d

If you falling down while controlling a vehicle, the vehicle gets damaged. Leaving the vehicle while driving to a lower area workis fine.
