### ISSUE TITLE
👾 [Bug Report] Stats Issue?

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#906]
**Description**: 
I noticed some huge stat differences to retail. I startet playing tbc and wantet to test some mechanics ( i know asc has not all perfect but should do the trick for some stuff ) is this realy that much off here? leftside is retail tbc noe. i have some gems in my gear but that shouldnt make that much difference

items used:

28593
28516
27803
27892
25819
28502
28189
28518
28566
23518
30641
31078
29277
24376
28042
27887

![image](https://user-images.githubusercontent.com/1266630/125851876-fac67d86-8dd3-4dba-807d-55933bb84816.png)

**Comment by Zyres** [comment]
Some items changed, here is a vid about items and stat changes: https://www.youtube.com/watch?v=YAo_jBppxKc

**Comment by dio85** [comment]
if my memory good, all item stat storet at dbc file. so if you extract the correct file, that stat good. i m correct?

**Comment by aaron02** [comment]
the items stats are correct i mean defense parry block...

**Comment by aaron02** [comment]
parry cannot be 0.5 because i have 5 points in parry so i should have +5%

**Comment by aaron02** [comment]
also with that same gear all stats are the same something gets added calculatet wrong

**Comment by Zyres** [comment]
so the items are correct in our db?

**Comment by aaron02** [comment]
the items are correct yeah

**Comment by Zyres** [comment]
So, I remember that we changed the calculation of many things during backporting from wotlk (tbc miss some dbc values for the wotlk calculation).
Idk if we had implemented a dummy value for that or not. If you find the calculation for it it should be easy to fix it 🤗

**Comment by schnek** [comment]
maybe this will help or speed up the process ^^ https://tbc.wowhead.com/guides/classic-the-burning-crusade-stats-overview

**Comment by aaron02** [comment]
i assume its also wrong for wotlk

**Comment by Appled** [comment]
The base stats (health, mana, str, agi, int etc etc) for all classes and for all levels are old guessed values, in wotlk too. The initial base stats for all race/class combinations could be retrieved from wowpedia, but stats per each level is harder to find out 😖

**Comment by Zyres** [comment]
I should know that but where do we define base stats per level?

**Comment by aaron02** [comment]
the instance should save only if you killed atleast 1 boss

**Comment by Appled** [comment]
@Zyres https://github.com/AscEmu/AscEmu/blob/master/src/world/Units/Stats.cpp#L366 and line 350

**Comment by Zyres** [comment]
Worked on it the entire day. I guess the values are pretty correct.
@aaron02 can you give us an example with identical stuff equipped (even gems) otherwise it will be impossible to check it out.

**Comment by aaron02** [comment]
i also testet it and noticed i dont had all skills fully up now its ok but u can block wihtout an shield on ascemu u have to have a shield equiped to be able to block

**Comment by Zyres** [comment]
... ok...
the blocking issue on tbc is another cup of coffee (idk how to retest it, you will always block/miss in a fight in bc right now). so closing this for now.

**Comment by aaron02** [comment]
meant in a another way the calculation dont calculates when no shield is equipped it stays at 0
