### ISSUE TITLE
👾 [Bug Report] Saved Instances

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#907]
**Description**: 
After a Instance gets Locked you should be able so see it in the raid tab at socials by pressing "Info"

![image](https://user-images.githubusercontent.com/1266630/126867331-c08270fa-62e2-47e2-b652-bf597200c51e.png)

**Steps to reproduce the problem**: 
1. Go into a Raid/Hero
2. Get The Instance Locked

**Comment by Zyres** [comment]
Done :-)

![image](https://user-images.githubusercontent.com/8825392/128612077-d910b543-b306-4523-a5a7-d865250bb6b8.png)

**Comment by aaron02** [comment]
it should only save a raid if you kill atleast 1 boss. On Retail it works as follow: You go into an instance/raid an id gets created on hat id no mos respawn in most cases there are some special circumstances like karazhan where all trash mobs are respawning on timers until you kill the corresponding boss. you can reset all instances/raids when they are not locked. A raid gets locked for all players if you kill a boss

**Comment by aaron02** [comment]
instances are also a thing to discuss because mob grouping is something we dont have and its just something lets say hacked. idk how blizz handles that case. but all mobs in instances are gruped together and if you pull 1 mob the full pack joins the fight. Even in some Instances in Hellfire Rampahrt (ZH) the full Pack respawns if u wipe with 1 mob still alive of the pack when wiping. In the Open world mobs dont aggro other mobs and in Instances all Pulled Mobs can Aggro other Mobs/Mobgroups when running close to them ( 10-15yard )
