### ISSUE TITLE
👾 [Bug Report] Not able to Learn Engeneering

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#908]
**Description**: 
Tried to learn Engeneering bot no matter what i do Trainer dont let me learn it. No other Proffessions learned.
maybe general issue dont Testet other Professions. Testet On WOTLK

    - Patch 1.12.1 - Classic ?
    - Patch 2.4.3 - TBC ?
    - Patch 3.3.5 - WoTLK x
    - Patch 4.3.4 - Cataclysm ?
    - Patch 5.4.8 - Mop ?

**Comment by Appled** [comment]
Does it happen with all engineering trainers or just with one specific trainer?

**Comment by aaron02** [comment]
i tried the on ein stormwind but shouldnt make a difference the spell is marked green but learning is greyed out

**Comment by aaron02** [comment]
Update i tried other race class combinations ( warlock and rogue humans ) they can learn professions. The Warrior Human cannot learn any Profession

**Comment by Zyres** [comment]
Encountered something similar. Tauren shamane, can't learn blacksmithing. It is red but I'm already level 20... I have no other professions learned...

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/543c466613f19df28b180d97a07da91dff577df5
