### ISSUE TITLE
⚙ [Support Request] update SkillTypes

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#917]
the question is where does the data come from 

> enum SkillTypes
> {
>     SKILL_TYPE_ATTRIBUTES           = 5,
>     SKILL_TYPE_WEAPON               = 6,
>     SKILL_TYPE_CLASS                = 7,
>     SKILL_TYPE_ARMOR                = 8,
>     SKILL_TYPE_SECONDARY            = 9,
>     SKILL_TYPE_LANGUAGE             = 10,
>     SKILL_TYPE_PROFESSION           = 11,
>     SKILL_TYPE_NA                   = 12
> };
>
 it seems wrong now

**Comment by Appled** [comment]
The values are from second column in SkillLine.dbc. I just checked them out and they are all correct from classic to mop.

**Comment by schnek** [comment]
a couple of values are still missing) -1 0 as an example
