### ISSUE TITLE
👾 [Bug Report] Creatures fly/disappear on evade (Cata)

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#923]
**Description**:  not abnormal behavior of npc when attacking

**Steps to reproduce the problem**: 
1. attack any npc
![image](https://user-images.githubusercontent.com/1216225/135125230-f992e4f7-fb9a-421f-85d0-ca22157e1007.png)

2. npc flies out of sight
![image](https://user-images.githubusercontent.com/1216225/135125429-1fa96054-ba10-4354-825a-d7a3284cceb5.png)

3. sometimes the server crashes because of this

**Expansion version**: 

    - Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**:  latest dev

**Operating system**: 

    - Platform: Linux
    - Platform: Windows

**Comment by Appled** [comment]
Disable pathfinding in world config and try again

**Comment by schnek** [comment]
most likely the problem is this. I will close it as I check.

**Comment by Appled** [comment]
Was the problem in pathfinding?

**Comment by schnek** [comment]
yes, problem in pathfinding

**Comment by Appled** [comment]
Alright, reopening then. @aaron02 should know why this is happening 😉

**Comment by aaron02** [comment]
not happening for me

**Comment by aaron02** [comment]
for me it is working fine pathfinding and collision enabled

**Comment by aaron02** [comment]
confirmed after 10 hours of mmaps building.... should be alot faster with a amd 5950x and 64 gb of ram -_-
it definitly worked before so we have to find out what changed

**Comment by aaron02** [comment]
fixed on my local repository i make an pr in the next days

**Comment by aaron02** [comment]
can you test again @schnek

**Comment by schnek** [comment]
Works for me. Might be worth checking out more on ships 🤞

**Comment by Zyres** [comment]
So if it works now, this could be closed @schnek

**Comment by schnek** [comment]
yes, this particular problem is solved, but mmaps does not work in some places.
