### ISSUE TITLE
👾 [Bug Report] Dungeon Finder does not work

### ISSUE THREAD

**Issue by Razfury** [AscEmu/AscEmu#927]
Hello, in the past we have had some issues on our parts but however as times change i've decided to close my other projects and help with this one as it is unique with multiversion support.

**Description**: 
The dungeon finder does not work when you queue within a group. Only works for solo queue. I am posting this issue and I do have the fix already so this is just a placeholder.

I will open a PR for this.

**Steps to reproduce the problem**: 
1. Login the game with 5 clients
2. Create a character on each account at level 15
3. Join 4 of the players party together.
4. Leave the last account outside the party and queue solo
5. Attempt to queue and see that it will never find a player for your group.

**Expansion version**: 

    - Patch 3.3.5 - WoTLK
    - Patch 4.3.4 - Cataclysm
    - Patch 5.4.8 - Mop

**AscEmu hash/commit**: 
45ea4ad058b01d22bcdc45a13ae00ff85071bee7

**Operating system**: 

    - Platform: Windows

**Comment by schnek** [comment]
welcome back😉..

**Comment by Razfury** [comment]
fixed with #942
