### ISSUE TITLE
💡 [Feature Request] Save instance/raid progress server shutdown or crash

### ISSUE THREAD

**Issue by Razfury** [AscEmu/AscEmu#928]
**Description**: 

We need to implement the feature that MaNGOS/Trinitycore has that saves players current instance or raid progress whenever the server shuts down or crashes because currently it does not and it is a missing blizzlike feature.

1. Get a group together
2. Go to a dungeon kill mobs before a boss.
3. Shut the server down and log back in
4. Notice the bodies of the trash mobs are gone and shouldn't be.

**Comment by aaron02** [comment]
its implemented the database table is just empty
