### ISSUE TITLE
👾 [Bug Report] Character Dies on Level Up

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#931]
**Description**: 
make a new character. type .char set level 9 and he dies and cannot be revived again. by setting back hes level below 9 he is alive again

not tested all levels but above level 31 he is alive again

**Expansion version**: 
    - Patch 3.3.5 - WoTLK

**Comment by Razfury** [comment]
Can you provide a video or a short so I can see what happens so I can investigate this further?

**Comment by aaron02** [comment]
![image](https://user-images.githubusercontent.com/1266630/137628561-64eba3ee-964d-4454-b675-8d3913e50cbf.png)
health gets set too high then the client sets the player as dead

**Comment by aaron02** [comment]
![image](https://user-images.githubusercontent.com/1266630/137630891-98df828f-972d-43fe-87b1-ed5fdecb2823.png)

test = 92
test2 = 32
test 3 = 22
test 4 = 100

so base hp is test - test4 which results in -8

in the calculation we get below 0

**Comment by Zyres** [comment]
Can't reproduce the issue. Created tauren and bloodelf...
