### ISSUE TITLE
👾 [Bug Report] Starting Skills Spells not Correct

### ISSUE THREAD

**Issue by aaron02** [AscEmu/AscEmu#934]
**Description**: 
New Characters are missing Skills or have to much skills.
Warriors have Berserk Stance and Dev stance which is not correct they should start only with battle stance the others are behind quests
Paladins Start with a Mount and Riding Skill 75 also all Auras unlocked 

![image](https://user-images.githubusercontent.com/1266630/137622375-edc2677d-6e2b-4458-9e53-637f21d0c836.png)

![image](https://user-images.githubusercontent.com/1266630/137622483-d83c699e-3157-4a57-9930-095d40b99cf1.png)

**Steps to reproduce the problem**: 
1. Make a new Character
2. Login
3. Show at the skills tab and notice u only have the languages

**Expansion version**: 
    Specify version - is required:
    - Patch 3.3.5 - WoTLK only testet on wotlk

**AscEmu hash/commit**: 

**Operating system**:

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/ea1547bc32b19be78d40dcc970a6dbf395be6cf3
