### ISSUE TITLE
👾 [Bug Report] npc cannot be attacked (cata undead)

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#959]
**Description**: 

you cannot attack npc (cata undead) if you exit and enter everything is fine

**Steps to reproduce the problem**: 
1. select cata version create new undead

**Expansion version**: 

Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 

latest dev

**Comment by Appled** [comment]
Confirmed, seems to be related to stun auras. You can also reproduce this with any character, just cast a stun spell on yourself and remove it with GM command and see how you cannot attack neutral mobs. You can however attack hostile mobs. This works in wotlk so are we missing some sort of state update packet somewhere?

**Comment by Appled** [comment]
New issue with more info https://github.com/AscEmu/AscEmu/issues/966
