### ISSUE TITLE
💡 [Feature Request] Trainer templates

### ISSUE THREAD

**Issue by Appled** [AscEmu/AscEmu#962]
**Description**: 
We have over 70k entries in trainer_spells table. We should create new table called trainer_templates or smth where we store templates for trainers. Template contains specificed spells and if we set trainer to use this template the trainer would teach all spells from that template. With templates we wouldn't need for example to set all mage trainers to teach Fireball rank 2. This will reduce tons of rows in trainer_spells table.

Class spells would need at least two templates per class if I recall correctly; lowlevel template which contains spells from level 1-6 (starting area trainers) and full template which contains all spells. So for example we put all rogue spells to template id 10 and then we would set all rogue trainers (except starting area trainers) to use that template.

Profession trainers are little bit trickier. @aaron02 can probably elaborate on this but in wotlk we would need 4 templates for each profession types; Artisan template which contains professions ranks and recipes up till skill level 300, Master template which contains previous template and profession ranks and recipes up to skill level 375, Grand Master template which contains previous template and profession ranks and recipes up to skill level 450.
In addition, some professions also have specialization trainers like Blacksmithing has Armorsmithing and Weaponsmithing. These would also need their own templates.
However, in Classic, we would need 4 different templates for each profession types; Apprentice template up to skill level 75, Journeyman template with previous template and up to skill level 150, Expert with previous template and up to skill level 225 and Artisan with previous template and up to skill level 300. This was changed in mid-TBC so that in "old world" all trainers can teach up to skill level 300 while Outlands still had their own trainers for Master (up to 375).

**Comment by Zyres** [comment]
We could create one template for class trainers and add a trainer level column to it. But I guess to keep it simple we could create two templates.

I would go over the current trainer_spells table and create templates from our current data.

**Comment by schnek** [comment]
yes the template is a great idea. if we take an example https://github.com/AscEmu/AscEmu/issues/1069 the problem itself is solved but the npc id does not work as it should.

**Comment by Zyres** [comment]
Update: trainers differ a lot, I guess we could create a template but still have to add trainer specific spells too.

**Comment by Appled** [comment]
> Update: trainers differ a lot, I guess we could create a template but still have to add trainer specific spells too.

How so? Class trainers shouldn't need a template. If i.e warrior trainers have two templates (low level and normal template) then all warrior trainers should have exactly those same spells. Only special cases are shaman and paladin who have just couple faction specific spells but that can be sorted by adding an optional racemask field to template.

**Comment by Zyres** [comment]
Okay, give me a few minutes, working on it.

**Comment by Appled** [comment]
Also, the template racemask field is needed in classic and tbc as well for priests. Priests have "racial spells" that are only available to certain races. Like Devouring Plague is only available for undead priests and Desperate Prayer is only available for dwarves and humans.
But since i.e. Devouring Plague is made available for all priests in wotlk the template also need min and max build versions 😉

**Comment by Zyres** [comment]
Okay, so unfortunately I have only the current data (wotlk). For this I wrote the following query which creates "trainer_properties" and "trainer_properties_spells" table.
I've included two column "can_train_level" and "can_train_skill_value" with the goal to reduce these "templates" more by checking trainers_properties_spell column reqlevel and reqskillvalue, but that is just a wild guess.

`/*create new table for trainer properties and copy data/structure from old table*/
DROP TABLE IF EXISTS `trainer_properties`;
CREATE TABLE `trainer_properties` AS SELECT * FROM `trainer_defs`;

/*add new columns*/
ALTER TABLE `trainer_properties` ADD COLUMN `build` INT DEFAULT 12340 AFTER `entry`;
ALTER TABLE `trainer_properties` ADD COLUMN `trainer_properties_spell` INT DEFAULT 0 AFTER `cannot_train_gossip_textid`;
ALTER TABLE `trainer_properties` ADD COLUMN `can_train_level` INT DEFAULT 0 AFTER `trainer_properties_spell`;
ALTER TABLE `trainer_properties` ADD COLUMN `can_train_skill_value` INT DEFAULT 0 AFTER `can_train_level`;
ALTER TABLE `trainer_properties` ADD COLUMN `comment` VARCHAR(250) DEFAULT '' AFTER `trainer_properties_spell`;

/*add subname to help us*/
UPDATE `trainer_properties` t1, `creature_properties` t2
SET t1.comment = t2.subname, t1.build = t2.build
WHERE t1.entry = t2.entry;

/*Add trainer_properties_spell id (template) to the trainer_properties (based on old trainer_spells table*/
UPDATE `trainer_properties` SET `trainer_properties_spell` = 99 WHERE `entry` IN(1317,3011,3345,3606,4213,4616,5157,5695,7949,11072,11073,11074,16160,16633,16725);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 98 WHERE `entry` IN(18753,18773,19251,19252,19540,33633,33676);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 97 WHERE `entry` IN(33610);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 96 WHERE `entry` IN(2818);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 95 WHERE `entry` IN(1676,1702,3290,3494,5174,5518,8736,10993,11017,11025,11031,11037,16667,16726,17222);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 94 WHERE `entry` IN(33634);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 93 WHERE `entry` IN(33677);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 92 WHERE `entry` IN(25277,26907,26955,26991,28697,33586,33611);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 91 WHERE `entry` IN(17637);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 90 WHERE `entry` IN(19576);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 9 WHERE `entry` IN(925,926,15280,16501);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 89 WHERE `entry` IN(18775);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 88 WHERE `entry` IN(18752);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 87 WHERE `entry` IN(17634);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 86 WHERE `entry` IN(2326,2327,2329,2798,3181,3373,4211,4591,5150,5759,5939,5943,6094,16272,16662,16731,17214,17424,19184,19478,22477);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 85 WHERE `entry` IN(18990,18991);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 84 WHERE `entry` IN(23734,26956,26992,28706,29233,33589,33621);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 83 WHERE `entry` IN(1681,1701,3001,3137,3175,3357,3555,4254,4598,5392,5513,6297,8128,16663,16752,17488,18804);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 82 WHERE `entry` IN(18747,18779,33640,33682);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 81 WHERE `entry` IN(26912,26962,26976,26999,28698,33617);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 80 WHERE `entry` IN(1355,1382,1430,1699,3026,3067,3087,3399,4210,4552,5159,5482,6286,8306,16253,16277,16676,16719,17246,19185,19369,34708,34710,34711,34712,34713,34714,34785,34786);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 79 WHERE `entry` IN(18987,18988,18993);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 78 WHERE `entry` IN(26905,26953,26972,26989,28705,29631,33587,33619);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 77 WHERE `entry` IN(1103,1346,2399,2627,3004,3363,3484,3523,3704,4159,4193,4576,5153,11052,11557,16366,16640,16729,17487);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 76 WHERE `entry` IN(18749,18772,33636,33684);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 75 WHERE `entry` IN(26914,26964,26969,27001,28699,33580,33613);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 74 WHERE `entry` IN(26910,26958,26974,26994,28704,33616);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 73 WHERE `entry` IN(18748,18776,33639,33678);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 72 WHERE `entry` IN(812,908,1218,1458,1473,2114,2390,2856,3013,3185,3404,3604,3965,4204,4614,4898,5137,5502,5566,8146,12025,16367,16644,16736,17434,17983,33996);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 71 WHERE `entry` IN(17215);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 70 WHERE `entry` IN(1215,1386,1470,2132,2391,2837,3009,3184,3347,3603,3964,4160,4611,4900,5177,5499,7948,16161,16642,16723);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 7 WHERE `entry` IN(16275,16679,16680,16681,20406,23128);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 69 WHERE `entry` IN(16588,18802,19052,27023,27029,33630,33674);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 68 WHERE `entry` IN(33608);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 67 WHERE `entry` IN(26911,26961,26998,28700,33581);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 66 WHERE `entry` IN(26996,33612);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 65 WHERE `entry` IN(18754,18771,19187,21087,33635,33681);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 64 WHERE `entry` IN(1385,1632,3007,3069,3365,3549,3605,3703,3967,4212,4588,5127,5564,5784,8153,11097,11098,16278,16688,16728,17442);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 63 WHERE `entry` IN(514,1241,2836,2998,3136,3174,3355,3478,3557,4258,4596,5511,6299,15400,16669,16724,17245);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 62 WHERE `entry` IN(26564,26904,26952,26981,26988,27034,28694,29924,33591,33609);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 61 WHERE `entry` IN(16583,16823,19341,33631,33675);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 60 WHERE `entry` IN(13084);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 6 WHERE `entry` IN(927,928,1232,5147,5148,5149,5491,5492,8140,16761,17121,17483,17509,17844,35281);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 59 WHERE `entry` IN(11866);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 58 WHERE `entry` IN(11870);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 57 WHERE `entry` IN(16621,17005);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 56 WHERE `entry` IN(11867);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 55 WHERE `entry` IN(11869);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 54 WHERE `entry` IN(16773);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 52 WHERE `entry` IN(11868);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 51 WHERE `entry` IN(2704);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 50 WHERE `entry` IN(11865);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 5 WHERE `entry` IN(911,912,2119,3059,3153,3593,16503);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 49 WHERE `entry` IN(20914);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 48 WHERE `entry` IN(16280);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 47 WHERE `entry` IN(7953);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 46 WHERE `entry` IN(7954);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 45 WHERE `entry` IN(3690);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 44 WHERE `entry` IN(4773);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 43 WHERE `entry` IN(4753);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 42 WHERE `entry` IN(4772);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 41 WHERE `entry` IN(4752);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 40 WHERE `entry` IN(4732);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 4 WHERE `entry` IN(913,914,985,1229,1901,2131,3041,3042,3043,3063,3169,3353,3354,3408,3598,4087,4089,4593,4594,4595,5113,5114,5479,5480,7315,8141,16771,17120,17480,17504);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 39 WHERE `entry` IN(28746,31238,31247);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 38 WHERE `entry` IN(20500,20511,35093,35100,35133,35135);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 37 WHERE `entry` IN(3060,3597);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 36 WHERE `entry` IN(3033,3034,3036,3064,3602,4217,4218,4219,5504,5505,5506,8142,9465,12042,16655,16721);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 35 WHERE `entry` IN(459,460,2126,3156,15283);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 34 WHERE `entry` IN(461,906,988,2127,3172,3324,3325,3326,4563,4564,4565,5171,5172,5173,5495,5496,5612,16266,16646,16647,16648,23534);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 33 WHERE `entry` IN(29156);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 32 WHERE `entry` IN(27703);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 31 WHERE `entry` IN(27705);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 30 WHERE `entry` IN(19340);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 29 WHERE `entry` IN(20791);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 28 WHERE `entry` IN(16654);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 27 WHERE `entry` IN(16755);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 26 WHERE `entry` IN(5958);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 25 WHERE `entry` IN(5957);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 24 WHERE `entry` IN(4165);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 23 WHERE `entry` IN(2492);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 22 WHERE `entry` IN(2489);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 21 WHERE `entry` IN(2485);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 20 WHERE `entry` IN(198,944,2124,15279,16500);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 2 WHERE `entry` IN(6251);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 19 WHERE `entry` IN(328,331,1228,2128,3047,3048,3049,4566,4567,4568,5144,5145,5146,5497,5498,5880,5882,5883,5884,5885,7311,7312,16269,16651,16652,16653,16749,17105,17481,17513,17514,23103,27704,28956,28958);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 18 WHERE `entry` IN(3062,3157,17089);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 17 WHERE `entry` IN(986,3030,3031,3032,3066,3173,3344,3403,13417,17204,17212,17219,17519,17520,20407,23127);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 16 WHERE `entry` IN(28471,28472,28474,29194,29195,29196,31084);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 15 WHERE `entry` IN(375,837,2123,3707,15284,16502,17482);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 14 WHERE `entry` IN(376,377,1226,2129,3044,3045,3046,3595,3600,3706,4090,4091,4092,4606,4607,4608,5141,5142,5143,5484,5489,5994,6014,6018,11397,11401,11406,16276,16658,16659,16660,16756,17510,17511);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 13 WHERE `entry` IN(915,916,2122,3155,3594,15285);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 127 WHERE `entry` IN(5164,7230,11177,20125);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 126 WHERE `entry` IN(7231,7232,11146,11178,20124,29505);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 125 WHERE `entry` IN(26903,26951,26975,26987,28703,33588);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 124 WHERE `entry` IN(30706,30709,30710,30711,30713,30715,30716,30717);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 123 WHERE `entry` IN(30721,30722,33638,33679);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 122 WHERE `entry` IN(26916,26959,26977,26995,28702,33603,33615);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 121 WHERE `entry` IN(24868,25099);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 120 WHERE `entry` IN(19186);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 12 WHERE `entry` IN(917,918,1234,1411,2130,3170,3327,3328,3401,3599,4163,4214,4215,4582,4583,4584,5165,5166,5167,6707,13283,16279,16684,16685,16686);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 117 WHERE `entry` IN(26906,26954,26980,26990,28693,33583);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 116 WHERE `entry` IN(15501,19775,19778);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 115 WHERE `entry` IN(18751,18774,19539,33637,33680);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 114 WHERE `entry` IN(19063,26915,26960,26982,26997,28701,33590,33614);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 112 WHERE `entry` IN(7406,7944,29514);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 111 WHERE `entry` IN(4578,9584);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 110 WHERE `entry` IN(7868,7869,29507);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 11 WHERE `entry` IN(895,3061,3154,3596,15513,16499);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 109 WHERE `entry` IN(7870,7871,29509);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 108 WHERE `entry` IN(7866,7867,29508);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 107 WHERE `entry` IN(29506);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 106 WHERE `entry` IN(8126,8738,29513);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 105 WHERE `entry` IN(26913,26963,26986,27000,28696,33618);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 104 WHERE `entry` IN(18755,18777,19180,33641,33683);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 103 WHERE `entry` IN(1292,6287,6288,6289,6290,6291,6292,6295,6306,6387,7087,7088,7089,8144,12030,16273,16692,16763,17441);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 102 WHERE `entry` IN(18911);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 101 WHERE `entry` IN(1651,1680,1683,1700,2367,2834,3028,3179,3332,3607,4156,4573,5161,5493,5690,5938,5941,7946,12032,12961,14740,16774,16780,17101,18018);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 100 WHERE `entry` IN(26909,26957,26993,28742,32474,33623);
UPDATE `trainer_properties` SET `trainer_properties_spell` = 10 WHERE `entry` IN(987,1231,1404,3038,3039,3040,3065,3171,3352,3406,3407,3601,3963,4138,4146,4205,5115,5116,5117,5501,5515,5516,5517,8308,10930,16270,16672,16673,16674,16738,17110,17122,17505);

/*Add column temp_id to old table trainer_spells*/
/*ALTER TABLE `trainer_spells` DROP COLUMN `temp_id`;*/
ALTER TABLE `trainer_spells` ADD COLUMN `temp_id` INT DEFAULT 0 AFTER `deletespell`;

/*Add temp_id values to old table*/
UPDATE `trainer_spells` t1, `trainer_properties` t2 
SET t1.temp_id = t2.trainer_properties_spell
WHERE t1.entry = t2.entry;

/*create new table fo trainer spell definitions and copy data/structure from old table*/
DROP TABLE IF EXISTS `trainer_properties_spells`;
CREATE TABLE `trainer_properties_spells` (
  `id` int unsigned NOT NULL DEFAULT '0',
  `min_build` int unsigned NOT NULL DEFAULT '4044',
  `max_build` int unsigned NOT NULL DEFAULT '15595',
  `cast_spell` int unsigned NOT NULL DEFAULT '0',
  `learn_spell` int unsigned NOT NULL,
  `spellcost` int unsigned NOT NULL DEFAULT '0',
  `racemask` int unsigned NOT NULL DEFAULT '0',
  `reqspell` int unsigned NOT NULL DEFAULT '0',
  `reqskill` int unsigned NOT NULL DEFAULT '0',
  `reqskillvalue` int unsigned NOT NULL DEFAULT '0',
  `reqlevel` int unsigned NOT NULL DEFAULT '0',
  `deletespell` int unsigned NOT NULL DEFAULT '0',
  UNIQUE KEY (`id`,`min_build`,`cast_spell`,`learn_spell`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Trainer System';

/*Add data from our old table to the new one. we replace all data with key id, cast_spell, learn_spell so we end up with unique spells for each id*/
REPLACE INTO `trainer_properties_spells` (`id`, `cast_spell`, `learn_spell`, `spellcost`, `reqspell`, `reqskill`, `reqskillvalue`, `reqlevel`, `deletespell`)
SELECT `temp_id`, `cast_spell`, `learn_spell`, `spellcost`, `reqspell`, `reqskill`, `reqskillvalue`, `reqlevel`, `deletespell` FROM `trainer_spells`;
`

**Comment by Appled** [comment]
Looking good but I'm still not sure if you can reduce templates with "can_train_level" and "can_train_skill_value" columns. Also, I think maxbuild column is required as well since some spells were removed later from game?

**Comment by Zyres** [comment]
min/max_build is inside trainer_properties_spells to define which spells are valid for the version.
build in trainer_properties defines since when the creature is a trainer, no need fo a max_build value (e.g. creature_properties)

**Comment by Appled** [comment]
> min/max_build is inside trainer_properties_spells to define which spells are valid for the version.

Oh yeah of course XD

> I'm pretty sure that can_train_level and can_train_skill_value is enough, at least according to our current data.
> 
> If we would update trainer_properties with "can_train_level" with 80 and 6, we could save the template 13 since template 12 includes all spells up tp level 80:

Ahh yeah now I understand what you mean with these columns. Yeah they should work fine for both class and profession trainers. I don't see any issues why wouldn't they.

**Comment by Appled** [comment]
> I guess 3127 is wrong here

Hmm, I can't recall when rogues did learn Parry but according to Wowpedia from 2010 and 2007 they should learn it at level 12, not at level 1.

**Comment by Zyres** [comment]
Check out develop https://github.com/AscEmu/AscEmu/commit/2b2e82e745d420719b1f46c63c0f219fd550b9d7

**Comment by Appled** [comment]
Cool, I'll test it later today or tomorrow 🥳

**Comment by Appled** [comment]
Class trainers seem to work fine. However I noticed some issues with profession trainers where they have some spells which they shouldn't teach, like a trainer in Elwynn Forest shouldn't teach a recipe from Outlands.
I don't have time atm to do a thorough testing but I'll try to make you a todo list in few days 😉

**Comment by Appled** [comment]
Uhh, that was painful.

### Blacksmithing:
Spellset 61

In trainer_properties NPCs with can_train_min_skill_value == 300 should use a new spellset that has spells from NPC id 4258 from old table.

NPCs with can_train_min_skill_value == 350 OR can_train_max_skill_value == 350 should use a new spellset that has spells from NPC id 16583 from old table.
Also, NPC id 33609 should use this new spellset.

### Leatherworking
Spellsets 64-67

Spellset 66 can be fully removed.
NPC id 26996 should use spellset 67 and NPC id 33612 should use spellset 65.

### Alchemy
Spellset 69

NPCs with can_train_max_skill_value == 325 but excluding NPC ids 16588, 18802, 19052, 27023, 27029, 33630, 33674 should use a new spellset that has spells from NPC id 1215 from old table.

### Herbalism
Spellsets 73-74

NPC id 33616 should use spellset 73.

### Tailoring
Spellsets 75-77

NPC id 33613 should use spellset 76.

### Cooking
Spellset 78

NPC id 33619 should have can_train_max_skill_value at 275.

### Mining
Spellsets 81-83

NPC id 33617 should use spellset 82.

### First Aid
Spellsets 84-86

NPC id 33621 should use spellset 85.

### Engineering
Spellsets 87, 90, 92, 93

NPCs with id 17637, 19576, 33611, 33634, 33677 should use spellset 87.
Spellset 90 can be fully removed.

Remove all spells from spellset 93 and replace them with spells from NPC id 1676 from old table.

### Enchanting
Spellsets 97-98

NPCs with id 18753, 18773, 19252, 19540, 33610, 33633, 33676 should use a new spellset that has spells from NPC id 18753 from old table.
Spellset 97 can be fully removed.

NPCs with can_train_max_skill_value == 295 or with id 19251 should use a new spellset that has spells from NPC id 1317 from old table.

Remove all spells from spellset 98 and replace them with spells from NPC id 26906 from old table.

### Fishing
Spellset 100

NPC id 33623 should have can_train_max_skill_value at 275.

### Skinning
Spellset 105

NPCs with can_train_max_skill_value == 25, change to 200.
NPCs with can_train_max_skill_value == 40 or NPC id is 33618, change to 275.

### Jewelcrafting
Spellsets 114-116

NPCs with id 19063 and 33614 should use spellset 115.

### Inscription
Spellsets 122-124

NPC with id 33615 should use spellset 123.

**Comment by Appled** [comment]
Found couple more

### Blacksmithing
Spellsets 61-63
[ ] All NPCs in these spellsets should have can_train_min_skill_value and can_train_max_skill_value at 0.

### Alchemy
Spellsets 68-70
[ ] NPC with id 33608 should use spellset 69.
[ ] Spellset 68 can be fully removed.

### Cooking
Spellset 78
[ ] NPCs with can_train_max_skill_value == 0 should use a new spellset that has spells from NPC id 26905 from old table.

Wotlk faction specific class spells were already in the table so after these it's done and this can be closed 🎉

**Comment by schnek** [comment]
https://github.com/AscEmu/AscEmu/issues/1099 if you do not have this problem, the problem may be due to problems in the "regional clients"..
