### ISSUE TITLE
👾 [Bug Report] fishing not working

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#990]
**Steps to reproduce the problem**: 

use a fishing rod... (distance problem)

**Expansion version**: 

Patch 3.3.5 - WoTLK

**AscEmu hash/commit**: 

latast develop

**Comment by Appled** [comment]
Fixed in https://github.com/AscEmu/AscEmu/commit/d1f180970f80f00c961f5a96349e33af98728bc6
